- sources/engine/Xenko.Engine/Starter/iOSXenkoView.cs
When implementing full page or interstitial ads such as google admob a black screen appears on any iOS device after the ad is loaded. This is a known problem with OpenTK-1.1 and the solution is to override WillMoveToWindow in iPhoneOSGameView so as to not suspend the window which causes the problem.
FYI, I had this patch done for me back in version 1.10.2 beta by Virgile and i hoped it would propagate into the other versions but my guess is no one was/is using full page ads in their game(s) yet
> Interstitial ads black screen issue

- sources/engine/Xenko.Assets/XenkoConfig.cs
Checking for Android, iOS, and UWP packages should now be up-to-date for VS2017 and still work with VS2015 for issue #42 
I tried to make it somewhat expandable via Version-to-path dictionaries with a default. They shouldn't need to be updated unless a package path changes.
I... Couldn't find a better iOS package to check for. That was the only one to mention iOS, unless that's rolled into Xamarin.VisualStudio.Apple.Sdk? Any suggestions for better packages would be much appreciated!
> Updated Package Support Checks

- sources/editor/Xenko.GameStudio/View/AboutPage.xaml
- sources/editor/Xenko.GameStudio/View/AboutPage.xaml.cs
Using `Task.Result` blocks the calling thread (here main UI thread) while the task is not completed.
Replaced with a proper async method and a `DependencyProperty`.
> [GameStudio] Don't block the UI thread while loading the Backers file.

- sources/engine/Xenko.UI/Controls/TextBlock.cs
Prevent TextBlock from throwing null reference exception when WrapText is set to true and the value of text is null. Fixes issue#82
> Fix null reference exception thrown when TextBlock text is null.

- sources/engine/Xenko.Physics/Simulation.cs
Workaround for [issue #88](https://github.com/xenko3d/xenko/issues/88).  Logs a Warning instead of throwing an exception.  Easily to reproduce via:
* In TopDownRPG, punch a cube, pick up coins, issue is triggered.
* In PhysicsSample, change scenes to trigger.
While playing with PhysicsSample, I started to get the feeling that it was related to objects disappearing from the scene, but not being fully removed from the physics simulation?
> change physics exception to log a warning instead

- sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptEditor/SimpleCodeTextEditor.cs
Fixes issue #110. 
Once "CaretOnPositionChanged" is called, cancels the previous working call through its cancellation token. The exception generated through that token has to be caught somewhere, this pull catches it where it should be most relevant.
> Fix GameStudio crashing when editing files with the simple code editor

- sources/engine/Xenko.Video/FFmpeg/VideoStream.cs
This is a hotfix for #95 and further investigation will be needed to properly fix it.
Context:
When importing a `.mp3` file, the media library gets stream information from the file using the ffmpeg library. For some reason, the library believes that the file contains 2 streams: one audio and one video. The video one contains invalid data (notably a framerate of 0) which causes an invalid arithmetic operation.
This hotfix simply prevents the invalid arithmetic operation.
> [Media] Fix System.OverflowException when importing audio

- sources/core/Xenko.Core.Mathematics/Double2.cs
- sources/core/Xenko.Core.Mathematics/Double3.cs
- sources/core/Xenko.Core.Mathematics/Double4.cs
- sources/core/Xenko.Core.Mathematics/Half2.cs
- sources/core/Xenko.Core.Mathematics/Half3.cs
- sources/core/Xenko.Core.Mathematics/Half4.cs
As I stated in [my previous PR](https://github.com/xenko3d/xenko/pull/62), if that didn't get merged I would create a PR that just adds Double2/3/4 types (and also I made a few grammar tweaks and fixed inconsistencies). 
Unlike my previous PR, this does NOT change anything to `real_t` and does NOT add Single2/3/4. It does not change any existing code. I don't think anyone would object to adding Double2/3/4 math types built-in for users who wish to do their own math in double-precision without having to re-implement built-in types.
Plus, some of the grammar and wording was incorrect and inconsistent, I've fixed some of that.
> [Math] Add Double2/3/4 only, fix grammar and inconsistencies

- sources/editor/Xenko.Assets.Presentation/AssetEditors/ScriptEditor/SimpleCodeTextEditor.cs
Properly fixes #110.
Catching `TaskCanceledException` was not enough has sometimes the base exception (`OperationCanceledException`) is directly thrown.
> [Editor] Catch base exception in case of task cancellation.

- sources/editor/Xenko.Assets.Presentation/AssetEditors/EntityHierarchyEditor/ViewModels/EntityHierarchyRootViewModel.cs
The root node in the prefab or scene editors should not be editable.
> [Editor] Prevent editing the prefab root or the scene root (fixes #150)

- sources/editor/Xenko.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Views/EntityHierarchyEditorView.xaml
- sources/editor/Xenko.Core.Assets.Editor/Components/TemplateDescriptions/ViewModels/NewOrOpenSessionTemplateCollectionViewModel.cs
- sources/editor/Xenko.Core.Assets.Editor/View/AssetViewUserControl.xaml
- sources/editor/Xenko.Core.Assets.Editor/View/CommonResources.xaml
Moved the render mode dropdown next to the editor camera settings, leaving it next to the translation mode doesn't make a lot of sense.
On the project selection window, the default tab selected points to recent projects instead of new when the user already has one.
The other changes can be seen in the two screenshots below, they are described right under.
In the asset view pane, reduced the font size, weight and opacity of the asset's type, the name of the asset should be the most visually important element, the icon already serves the same purpose as that label does and users will more often find their assets by visually scanning through asset names first.
Added a separator between the asset view option and filter to avoid grouping them visually since they aren't related.
I'm not sure …
> [Editor] Minor UI tweaks.

- THIRD PARTY.md
- sources/editor/Xenko.Core.Assets.Editor/Resources/Images.resx
- sources/editor/Xenko.Core.Assets.Editor/Resources/Images/folder_128.png
- sources/editor/Xenko.Core.Assets.Editor/Resources/Images/folder_64.png
- sources/editor/Xenko.Core.Assets.Editor/Xenko.Core.Assets.Editor.csproj
Changes the image for folders in the asset view. double resolution as the image before. color as discussed in #143:
> [Editor] Flat folder icon

- sources/editor/Xenko.Core.Assets.Editor/ViewModel/EditorViewModel.cs
- sources/editor/Xenko.GameStudio/GameStudioWindow.xaml
This PR will be fixed the issue #195.
My first commit it's about the problem with the UI update on editor when you clean the list of recent projects, apparently it's not possible to use an ObservableCollection with value converter `Take`, I don't know why this, because to use a converter is the best solution as informed here [Creating a WPF ItemSource Length Filter Converter](https://weblog.west-wind.com/posts/2018/Jun/23/Creating-a-WPF-ItemSource-Length-Filter-Converter). I had tried many different solutions using it, but none works.
> [Game Studio] Recent files property update notification fixed

- sources/engine/Xenko.Physics/Engine/PhysicsProcessor.cs
Set RenderGroup of new debug shape when ColliderShapesRendering is enabled.
[Edit]
New debug shape is set RenderGroup.Group0 when the visualization by DebugPhysicsShapes is enabled.
In the case, it will not be rendered even if you add new entity with PhysicsComponent in current scene.
(Need to disable and re-enable the visualization once)
I used DebugPhysicsShapes script and this script to reproduce.
```csharp
using System;
using System.Linq;
using Xenko.Core.Mathematics;
using Xenko.Engine;
using Xenko.Extensions;
using Xenko.Graphics.GeometricPrimitives;
using Xenko.Input;
using Xenko.Physics;
using Xenko.Rendering;
using Xenko.Rendering.Materials;
using Xenko.Rendering.Materials.ComputeColors;
namespace MyGame
{
public class AddSphereScript : SyncScript
{
public Vector3 DropPoint = new …
```
> [Physics] Set RenderGroup of new debug shape

- sources/core/Xenko.Core.Mathematics/Int2.cs
- sources/core/Xenko.Core.Mathematics/Int3.cs
- sources/core/Xenko.Core.Mathematics/Int4.cs
The previous methods would always produce `inv` == 0, and thus normalization would always zero-out the vector components.
> Fix for `Normalize` methods of Int2 and Int3

- sources/engine/Xenko.Games/GameBase.cs
- sources/engine/Xenko.Games/WindowsStore/GameWindowUWP.cs
See [202](https://github.com/xenko3d/xenko/pull/202#issuecomment-424959027).
Implemented `visible` as well, not sure why it wasn't before.
> [UWP] Update window interface implementation

- sources/engine/Xenko.Games/Desktop/GameWindowWinforms.cs
Issue raised by [EssenRoc](https://github.com/xenko3d/xenko/pull/202#discussion_r223173370), window is treated as unfocused while editing text. 
Winforms' input system uses a hack to manage text input, it spawns a text box which gets focus when we request text input, focus only works on the window itself, this PR changes it so it includes component of the window as well into the focus check.
> [Winforms] Focus -> ContainsFocus

- sources/engine/Xenko.Graphics/Direct3D/Texture.Direct3D.cs
- sources/engine/Xenko.Graphics/Texture.cs
- sources/engine/Xenko.Graphics/TextureDescription.Extensions2D.cs
- sources/engine/Xenko.Graphics/TextureDescription.cs
- sources/engine/Xenko.Graphics/TextureOptions.cs
added SharedHandle to texture to create shared DirectX 11 textures. first tests worked fine with only using the Shared option. the SharedNthandle part is optional.
> [Graphics] Added SharedHandle to texture

- sources/engine/Xenko.Graphics/Direct3D/PipelineState.Direct3D.cs
For example effect A sets a hull shader, effect B a compute shader and effect C only vertex and pixel shaders - the hull shader from effect A was now still set on the native device context leading to a broken draw call because when applying effect B the draw shaders were not cleared and follow up comparison when applying C failed.
> [Graphics] When mixing Dispatch and Draw calls in Direct3D11 the set shaders on the native device context got mixed up.

- sources/engine/Xenko.Graphics/Buffer.Vertex.cs
- sources/engine/Xenko.Graphics/BufferFlags.cs
- sources/engine/Xenko.Graphics/Direct3D/Buffer.Direct3D.cs
- sources/engine/Xenko.Graphics/Direct3D/PipelineState.Direct3D.cs
the work was almost done, only someone forgot to build the proper stream out elements and add the matching buffer flag.
> [Graphics] fixed geometry shader with stream out 

- build/Xenko.Core.GlobalSettings.Local.targets
This reverts commit 2eb9a6f0b34b182026e7eda7255e86521419dba8.
had to revert this, because it crashes the shader compiler. the key files just contain an exception.
so this needs to be further tested by @SleepyMode or @xen2 before we can upgrade the solution to csharp 7.2.
in general i think it is better to upgrade only if there is a feature that is actually required. especially for big projects its always a risk to upgrade core parts.
> Revert "Update to C# 7.2 (#264)"

- sources/assets/Xenko.Core.Assets/Diagnostics/AssetLogMessage.cs
- sources/assets/Xenko.Core.Assets/Yaml/CollectionWithIdsSerializerBase.cs
- sources/core/Xenko.Core.Yaml/Serialization/DefaultObjectFactory.cs
- sources/core/Xenko.Core/Serialization/ClassDataSerializer.cs
- sources/editor/Xenko.Core.Assets.Editor/Themes/generic.xaml
- sources/editor/Xenko.Core.Assets.Editor/View/Controls/GridLogViewer.cs
- sources/presentation/Xenko.Core.Presentation/Controls/TextLogViewer.cs
- sources/presentation/Xenko.Core.Presentation/Themes/ExpressionDark/Theme.xaml
- sources/presentation/Xenko.Core.Presentation/Themes/generic.xaml
This PR implements a button on the log viewer's UI to show stacktraces and inner exceptions. It also wraps activator/constructor exceptions around a more generic exception to catch them more efficiently.
I'm also presenting a way to entirely ignore any constructor issues while still providing a workable object, see DefaultObjectFactory.cs line 118 and ClassDataSerializer.cs line 18.
Constructor exceptions crashes the editor while its open and block any attempt to open the project afterward. The log viewer doesn't explicitly tell the user what goes wrong when opening the project, this PR should clarify that issue.
If we *really* don't want to block the user from opening a project we could also use the solution mentioned above to bypass this issue and mention to the user that he should …
> [Serialization] Clarify some issues that users might encounter.

- sources/core/Xenko.Core/Threading/ThreadPool.cs
ThreadPool never close off the threads it spawns, see [Discord discussion](https://discordapp.com/channels/500285081265635328/500290856532574209/527465891529621514) for more details.
@Kryptos-FR I did a couple of changes, how would you deal with synchronization ?
> [Core] ThreadPool: shutdown idle threads

- sources/launcher/Xenko.Launcher/Resources/Strings.Designer.cs
- sources/launcher/Xenko.Launcher/Resources/Strings.resx
- sources/launcher/Xenko.Launcher/Resources/Urls.Designer.cs
- sources/launcher/Xenko.Launcher/Resources/Urls.resx
- sources/launcher/Xenko.Launcher/Resources/answerhub.png
- sources/launcher/Xenko.Launcher/Resources/patreon_mark_coral_24.png
- sources/launcher/Xenko.Launcher/Views/LauncherWindow.xaml
- sources/launcher/Xenko.Launcher/Xenko.Launcher.csproj
- sources/launcher/Xenko.LauncherApp/Xenko.LauncherApp.csproj
This PR is to update the links on the Xenko Launcher. 
Links on the Xenko Launcher were updated as follows:
* Update the Roadmap url to the github repository projects page.
* Add a tooltip status text to the link buttons so the user know where they will take them.
* Add a link to the Patreon page.
* Remove the AnswerHub link.
This PR was create after discussing the issue with @xen2 and @Kryptos-FR in the Xenko discord server. No GitHub issue has been created.
* The Roadmap url was updated because the Xenko project now uses GitHub projects instead of trello.
* Status tooltips for the links were added so users would know where the links would take them.
* A link to the Xenko Patreon page was added at @xen2's request.
* The AnswerHub link was removed because the Xenko project no longer uses …
> Update links in the Xenko Launcher.

- samples/Templates/FirstPersonShooter/FirstPersonShooter/Assets/MainScene.xkscene
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/Player/PlayerInput.cs
- sources/editor/Xenko.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityCameraService.cs
- sources/editor/Xenko.Assets.Presentation/Templates/Assets/Scripts/Camera/BasicCameraController.cs
Fix BasicCameraController's mouse input, implements gamepad support, explain in detail common pitfalls of camera controller programming and fixes single frame lag on FPS sample's PlayerInput.
Redondant.
None logged on Github.
This mostly stemmed from this [Discord discussion](https://discordapp.com/channels/500285081265635328/500290856532574209/534784317319020555) I had a couple of weeks ago, creating this PR to fix the issue mentioned lower and clarify controller programming. This camera might very well be the first camera that users interact with, knowing that we might as well document thoroughly how it works and what users should do when modifying or creating one.
- There still is at least one frame of lag somewhere else inside the engine, it is fairly visible when binding mouse input …
> [Samples] Misc camera controller fixes

- docs/technical/editor-localization.md
- sources/editor/Xenko.Assets.Presentation/Xenko.Assets.Presentation.csproj
- sources/editor/Xenko.Core.Assets.Editor/Xenko.Core.Assets.Editor.csproj
- sources/editor/Xenko.Editor/Xenko.Editor.csproj
- sources/editor/Xenko.GameStudio/Xenko.GameStudio.csproj
- sources/presentation/Xenko.Core.Presentation/Xenko.Core.Presentation.csproj
If the path to the project contains any spaces, then the build steps for the localization files will fail.
Escape all paths in the command line. Special case for`$(TargetDir)` that needs an extra `.` since otherwise the last quote is escaped as well.
None.
Building from sources will fail for users that have a space in the path where the sources are located. Especially annoying if the space is in the username.
> [Localization] Fix build for path containing spaces

- sources/engine/Xenko.Physics/Data/ConvexHullColliderShapeDesc.cs
Resolves #372.
The userdoc's meaning was the opposite of what it should be to match the current functionality.
Related to #372.
> [Physics] correct userdoc for convex hull collider parameters.

- sources/editor/Xenko.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityCameraService.cs
Fix issue #422 , cleaned up the function while I was at it.
Previously used the camera entity's matrix while the editor camera has its own matrix resulting in an identity instead of camera aligned panning direction.
#422 
See issue.
> [Editor] Panning direction Fix (#422)

- sources/presentation/Xenko.Core.Presentation.Tests/TestTypeExtensions.cs
- sources/presentation/Xenko.Core.Presentation.Tests/TestValueConverters.cs
- sources/presentation/Xenko.Core.Presentation.Tests/Xenko.Core.Presentation.Tests.csproj
- sources/presentation/Xenko.Core.Presentation/Extensions/TypeExtensions.cs
- sources/presentation/Xenko.Core.Presentation/ValueConverters/ObjectToTypeName.cs
This PR changes the `ObjectToTypeName` value converter to convert `object` `Type` to a prettier C# like style. 
This change makes the `ObjectToTypeName` value converter produce more meaningful names. The `Type` name returned has the following properties:
- Generic type parameters are included using C# like syntax. i.e. `<Type1, Type2>` instead of `'2`.
- Primitive types use the keyword syntax. i.e. `int` instead of `Int32`.
- `Nullable` types display using C# nullable syntax. i.e. `DateTime?` instead of `Nullable<DateTime>`.
- `ValueTuple` types display using C# tuple syntax i.e. `(int, string)` instead of `ValueTuple<int, string>`.
- Type names are not `namespace` or `class` name qualified. i.e. `DateTime` instead of `System.DateTime`. 
None
Currently when displaying a types name in the …
> Change the ObjectToTypeName value converter to give prettier C# names.

- sources/assets/Xenko.Core.Assets/PackageSessionPublicHelper.cs
- sources/assets/Xenko.Core.Assets/Xenko.Core.Assets.csproj
- sources/core/Xenko.Core.Tasks/Xenko.Core.Tasks.csproj
Added support for more MSBuild Toolset Versions.
#420
MSBuild Toolset Version 15.0 is not available anymore.
> Assets Compiler Support MSBuild Toolset Version 16.0 

- sources/engine/Xenko.Graphics/SDL/Window.cs
Makes window resizing work when the window is an SDL2 window.
It has been at least rudimentarily tested on my own machine.
https://github.com/xenko3d/xenko/issues/430 (really directly yoinked from phroot's change)
Previously `Game.Window.AllowUserResizing = true;` would be a no-op.
> Make SDL window user resizable.

- sources/engine/Xenko.Assets/Materials/MaterialAssetCompiler.cs
- sources/engine/Xenko.Rendering/Rendering/Materials/MaterialGeneratorContext.cs
- sources/engine/Xenko.Rendering/Rendering/Materials/ShaderGeneratorContext.cs
resetting shader key scope for multi pass materials
shader keys get a "i1" postfix for multi passe materials that would not be necessary.
- Bug fix (non-breaking change which fixes an issue)
> Resetting shader key scope for multi pass materials

- sources/engine/Xenko.Engine/Engine/Processors/CameraProcessor.cs
Fairly simple changes, the dirty check bool was never set back to false which forces cameras to be re-registered each frame.
See above.
None reported.
Fixes a bug.
> [Camera] Fix CamProcessor's cameraSlotsDirty branch running continuously

- sources/engine/Xenko.Engine/Engine/SceneInstance.cs
The collection can be changed through user code which might make the enum skip over items, this allocates and fills a temp array to store the collection state as is.
See above.
None reported.
Ex: A component removing another entity after being removed itself, the collection's enum implementation doesn't check back if the collection changed so it just continues from the index it left off on which might not be accurate anymore if the removed item's index lays at or before the enum's index.
The default .Net implementation would probably have thrown here, should we perhaps implement safeguards as well ?
> [SceneManagement] Fix loop skipping items when collection is modified

- sources/core/Xenko.Core/Threading/ThreadPool.cs
Title.
This PR has been benchmarked and, as expected given those changes, does not produce any performance difference besides faster initial run and slightly less allocation.
``Task.Factory.StartNew(ProcessWorkItems, TaskCreationOptions.LongRunning);`` maps to ``StartNew(Action(object), object)`` function signature instead of ``StartNew(Action(object), TaskCreationOptions)`` which, of course, didn't actually set the task as long running.
Cache the delegate we pass onto the task factory to reduce allocation.
Push as much stuff as possible outside of the lock.
Let exceptions fall into unhandled instead of ignoring them, if you have any better idea feel free to comment/start a review.
#302 
Bug, alloc.
>  [Threading] ThreadPool refactor, reduce allocation, fix wrong argument 

- sources/engine/Xenko.Graphics/Direct3D/CommandList.Direct3D.cs
Previously, unordered access views could only be bound to the compute stage. This patch lets them be bound to the output merger stage, so pixel shaders can read and write to them.
Much of the patch is based on how UAV binding for the compute stage works - there is an array of currently bound UAVs, and in SetUnorderedAccessView this is checked against and the UAV is bound if necessary.
However due to how Direct3D ties render targets and UAVs together (see [here](https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11devicecontext-omsetrendertargetsandunorderedaccessviews)), its also necessary to keep track of the number of bound render targets, and to re-bind all the UAVs whenever one is changed. The patch prioritises render targets, in that if the targets and UAV …
> Add output merger UAV binding.

- sources/engine/Xenko.Games/GameSystemCollection.cs
GameSystems removed from the collection are still being drawn and updated, this PR fixes that.
The default comparer used when removing from the list most likely check for both the key and the value, passing in a null when the profiling key for the item in the collection might not be null will fail to find a match and so it won't remove that item.
No known issues.
Fixes a bug.
> [GameSystems] Fix: removed gamesystem still runs update and draw

- sources/engine/Xenko.UI/Rendering/UI/UIRenderFeature.Picking.cs
Exposes the function-variable mouseOverElement as public property UIElementUnderMouseCursor. 
This could be used to consume a click when handling mouse input.
in file UIRenderFeature.Picking.cs:
the variable mouseOverElement (in private UpdateMouseOver() ) will be a public property with the name UIElementUnderMouseCursor 
#508
I havent found a method to get the control under the mouse, 
which i need to consume a click in my input handling when the click occured over an uiElement.
example: 
if the mouseclick is over an ui-button, 
currently the linked buttonevent will be fired and IsMouseButtonPressed is true
resulting in my selected unit moving AND a fired button event.
in this case only the button even should fire
and the test of IsMouseButtonPressed should be "blocked"
`if ( …
> [UI/INPUT] expose/change mouseOverElement as public property

- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/Core/Utils.cs
- sources/engine/Xenko.Physics.Tests/CharacterTest.cs
- sources/engine/Xenko.Physics.Tests/ColliderShapesTest.cs
- sources/engine/Xenko.Physics.Tests/SkinnedTest.cs
- sources/engine/Xenko.Physics/Simulation.cs
Removes helper function which allocs and returns a new list, I don't think we should guide users towards those kinds of functions and we already had quite a bit of discussion about excluding extensions-like methods from the main repo.
See above.
None.
See PR Details.
> [Physics] Remove helper functions which allocs new lists

- sources/core/Xenko.Core/Native/NativeLibrary.cs
If the given library wasn't found through the default paths, go through each paths set in the local executable's PATH variable.
See above.
None.
This mirrors how windows loads missing dlls and enables custom directory layouts (ex:one executable in root, dotnet dlls inside ``bin/`` and native libs inside ``bin/x64`` / ``bin/x86`` by modifying PATH at runtime).
> [LIB] Test executable PATH when preloading libraries

- sources/core/Xenko.Core/Utilities.cs
Swaps native memcpy with dotnet's Buffer.MemoryCopy, performs better in most cases, more detail at the bottom of this post.
Added Aggressive inlining attribute to help the JIT to strip potential conversion from void*->IntPtr->void*, we have a fairly large amount of code converting T* to IntPtr, not sure it's worth going through each one of those to manually strip them
See above.
None.
Helps performances.
Tests where done through BenchmarkDotNet on a Windows 10 x64 Ryzen 2700x. Release build.
```
NET CORE
|        Method |   Bytes |          Mean |         Error |        StdDev | Rank |
|-------------- |-------- |--------------:|--------------:|--------------:|-----:|
| msvcrt_memcpy |      64 |      8.297 ns |     0.0622 ns |     0.0581 ns |    4 |
| buffer_memcpy |      64 |      3.505 …
```
> [Core] memcpy -> dotnet Buffer.MemoryCopy

- sources/assets/Xenko.Core.Assets/PackageCollection.cs
Removing a package did not fire an event, so all assets of that package where still in the dependency manager.
> Package collection remove event

- sources/core/Xenko.Core/Threading/ThreadPool.cs
Replaced locking with semaphore+bag. Only a single thread is woken up per job queued up, they don't all hammer on the lock blocking further work from being queued up, this version should be more efficient and faster even more so for machines with many cores.
See above.
None.
Performances.
> [ThreadPool] Reduce lock contention

- sources/core/Xenko.Core.Serialization/Storage/ObjectDatabase.cs
- sources/engine/Xenko.Assets/Media/VideoAssetCompiler.cs
- sources/engine/Xenko.Video/Video.cs
- sources/engine/Xenko.Video/VideoInstance.Direct3D.cs
- sources/engine/Xenko.Video/VideoInstance.cs
- sources/engine/Xenko.Video/VideoSerializer.cs
in order to carry the original FileProvider with the deserialized video.
Video serialization and data base management impovements.
Remaining problem is that the `VideoInstance` assumes that the data is stored in a bundle. This fails if the video was loaded differently. See https://github.com/vvvv/xenko/blob/f9283cb46a63a43b68dd8ca309b4bb5f3fa6465d/sources/engine/Xenko.Video/VideoInstance.cs#L474
> Added VideoSerializer

- sources/engine/Xenko.Engine/Engine/TransformComponent.cs
``Scene`` does not get de-referenced when setting ``Transform.Parent`` afterwards leading to the entity potentially existing in two different scene or twice in the same scene (at the root and under the parent).
See PR Details.
None reported
Fixes a bug.
> [Transform] Fix Entity twice in scene

- sources/engine/Xenko.UI/Panels/Panel.cs
- sources/engine/Xenko.UI/Rendering/UI/UIRenderFeature.Picking.cs
- sources/engine/Xenko.UI/UIElement.Events.cs
- sources/engine/Xenko.UI/UIElement.cs
Fixed two instances where MouseOverState wasn't properly updated.
There were two instances where MouseOverState wasn't properly updated.
1. When an overred element was removed from the hierarchy (button click removes it from a panel) - With the element removed, it wasn't possible to update state of its parents and to invoke the hit test for the current overred element. Now, when element is removed from a panel and was overred, the parent state is updated to MouseOverNone. And, when when an element measure is invalidated, it is marked to require a hit test, in case it is the last overred element. This will also cover cases when the elements are animated under the cursor.
2. When more than a single UI was present in the scene - The issue was that the value for current overred element was …
> Fix mouse over state

- sources/editor/Xenko.Core.Assets.Editor/View/Behaviors/PropertyViewAutoExpandNodesBehavior.cs
Component properties with `ExpandRule.Auto` or `ExpandRule.Once` will remember their expand/collapsed states for the whole session.
The private property path `Hashset`s are changed to static so it's retained for the entire session.
One minor issue is if there's duplicate path names, they will affect each other. In the short term, this is probably not a big issue. In the long term, you'll probably want to do something like prefix all the paths will something unique?
Fixes #358
> [Editor] Remember expand/collapse states in property window

- sources/engine/Xenko.Games/Desktop/GameWindowWinforms.cs
- sources/engine/Xenko.Games/GameWindow.cs
- sources/engine/Xenko.Games/OpenTK/GameWindowOpenTK.cs
- sources/engine/Xenko.Games/SDL/GameWindowSDL.cs
Added an event that happens when the game window gets closed by the user.
The event happens before the window gets disposed. Implemented for Winforms, OpenTK, and SDL.
It allows the developer to react to the closing window in order to clean up resources before the window gets disposed.
> [Games] Added Closing event to GameWindow

- sources/core/Xenko.Core/PlatformFolders.cs
Binary directory can be one level below calling executable
This allows for a /bin or /lib (can have any name) folder next to the entry exe with all assemblies and data inside.
Have a clean build output folder. With a line in the exe.config file:
```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
<probing privatePath="lib" />
</assemblyBinding>
```
The output folder can be cleaned up like this:
before:
after:
> [Core] Binary directory can be one level below calling executable

- sources/engine/Xenko.Games/GameBase.cs
- sources/engine/Xenko.Games/GameContext.cs
- sources/engine/Xenko.Games/GameContextWinforms.cs
- sources/engine/Xenko.Games/GamePlatform.cs
Fixed logic for calling `Game.Tick()` from an external main loop.
Minimal invasive fix. Tested on Windows and works nicely if the calling application calls `Application.DoEvents()`.
Load and update a Game from another application.
> [Games] Fix external main loop support on windows

- sources/editor/Xenko.Core.Assets.Editor/View/Behaviors/TextBoxPropertyValueValidationBehavior.cs
- sources/editor/Xenko.Core.Assets.Editor/View/Behaviors/TextBoxVectorPropertyValueValidationBehavior.cs
- sources/editor/Xenko.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml
- sources/presentation/Xenko.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
- sources/presentation/Xenko.Core.Presentation/Controls/NumericTextBox.cs
- sources/presentation/Xenko.Core.Presentation/Controls/TextBoxBase.cs
The primary focus is to prevent the app from crashing due to invalid type conversion, and give the user an indication the data is not valid.
When the data conversion fails (eg. invalid color), it'll flash a red border three times and revert back (this reverting is done through some magic in the binding).
I don't have any expertise in WPF so this is the best I could, rather than try to do something like a tooltip message or toast.
While this is probably more of an excuse than an argument, Unity just reverts when invalid data is entered and has zero indicators.
I have changed `InvalidOperationException` to `InvalidCastException` because I believe this is the correct exception type for what the code is actually trying to do.
See #393, #534 for issues which should no longer crash with this …
> Prevent application crash when invalid property value is entered

- sources/core/Xenko.Core.Mathematics/Matrix.cs
- sources/engine/Xenko.Engine/Engine/TransformComponent.cs
EDIT: This pull has been changed to note the quirk with `Matrix.Multiply` rather than change it.
Add documentation to not use a `ref` variable as the `out` parameter for `Matrix.Multiply`, ie.
```
var matrix1 = // Some matrix
var matrix2 = // Some other matrix
Matrix.Multiply(ref matrix1, ref matrix2, out matrix2); // This will not correctly calculate matrix1 * matrix2
```
Add a `<remarks>` tag to `Matrix.Multiply`.
Fix code where `Matrix.Multiply` was used in the way above.
We cannot fix `Matrix.Multiply` to calculate the new matrix defensively because of performance degradation, so we tell them not to do it.
> Add note to Matrix.Multiply methods to not use a parameter as both ref and out

- sources/core/Xenko.Core/Utilities.cs
- sources/engine/Xenko.Engine/Updater/UpdateEngine.cs
- sources/engine/Xenko.Physics/Engine/PhysicsComponent.cs
- sources/engine/Xenko.Rendering/Extensions/IndexExtensions.cs
- sources/engine/Xenko/Graphics/DataBox.cs
- sources/engine/Xenko/Rendering/ParameterCollection.cs
These commits are aimed at reducing memory allocations, which in turn reduces the garbage collector being called to clean up the objects.
* Reduce the number of structs that get boxed due to missing IEquatable inheritance when used as a `Dictionary` key.
* Avoid structs being boxed (ie. another object allocation) in the object array in `ParameterCollection` when the currently stored value is the same as the incoming value.
* ~Reduce the number of times `RenderMesh` is created by fixing the mesh count logic check.~
* Use concrete classes when calling enumerator to get the struct enumerable to avoid object allocation.
For the `ParameterCollection` fix, I am unsure whether the second check is required or if it could just go into the same logic as the equality test.
To play it safe, if `<T>` …
> Reduce object allocation/boxing

- sources/engine/Xenko.Graphics/Sprite3DBatch.cs
- sources/engine/Xenko.Graphics/UIBatch.cs
These changes should make the UI slightly faster.
Mainly tried to figure out which variables could be declared upfront and pre-calculated so the loops are more straight forward.
Also, trying to strike a balance between code readability vs performance, so the methods like
`Vector4 Vector4Add(ref Vector4 v1, ref Vector4 v2)` is used instead of the standard `ref, ref, out` version.
I've only tested against the Menu sample template.
Here's the FPS of the game without this change:
Here's the FPS of the game with the changes applied:
> [Graphics] Slightly faster UIBatch and Sprite3DBatch

- sources/assets/Xenko.Core.Assets/Templates/TemplateManager.cs
Fixes a special case where I have explicitly included a Xenko package in my project, and Game Studio adds its own packages (in `ExtraPackages`) causing duplicate templates to appear (in the 'Add Asset' menu).
This change checks if any of the `ExtraPackage`s is already defined in the current session's packages and ignores re-adding them.
The truth is that all I want is access to `GizmoComponentAttribute` and `EntityGizmo` so that I can get my custom components in Game Studio to be clickable within the scene, but currently this requires referencing `Xenko.Assets.Presentation` to get to these classes, and I'm not really willing to make any massive changes to get this to work.
`ExtraPackages` also defines `Xenko.Assets.Presentation` so the concatenation duplicates the asset templates.
I'm …
> Fix Game Studio adding duplicate asset templates

- sources/core/Xenko.Core/Threading/Dispatcher.cs
- sources/core/Xenko.Core/Threading/ThreadPool.cs
This is a second attempt to implement some of #562 features, the logic implemented to reduce allocations from that PR has not been transferred over to this one, see the discussion [here](https://github.com/stride3d/xenko/pull/562#issuecomment-594200461) for more info.
- ThreadPool: Remove the last couple of allocations that the internal 'queue' might create when scheduling work.
- Dispatcher: Schedule work for other threads sooner and in bulk.
- Dispatcher: Continue through the frame as soon as work as been completed instead of waiting for other threads to wake up and signal before continuing even though there aren't any work left for them to deal with.
None.
Performances.
Note:
Previously the PR also took care of refactoring the dispatcher's logic into something more maintainable, less …
> [Threading] Dispatcher scheduling (cont. #562)

- sources/core/Xenko.Core.Mathematics/BoundingFrustum.cs
- sources/core/Xenko.Core.Mathematics/Color.cs
- sources/core/Xenko.Core.Mathematics/Color4.cs
- sources/core/Xenko.Core.Mathematics/ColorBGRA.cs
- sources/core/Xenko.Core.Mathematics/Plane.cs
- sources/editor/Xenko.Assets.Presentation/AssetEditors/UIEditor/Game/UILayoutHelper.cs
- sources/engine/Xenko.Graphics/OpenGL/PipelineState.OpenGL.cs
- sources/engine/Xenko.Graphics/Sprite3DBatch.cs
- sources/engine/Xenko.Graphics/SpriteFont.cs
- sources/engine/Xenko.Graphics/UIBatch.cs
- sources/engine/Xenko.Physics/Shapes/StaticPlaneColliderShape.cs
- sources/engine/Xenko.Rendering/Rendering/Lights/LightClusteredPointSpotGroupRenderer.cs
- sources/engine/Xenko.Rendering/Rendering/Lights/LightSkyboxRenderer.cs
- sources/engine/Xenko.Rendering/Rendering/RenderContext.cs
- sources/engine/Xenko.Rendering/Streaming/StreamingManager.cs
- sources/engine/Xenko.UI/Panels/Grid.cs
- sources/engine/Xenko/Rendering/ParameterCollection.cs
More minor perf tricks.
1. Inherit IEquatable where a struct is used as a dictionary key to avoid boxing.
2. StreamingManager & LightClusteredPointSpotGroupRenderer to remove items in reverse to avoid O(n^2). The StreamingManager performs a `FlushSync` on removal, so this might be a breaking change (ie. a subtle behavior change by flushing in reverse). The alternative is to use `RemoveAll` + predicate to ensure the behavior is consistent at a slight perf cost (see benchmark further down the page).
3. LightClusteredPointSpotGroupRenderer to use `ref` to avoid struct copies, initialize lights directly by array to avoid constant size checks in FastStructList Add method.
4. Faster BoundingFrustum constructor by avoid needless intermediate struct constructors/copying. A new `Plane.Normalize` …
> Yet another minor perf improvement pull

- sources/editor/Xenko.Assets.Presentation/AssetEditors/GameEditor/Services/EditorGameController.cs
- sources/editor/Xenko.Assets.Presentation/AssetEditors/GameEditor/Services/IEditorGameController.cs
- sources/editor/Xenko.Assets.Presentation/AssetEditors/GameEditor/ViewModels/GameEditorViewModel.cs
- sources/editor/Xenko.Core.Assets.Editor/Services/IAssetPreviewService.cs
- sources/editor/Xenko.Editor/EditorGame/Game/EditorServiceGame.cs
- sources/editor/Xenko.Editor/Preview/GameStudioPreviewService.cs
- sources/editor/Xenko.GameStudio/AssetEditorsManager.cs
- sources/editor/Xenko.GameStudio/DockingLayoutManager.cs
- sources/editor/Xenko.GameStudio/GameStudioWindow.xaml.cs
- sources/editor/Xenko.GameStudio/PreviewViewModel.cs
Throttle the game update and prevent draw calls for scene/prefab editors and the preview asset when they are hidden inside a tab in the editor.
Added `EditorServiceGame.IsEditorHidden` field to throttle the game updating to once per second, and stop the draw code.
~I tried to keep close to the current architecture.~ (Yeah, I don't think I can claim that anymore...)
A dockable sub-window's visibility can't be detected with `IsVisible`, no idea why...
What's actually required is testing `IsSelected`. This should work whether it's split or floating.
Unfortunately, the Asset Preview sub-window requires a bigger hack, due to `DockingLayoutManager` essentially destroying and recreating the `DockingManager` control. This broke every `<i:Interaction.Behaviors>` inside `DockingManager`, which I've …
> GameStudio to suspend game sub-windows when they are hidden in tab control

- build/Xenko.build
- sources/native/Xenko.Native.targets
- sources/targets/Xenko.Core.Sign.targets
* Added XenkoBuildPrerequisitesInstaller build variable (true by default).
* Renamed XenkoSignTool to XenkoSign
This makes it easier to build the xenko nuget packages on a private TeamCity server when advanced installer isn't available.
> [Build] Added XenkoBuildPrerequisitesInstaller build variable 

- sources/core/Xenko.Core.Reflection/TypeDescriptorFactory.cs
- sources/editor/Xenko.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml
Fix multi-dimensional array crashing the editor.
Annotate 'Not supported' text to property window for unsupported object types.
Treat multi-dimensional array as an object type to prevent the editor from crashing.
Append 'Not supported' text to unsupported object types in the property window.
Note that I don't know how localization really works, so would like someone to help in this area.
Fixes #431 & #645
Don't want the editor to crash.
> [Editor] Prevent multi-dimensional array from crashing the editor

- sources/core/Xenko.Core.Mathematics/BoundingSphere.cs
- sources/engine/Xenko.Graphics/CommandList.cs
- sources/engine/Xenko/Rendering/ParameterCollection.cs
Minor fixes.
Use the correct variable for the for-loop bounds check. The two arrays already had the same sizes so it never caused any issues.
Removed `ParameterCollection.GetValuePointer` since the code leaves the `fixed` scope, the pointer can potentially point to an invalid location if the garbage collector moves the array.
The two methods that used it now implement the pointer code correctly.
Any external users that have been using it, 1. shouldn't, 2. have access to `DataValues` and can create a fixed pointer themselves.
> Minor code fixes, remove unsafe method

- sources/assets/Xenko.Core.Assets/Tracking/SourceHashesHelper.cs
- sources/assets/Xenko.Core.Assets/Yaml/AssetObjectSerializerBackend.cs
- sources/core/Xenko.Core.Reflection/MemberDescriptors/IMemberDescriptor.cs
- sources/core/Xenko.Core.Reflection/MemberDescriptors/MemberDescriptorBase.cs
- sources/core/Xenko.Core.Reflection/TypeDescriptors/CollectionDescriptor.cs
- sources/core/Xenko.Core.Reflection/TypeDescriptors/DictionaryDescriptor.cs
- sources/core/Xenko.Core.Reflection/TypeDescriptors/ObjectDescriptor.cs
- sources/core/Xenko.Core.Yaml.Tests/DescriptorTests.cs
- sources/core/Xenko.Core.Yaml.Tests/Serialization/SerializationSubClassTests.cs
- sources/core/Xenko.Core.Yaml/Serialization/DynamicMemberDescriptorBase.cs
- sources/core/Xenko.Core.Yaml/Serialization/ObjectContext.cs
- sources/core/Xenko.Core.Yaml/Serialization/Serializers/DefaultObjectSerializerBackend.cs
- sources/core/Xenko.Core/DataContractMetadataTypeAttribute.cs
- sources/engine/Xenko.UI/Attributes/DefaultThicknessValueAttribute.cs
- sources/engine/Xenko.UI/Controls/Button.cs
- sources/engine/Xenko.UI/Controls/ButtonBase.cs
- sources/engine/Xenko.UI/Controls/ImageButton.cs
- sources/engine/Xenko.UI/Controls/ModalElement.cs
- sources/engine/Xenko.UI/Controls/ScrollViewer.cs
- sources/engine/Xenko.UI/Controls/Slider.cs
- sources/engine/Xenko.UI/Controls/ToggleButton.cs
Fix YAML bug where derived controls change the default value, which doesn't get detected by the serializer.
Added a new attribute to allow for overriding default values via a `DataContractMetadataTypeAttribute`.
This is similar to .NET's [MetadataTypeAttribute](
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.metadatatypeattribute?view=netframework-4.8), however our rules differ slightly. eg. We allow all sub-classes to declare the metadata attribute.
The metadata property is matched on both field/property name AND the data type. This is because a user might hide a property with a new one in the sub class, but it has a different data type (unlikely scenario...?).
The other fix is to push the 'parent' property that generated the value and check the default …
> Fix YAML serialization when control subclasses override the default values

- sources/editor/Stride.Core.Assets.Editor/ViewModel/SessionViewModel.cs
- sources/editor/Stride.GameStudio/GameStudioWindow.xaml
Add new right-click Asset context menu to 'Show source file in Explorer'
If the file no longer exists, then try to browse to the folder it belonged to.
If the folder no longer exists, then show an error message.
Menu is always disabled for Assets that don't have `MainSource` set.
I want to browse to the actual file that the asset is pointing to because I want to do something with it.
> [Editor] Add ability to 'Show source file in Explorer' for an asset

- sources/core/Stride.Core/PropertyContainerClass.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/UIEditor/ViewModels/PanelViewModel.cs
- sources/editor/Stride.Assets.Presentation/Templates/SoundFromFileTemplateGenerator.cs
- sources/editor/Stride.Core.Assets.Editor/View/Controls/GridLogViewer.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModel/EditorViewModel.cs
- sources/editor/Stride.GameStudio/GameStudioWindow.xaml
- sources/editor/Stride.GameStudio/LayoutAnchorableActivateOnLogBehavior.cs
General bug fixes to the Game Studio editor.
1. Fix redundant settings file save when removing a project from the recently used projects list.
2. Fix bug when you drag&drop multiple audio files to the Asset view where `FFmpegMedia` cannot be reused.
3. Fix Asset Log grid where it doesn't display new messages unless you actively press some filter buttons.
4. Layout controls' behaviors break due to reloading the layouts. It must bind to the global instance `GameStudioViewModel.GameStudio` like the others have already done.
5. Don't crash when `Change layout type` is selected, and reinstate the dependency properties (eg. `Grid.Row`, `Grid.Column`
(4.) fixes #281 so it'll show the Build Log tab when an error occurs.
(5.) fixes #169 so `Change layout type` doesn't crash the editor.
> Multiple Editor fixes

- sources/core/Stride.Core.Reflection/TypeDescriptorFactory.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/DescriptorCategory.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/NotSupportedObjectDescriptor.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/ObjectDescriptor.cs
- sources/editor/Stride.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml
- sources/editor/Stride.Core.Assets.Editor/ViewModel/CopyPasteProcessors/AssetPropertyPasteProcessor.cs
- sources/presentation/Stride.Core.Presentation/ValueConverters/NotSupportedTypeToTypeName.cs
Fixes bug introduced by #646
Can't just append the '(Not supported)' message to all objects.
A specific `ObjectDescriptor` type is needed to mark these types.
Fixes #650 
Unfortunately, this means only multi-array types can be marked.
The problem is that some properties accept null as a valid object type (this outputs 'None'). There are also properties that accept an actual object, eg. the 'Sort Mode' on the render stage.
A minor issue is that things like `DateTime` will not say '(Not supported)', however it does already just say DateTime and isn't editable.
> [Editor] Fix property value showing '(Not supported)' for null values

- THIRD PARTY.md
- sources/editor/Stride.Core.Assets.Editor/Stride.Core.Assets.Editor.csproj
- sources/editor/Stride.Core.Assets.Editor/View/AssetViewUserControl.xaml.cs
- sources/editor/Stride.GameStudio/ActivateParentPaneOnGotFocusBehavior.cs
- sources/editor/Stride.GameStudio/AssetEditorsManager.cs
- sources/editor/Stride.GameStudio/AvalonDockHelper.cs
- sources/editor/Stride.GameStudio/DockingLayoutManager.cs
- sources/editor/Stride.GameStudio/GameStudioWindow.xaml
- sources/editor/Stride.GameStudio/GameStudioWindow.xaml.cs
- sources/editor/Stride.GameStudio/LayoutAnchorableActivateOnLocationChangedBehavior.cs
- sources/editor/Stride.GameStudio/LayoutAnchorableActivateOnLogBehavior.cs
- sources/editor/Stride.GameStudio/Theme.AvalonDock.xaml
- sources/editor/Stride.GameStudio/View/CustomDocumentPaneTabPanel.cs
Change to open source MS-PL AvalonDock fork.
Removed Xceed library which doesn't seem to be used anymore (DataGrid removed prior, and AvalonDock changed in this pull).
Note that the `THIRD PARTY.md` still references `WPFToolKit` which is the old (expired?) link to the Xceed, which is not removed because we have a few xaml pages that were copied over from them (this was done before their license change so remains under the MS-PL license). Not a lawyer so leaving it unless advised otherwise.
Fixes #661
Fixes #659
The forked version fixes the docking layout resize bug, which we don't know when Xceed will release for the open source public.
Xceed license was changed, so using proper open-source is probably more welcome (in my opinion...)
> Change to open source AvalonDock & remove Xceed library

- sources/editor/Stride.GameStudio/AssetEditorsManager.cs
Remove visibility logic check when closing event is raised so the asset window can actually close, otherwise it's hidden in limbo and the asset can't be reopened.
I have also removed the check in the CurveEditor code, but didn't test that which I'm not sure if it exists anymore.
This bug is occurring to due to adding the new forked AvalonDock.
Not sure if this logic check was originally meant as some workaround for some bug in the original AvalonDock, eg. it raised close event when it shouldn't have, or if there's some condition where this is raised and we don't want it to close?
> [Editor] Fix closing then reopening asset when undocked

- sources/assets/Stride.Core.Assets/AssetImporterParameters.cs
- sources/editor/Stride.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml
- sources/editor/Stride.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml.cs
- sources/editor/Stride.Assets.Presentation/Templates/ModelFromFileTemplateGenerator.cs
- sources/editor/Stride.Assets.Presentation/ViewModel/ModelViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModel/ImportedAssetViewModel.cs
- sources/engine/Stride.Assets.Models/AssimpAssetImporter.cs
- sources/engine/Stride.Assets.Models/ImportAssimpCommand.cs
- sources/engine/Stride.Assets.Models/ImportModelCommand.Model.cs
- sources/engine/Stride.Assets.Models/ModelAsset.cs
- sources/engine/Stride.Assets.Models/ModelAssetCompiler.cs
- sources/engine/Stride.Assets.Models/ModelAssetImporter.cs
- sources/tools/Stride.Importer.Assimp/Stride.Importer.Assimp.cpp
Not sure if anyone else wants this feature, but I was caught out with Assimp's importer deduping my materials on my model when I didn't want it to.
I've now added a checkbox so you can choose not to dedupe materials. It's ticked by default so it behaves the same as currently. However, note that FBX and Assimp importers actually behave inconsistently in this regard, since FBX importer does _not_ dedupe materials at all.
Here's a screenshot of what the option looks like:
Note that I've only added it for the Assimp importer since it's a flag option for the importer.
I did not do it for FBX importer, I couldn't find any option for the FBX SDK (or I didn't look hard enough), and I don't want to troll though the code to figure out what the correct logic is to manually deduped it.
Note that the …
> [Editor] Add ability to make material deduping from Assimp importer optional

- docs/CONTRIBUTING.md
Welp, didn't mean to open a new branch on the official, github's online editor is kind of weird to use, anyway:
Update contribution to the changes we made since then, fix spelling and change the wording in certain places to be stay succinct.
AFAIK `.editorconfig` is ready by now, tell me if it isn't.
Changes speaks for themselves.
> [Docs] Update contributing

- sources/editor/Stride.Assets.Presentation/Templates/SoundFromFileTemplateGenerator.cs
Imported audio assets won't append ' track ' + index to the name if there's only track.
Majority of audio that I import are wav, mp3, etc, that don't have multiple tracks, so this naming appending feature is not needed for those cases.
> [Editor] Don't append track name to Audio asset name if there's only one track

- sources/core/Stride.Core/Diagnostics/ExceptionInfo.cs
- sources/editor/Stride.Core.Assets.Editor/Themes/generic.xaml
- sources/presentation/Stride.Core.Presentation/Controls/TextLogViewer.cs
- sources/presentation/Stride.Core.Presentation/Themes/ThemeSelector.xaml
Hopefully this should make the logger less obtuse for users.
Adds a ``(...)`` at the end of exceptions to hint to users that they can use a similar button to show the rest. 
Changes ``ExceptionInfo``'s formatting to reflect how dot net does it by default, i.e.: 
``Type: Message\n{innerExceptions.ToString}\n{Stacktrace}``
instead of ours which was
``Message\n{Stacktrace}\n{innerException.ToString}``
this leads to the first stacktrace line being the line that actually created the exception instead of one of the many catch the exception climbed back through.
See PR Details.
> [Logger] Enhance logger and ExceptionInfo formatting

- sources/editor/Stride.Core.Assets.Editor/Themes/generic.xaml
- sources/presentation/Stride.Core.Presentation/Themes/ThemeSelector.xaml
Add tooltips on the buttons in the Asset errors & Build output grids.
Remove the mystery behind the buttons.
> [Editor] Add tooltips to the buttons in the Asset errors & Build output grids

- sources/assets/Stride.Core.Assets/Yaml/CollectionWithIdsSerializerBase.cs
- sources/assets/Stride.Core.Assets/Yaml/ErrorRecoverySerializer.cs
- sources/core/Stride.Core.Yaml/Serialization/DefaultObjectFactory.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializer.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializers/ArraySerializer.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializers/DefaultObjectSerializerBackend.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializers/DictionarySerializer.cs
- sources/core/Stride.Core.Yaml/YamlException.cs
- sources/core/Stride.Core/Serialization/ClassDataSerializer.cs
- sources/editor/Stride.Assets.Presentation/AssemblyReloading/GameStudioAssemblyReloader.cs
Logs silent fails user component throwing exceptions through their ctor and properties created.
In general most logs are more concise, the rest of the information has been pushed into inner exceptions for the user to unfold through the ``...`` button, keeping the base view readable.
Fixes #209 
Some changes might not make sense without #687 
Kill an old bug.
> [Serialization] Handle component and property access-related exception gracefully

- sources/editor/Stride.Assets.Presentation/AssetEditors/ProjectWatcher.cs
Code editor and other asset editors would fail to open. It was caused by a *not-null* check which should have been a *null* check.
Fixes #711
> [Editor] Fix project file not tracked

- sources/engine/Stride.Graphics/VertexHelper.cs
- sources/engine/Stride.Rendering/Rendering/ProceduralModels/PrimitiveProceduralModelBase.cs
Made the property to adjust the number of generated texture coordinates visible to the user.
The vertex buffers generated by the procedural models are quite huge since they contain 10 channels of texture coordinates. This property allows the user to reduce them if needed.
> [Rendering] Added NumOfTexCoords property to Procedural Models

- sources/engine/Stride.Physics/Engine/HeightmapUtils.cs
Fix array index out of bounds at resizing pixel data.
HeightmapAsset that enabled Resize fails to compile.
1. Add HeightmapAsset from a source file(i.e. 256x256).
2. Enable and set Resize to 1024x1024
The asset compilation fails.
> [Physics] Fix HeightmapAsset compilation fails with resizing

- sources/engine/Stride.Graphics/VertexDeclaration.cs
Assimp C++ project fail to compile because of ambiguous method overload resolution.
> C:\Projects\stride\sources\tools\Stride.Importer.Assimp\Stride.Importer.Assimp.cpp(475,1): error C2668: 'Stride::Graphics::VertexDeclaration::VertexDeclaration': ambiguous call to overloaded function
Failing C++:
https://github.com/stride3d/stride/blob/f2730dd2c66ddfec3171ca0a8180ad0fdb2dfe96/sources/tools/Stride.Importer.Assimp/Stride.Importer.Assimp.cpp#L475
Related C# code:
https://github.com/stride3d/stride/blob/f2730dd2c66ddfec3171ca0a8180ad0fdb2dfe96/sources/engine/Stride.Graphics/VertexDeclaration.cs#L32-L33
https://github.com/stride3d/stride/blob/f2730dd2c66ddfec3171ca0a8180ad0fdb2dfe96/sources/engine/Stride.Graphics/VertexDeclaration.cs#L44
N/A
Fix compilation by making the overloads unambiguous …
> Fix C++ compilation with Visual Studio 16.6

- sources/engine/Stride.Games/SDL/GameWindowSDL.cs
Fixed SDL window resize initiated by GraphicsDeviceManager after back buffer resize
Fixes a regression introduced by #737 
The case of an automatic window resize after a back buffer resize wasn't handled.
#737
Get my PR in order :)
> [Games] Fixed SDL window resize initiated by GraphicsDeviceManager

- sources/editor/Stride.GameStudio/GameStudioWindow.xaml.cs
A taskbar set to auto-hide cannot be interacted with while the gamestudio window is maximized, this PR fixes that.
See changes.
None
Fix bug
> [Editor] Fix autohide taskbar

- sources/core/Stride.Core.Mathematics/Color.cs
Corrected the param documentations for Color[index].
Params for color indexes were incorrect as described in [Issue #693](https://github.com/stride3d/stride/issues/693) and so were corrected to:
- 0: Red
- 1: Green
- 2: Blue
- 3: Alpha
https://github.com/stride3d/stride/issues/693
Change is good for readability and to avoid confusion.
- [ x ] Docs change / refactoring / dependency upgrade
> Correction Color[index]

- sources/engine/Stride.Input/Windows/GameControllerDirectInput.cs
Calling joystick.Acquire() concurrently with a direct input device connected will hang threads indefinitely.
It should fix #710, it did fix it on my end but I would still like @jeske to confirm that it works on his end too to be sure.
Fix a bug.
> [Input] Fix DirectInput Acquire()

- sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
- sources/assets/Stride.Core.Assets.Quantum/AssetToBaseNodeLinker.cs
- sources/assets/Stride.Core.Assets/Reflection/CollectionItemIdentifiers.cs
- sources/core/Stride.Core.Design/AbsoluteId.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/CollectionDescriptor.cs
- sources/core/Stride.Core.Serialization/Assets/AssetId.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/AssetCompositeGameEditor/ViewModels/AssetCompositeHierarchyEditorViewModel.cs
- sources/editor/Stride.Editor/Engine/EntityExtensions.cs
- sources/presentation/Stride.Core.Quantum/GraphNodeLinker.cs
- sources/presentation/Stride.Core.Quantum/GraphVisitorBase.cs
- sources/presentation/Stride.Core.Quantum/References/ReferenceEnumerable.cs
Reduce the time taken to add and load prefabs and scenes in the gamestudio.
Most of the changes made only target the hot path, as I have mentioned on #743 I think that a significant re-write is required before performances are at an acceptable level, this will have to do in the mean time.
The cost associated with allocating are far greater than attempting a couple of casts before hand as those methods are extremely frequently used, so:
- Explicitly tested IReadonlyCollection against common collection implementation to retrieve the alloc-less enum for cases where it made sense.
- Simplified or replaced a couple of linq operations by handwritten loops.
- ``FindSubEntity`` now uses the ``EntityManager.GetEnumerator()`` when it can instead of going through the hierarchy.
- Added another …
> [GameStudio] Prefabs and scene loading optimization

- sources/engine/Stride.Input.Tests/TestInput.cs
- sources/engine/Stride.Input/VirtualButton/VirtualButton.cs
* Change type checking in `VirtualButton.RegisterFromType` from equals to `IsAssignableFrom`.
* Add `TestVirtualButtonFind` to `TestInput` to whether buttons from Keyboard, Mouse and GamePad are found.
#750 
Makes `VirtualButton.Find` able to find keys from devices other than the keyboard.
- New Tests and all `Stride.Input` tests passed
> [Input] Fix Issue #750, VirtualButton.RegisterFromType

- sources/assets/Stride.Core.Assets.CompilerApp/PackageBuilder.cs
- sources/assets/Stride.Core.Assets/PackageSession.Dependencies.cs
Fix some CompilerApp issues so it can build/load the game projects.
`builderOptions.ExtraCompileProperties` is nullable so needs to guarded before calling `TryGetValue`.
Sometimes nuget generates paths with "\_.\_", eg. my `[GAME].Windows\obj\project.assets.json` contains
```
{
"version": 3,
"targets": {
".NETFramework,Version=v4.7.2": {
// ...omitted
"Stride.SpriteStudio.Offline/4.0.0.1-beta03": {
"type": "package",
"dependencies": {
"Stride.Assets": "4.0.0.1-beta03",
"Stride.SpriteStudio.Runtime": "4.0.0.1-beta03"
},
"compile": {
"lib/net472/_._": {}
},
"runtime": {
"lib/net472/_._": {}
}
},
// ...other stuff
```
According to [this thread](https://github.com/dotnet/aspnetcore/issues/744), nuget sometimes emits empty directories.
I have changed it so these paths are ignored, so it's not …
> Fix CompilerApp to not load invalid assemblies

- sources/core/Stride.Core.AssemblyProcessor/Utilities.cs
- sources/editor/Stride.Assets.Presentation/Templates/NewGameTemplateGenerator.cs
- sources/engine/Stride.Assets/Templates/ProjectTemplateGeneratorHelper.cs
- sources/tools/Stride.ProjectGenerator/Program.cs
Namespace changes within the namespace validation window weren't being carried over to generated project source files, this PR fixes that.
See above.
#547 
Fix a bug.
This PR supersedes #753 , see my comment over there for more info.
Do note that the generated ``*App.cs`` class name is based on the project name and gets auto-corrected through ``BuildValidClassName()``, it is not based on the namespace, they won't match if users change the namespace, it works fine but I'm not sure that that's expected behavior for you @xen2, I'll leave that to you.
> Template validation

- sources/core/Stride.Core.Mathematics/Half2.cs
- sources/core/Stride.Core.Mathematics/Half3.cs
- sources/core/Stride.Core.Mathematics/Half4.cs
- sources/engine/Stride.Graphics/Effects/Effect.cs
- sources/engine/Stride.Shaders.Compiler/EffectCompiler.cs
- sources/engine/Stride.Shaders.Parser/ShaderLinker.cs
- sources/engine/Stride.Shaders.Parser/ShaderMixinParser.cs
- sources/engine/Stride.Shaders.Tests/TestShaderReflection.cs
- sources/engine/Stride.Shaders/EffectValueDescription.cs
- sources/engine/Stride/Effects/ParameterKeyValueMetadata.cs
- sources/shaders/Stride.Core.Shaders/Ast/VectorType.cs
- sources/shaders/Stride.Core.Shaders/Writer/ShaderWriter.cs
The PR adds the default values as defined in a shader to the shader reflection. This allows to read them during runtime after they have been modified or new ones have been added.
I took the liberty and used the `EffectValueDescription.DefaultValue` property for it, as it wasn't used anywhere before.
I've also added tests to the PR which exposed a few other issues like invalid HLSL being generated when declaring a variable like `vector<float, 2> foo;`, constructors of `Half` vectors not being present or `ShaderClassString` not working.
None that I know of.
The default values of shader variables are being read at compile time by the shader key generator and stored in static C# fields. This works fine as long as one doesn't change those values during runtime or add new variables to a shader. …
> Include default values in shader reflection

- sources/engine/Stride.Navigation/DynamicNavigationMeshSystem.cs
- sources/engine/Stride.Physics/Bullet2PhysicsSystem.cs
Bullet2PhysicsSystem and DynamicNavigationMeshSystem to use services to retrieve GameSettings and game systems to remove dependency on Game object.
Ideally Game object should have a 'headless server' mode, but this is a lot of effort.
In the mean time, this change makes it easier to make a "game" class that doesn't inherit the Game class.
eg. consider the following HeadlessGame, but we want to load the physics settings from the asset, or include DynamicNavigationMeshSystem.
https://github.com/xen2/Xenko.ClientServerSample/blob/master/Xenko.ClientServerSample.Server/HeadlessGame.cs
Note I haven't really tested if DynamicNavigationMeshSystem could work in a headless mode, so could be excluded from this commit if it's a bit iffy to change.
> Game Systems to use Services instead of Game object

- sources/engine/Stride.Rendering/Rendering/LogicalGroup.cs
- sources/engine/Stride.Shaders.Compiler/EffectCompiler.cs
- sources/engine/Stride.Shaders.Tests/TestShaderReflection.cs
Reverts change from previous commit that reflection wasn't cleaned up in debug.
#765 
The shader reflection should be the same in debug and release builds. My change in the last PR was a little too quick. It would've required user code to filter the reflection on its own.
It would still be nice to tell the compiler not to remove parameters, but that's for another day.
> Little cleanup to previous PR regarding shader reflection

- sources/assets/Stride.Core.Assets/AssetFolderCollection.cs
- sources/core/Stride.Core/Collections/ConstrainedList.cs
- sources/core/Stride.Core/Collections/SortedList.cs
- sources/engine/Stride.Games/IGameSystemCollection.cs
- sources/engine/Stride.Rendering/Rendering/GraphicsRendererCollectionBase.cs
Added `IReadOnlyList<T>` base interface to the core collections, where it was missing.
Unfortunately, `IList<T>` doesn't inherit from `IReadOnlyList<T>`, so one has to add it manually. Most Stride collections had it already, but a few were missing.
This makes the collection compatible with generic operations that expect an `IReadOnlyList<T>`.
> [Core] Added IReadOnlyList<T> base interface to core collections

- sources/engine/Stride.Shaders.Parser/ShaderLinker.cs
- sources/engine/Stride.Shaders.Tests/TestShaderReflection.cs
Follow up to my previous PR - I missed to check whether the default values also work when using a type alias like "float4".
#765
> [Shaders] Default value not working when using type alias

- sources/engine/Stride.Engine/Engine/Entity.cs
Users want a succinct way to remove entities from the game regardless of their place in the hierarchy, right now they have to set both parent and scene to null when they aren't sure that either of these is set.
Doing this operation should not require more than a single line, it might come more instinctively and will be easier to keep in mind.
In this PR when the value passed to ``Scene`` is null the engine detaches the entity from its parent if it has any or removes it from the scene.
I decided against making a specific function for it to keep it more in line with how we do other operations with transforms and entities and also to avoid having the same issues that unity has with the 'magic' Destroy() function.
> [Engine] Scene = null also detaches parent

- sources/engine/Stride.UI/Rendering/UI/UIRenderFeature.cs
This change prevents UI elements from being rendered underneath Sprites.
Previous value is `128` - the default, same as `SpriteRenderFeature`, which meant that during sorting the UI could potentially end up rendered before the sprites (or not).
The value `192` was chosen to match the `SortKey` of `BackgroundRenderFeature`.
I was playing around with JumpyJet and noticed that for some combinations of entity order in the scene the UI was not rendered on top of everything else as it should be.
After I applied the change I played a bit with the order of entities as previously but now UI was always on top.
_I'm not sure about changes to the documentation or in-code comments for this change._
> Increase UIRenderFeature SortKey to always render UI on top of Sprites

- sources/assets/Stride.Core.Assets/Package.cs
As the title says, having a file without an extension (like a github license file for example) prevents the whole project from being loaded in the game studio.
The first change might not be required, not sure, you'll probably know better than I do @xen2 
None
Bug
> [Build] Fix project files without extensions preventing loading

- sources/engine/Stride.Physics/Engine/PhysicsProcessor.cs
Fixes #798 by not removing a component that has been re-added in the same frame.
When an entity is removed from a scene it is removed from all the component processors. For physics, this removal is delayed till the next frame. So if the same entity is added back in the same frame, it's physics component should not be removed.
Note: This causes the associated data in the `ComponentDatas` to be a different object than in `component.Data`, however, they still have the same _value_ because they pass the `IsAssociatedDataValid` check.
#798 
Allows removing and adding entities, with a physics component, from the scene without the need to clone them.
> [Physics] Prevent invalid state when component was added right after removal

- sources/engine/Stride.Engine.Tests/TestCameraProcessor.cs
- sources/engine/Stride.Engine/Engine/Processors/CameraProcessor.cs
- sources/engine/Stride.Engine/Engine/SceneSystem.cs
- sources/engine/Stride.Engine/Rendering/Compositing/GraphicsCompositor.cs
By removing the dependency on the scene system and fetching the camera collection from the used graphics compositor directly, one can render a scene from within a different context than a scene system.
We're dealing with multiple scenes in one game rendered at the same time. The scenes to be rendered can vary from frame to frame. We therefor don't make use of a scene system but use a custom game system scheduling those scene rendering. This PR ensures that a scene using camera slots still works as expected.
> Remove dependency of camera processor on scene system

- sources/engine/Stride.Engine/Engine/SceneSystem.cs
The graphics compositor needs to be set in the `RenderContext` before calling `Draw` on the entity processors.
#825
> [Engine] Fixed regression that the camera processor wouldn't find the camera slot anymore

- sources/engine/Stride.Graphics/Direct3D/GraphicsResourceBase.Direct3D.cs
- sources/engine/Stride.Graphics/Direct3D12/GraphicsResourceBase.Direct3D12.cs
- sources/engine/Stride.Graphics/GraphicsResourceBase.cs
- sources/engine/Stride.Graphics/Null/GraphicsResourceBase.Null.cs
- sources/engine/Stride.Graphics/OpenGL/GraphicsResourceBase.OpenGL.cs
- sources/engine/Stride.Graphics/Vulkan/GraphicsResourceBase.Vulkan.cs
This allows clients to get notified when the internal resource gets destroyed.
We're using `WGL_NV_interop` to register handles for a texture. These handles need to be unregistered in case the internal texture gets destroyed.
> [Graphics] New event GraphicsResourceBase.Destroyed

- sources/core/Stride.Core/Annotations/MemberRequiredAttribute.cs
- sources/engine/Stride.Assets.Tests/Stride.Assets.Tests.csproj
- sources/engine/Stride.Assets.Tests/TestMemberRequiredComponentChecks.cs
- sources/engine/Stride.Assets/Entities/ComponentChecks/IEntityComponentCheck.cs
- sources/engine/Stride.Assets/Entities/ComponentChecks/ModelComponentCheck.cs
- sources/engine/Stride.Assets/Entities/ComponentChecks/ModelNodeLinkComponentCheck.cs
- sources/engine/Stride.Assets/Entities/ComponentChecks/RequiredMembersCheck.cs
- sources/engine/Stride.Assets/Entities/EntityHierarchyCompilerBase.cs
This PR introduces a `[MemberRequired]` attribute that can be placed on fields and properties of components. If during the asset compilation a field/property with that attribute is `null`, a warning/error is issued.
Additionally, component checks in the `EntityHierarchyCompilerBase` have been abstracted into an interface `IEntityComponentCheck` to allow better maintenance and future expansion of such checks.
Resolves #778 
It's often very easy to forget to set a value for a component in Game Studio and you would only find that out with an exception. With this change, you can mark properties as required and get a warning during compilation which is more visible.
The docs would need to be updated to include information about a possibility of marking properties with the added attribute.
All …
> Allow components to have required members and report warning/error if they're null

- sources/engine/Stride.Games/GameSystemBase.cs
- sources/engine/Stride.Rendering/Rendering/EffectSystem.cs
removed grahpicsDeviceSerive from EffectSystem (which overwrites the one of baseClass)
i also made gamesystemBase.InitGraphicdevice protected (from private) to so effectSystem
can init it.
i did it that way becaue didnt want to put the init in the baseclass since i dont know the impact.
but it would be better to do there.
this crashed with isNullException:GraphicsDevice (in an code only environment)
Effect eff = Game.EffectSystem.LoadEffect("PositionVColorShader").WaitForResult();
> Bugfix EffectSystem not using baseClass when accessing graphicsDevice

- sources/engine/Stride.Rendering/Rendering/Images/ImageEffectShader.cs
Fixed null pointer in ImageEffectShader in case no input texture is set on a slot.
> [Rendering] Fixed null pointer in ImageEffectShader in case no input texture is set on a slot

- sources/engine/Stride.Rendering/Rendering/Material.cs
- sources/engine/Stride.Rendering/Rendering/Materials/MaterialGeneratorContext.cs
When creating materials at runtime it's important that the graphics device gets passed down to the `ShaderGeneratorContext` or otherwise the sampler states do not work.
> [Rendering] Pass the graphics device down to the shader generator context

- sources/engine/Stride.Games/GameBase.cs
- sources/engine/Stride.Games/GameTime.cs
I mentioned on the previous PR regarding this topic (#785) that I would look at merging UpdateTime and DrawTime together into a single 'Time' class, it's actually not a good idea to do so for a whole lot of reasons.
So instead of that I'll just fix DrawTime to UpdateTime's factor, see #785 for why that's important. Also, factor should only affect elapsed time after the frame/update is processed otherwise you might have 'one half of the frame' in real time and the other in slow mo when that variable is modified in the middle of its execution.
See above
None
See PR details
> [Engine] Small fix for time warp

- sources/engine/Stride.Assets/Effect/EffectCompileCommand.cs
- sources/engine/Stride.Engine/Shaders.Compiler/EffectCompilerFactory.cs
- sources/engine/Stride.Engine/Shaders.Compiler/RemoteEffectCompiler.cs
- sources/engine/Stride.Rendering/Rendering/EffectSystem.cs
- sources/engine/Stride.Shaders.Tests/TestMixinCompiler.cs
- sources/engine/Stride.Shaders/Compiler/EffectCompilerCache.cs
- sources/engine/Stride.Shaders/Compiler/NullEffectCompiler.cs
The effect compiler uses the virtual file provider to lookup shader source code and the database to cache compiled shaders. Allowing to pass both services explicitly (and not assuming they're implemented by the same instance) one can highly customize the shader source code lookup without affecting the caching mechanism.
We need to be able to load shaders at runtime. These changes allow us to use a custom file provider for shader source code lookup.
> Explicitly pass database to effect compiler

- sources/engine/Stride.Engine/Engine/InstancingUserBuffer.cs
- sources/engine/Stride.Rendering/Rendering/InstancingRenderFeature.cs
- sources/engine/Stride.Rendering/Rendering/RenderInstancing.cs
This constraint was restricting the user buffer setup
(cherry picked from commit 78e74a7fa5576f2f6efe178b31ee5a27ef14e083)
Minor fix to allow more buffer types.
PR #340 
Providing matrix buffers with compute shaders.
> [Rendering] Instancing: Changed Buffer<Matrix> to Buffer

- sources/engine/Stride.Engine/Profiling/GameProfilingSystem.cs
Small change to avoid throttling while the game is being profiled, similar to what we do with vsync in such cases.
See above and title.
None
See PR Details.
> [Profiling] Disable unfocused throttling when profiling

- sources/editor/Stride.Editor/EditorGame/Game/EditorServiceGame.cs
My changes in 5946194cf738 caused the preview game to crash on startup. I guess it worked before because the effect compiler created in `Game.Initialize` was replaced with another one after initialization, see `PreviewGame.Initialize` and `EntityHierarchyEditorGame.Initialize`.
> [Editor] Fixed null pointer on startup introduced by 5946194cf738

- sources/engine/Stride.Shaders.Parser/Mixins/ModuleMixinInfo.cs
- sources/engine/Stride.Shaders.Parser/Mixins/ShaderCompilationContext.cs
- sources/engine/Stride.Shaders.Parser/Mixins/StrideShaderLibrary.cs
This PR addresses two issues we ran into when loading a broken shader:
1) It was impossible to reload it due to some internal dependency not being tracked and therefor a cache not being invalidated by ResetCache calls. I added a `ReferencedShaders` property to keep track of them independent of the `MinimalContext` logic - using that one caused a weired behavior in my previous PR.
2) The compiler result was not deterministic when invoked a second time - a mixin was marked with error flag but the result log had no error which lead to subsequent code paths crashing as they only checked the result log.
https://github.com/vvvv/VL.Stride/issues/221
> Couple of fixes to shader compiler

- sources/engine/Stride.Rendering/Rendering/InstancingRenderFeature.cs
If instancing count <= 0
Memory leak bug fix.
The effect validation doesn't run if instancing count is <= 0. This fixes the bug, but I am not sure whether this is the correct way of doing it.
Questions:
* Does this work if an effect has instancing and then the instancing component is removed?
* Is there a way to not even create the `InstancingData` and also don't run the `InstancingRenderFeature` for a mesh, if no `InstancingComponent` is attached? Here is also the question of whether it works if an effect has instancing and in the next frame not anymore.
#851 
Reported memory leak
> [Rendering] Instancing: Skip effect validation

- sources/launcher/Stride.Launcher/ViewModels/DocumentationPageViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/LauncherViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/NewsPageViewModel.cs
- sources/launcher/Stride.Launcher/Views/Commands.cs
- sources/presentation/Stride.Core.Presentation/Commands/UtilityCommands.cs
When the launcher switched to .net core the links in the launcher stopped working. This is because UseShellExecute is false by default on .net core. This PR fixes the links by setting UseShellExecute to true for all the Process.Start calls that open an URL.
#809 
Bug fix for a problem that is causing confusion for new users
> Fixed browser not opening when clicking a link in the launcher. Fixes #809

- sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.csproj
Adds missing dependency on `System.Reactive` - this is an indirect dependency, introduced by RoslynPad. On .NET Framework it was pulled from the GAC, but in .NET Core it was missing. This resulted in a silent exception being swallowed because it occurred on a background thread. The exception message complained about version 4.3.0 (but there's only 4.3.1) so I also upgraded the `System.Reactive.Linq`
Fixes #786
> [Editor] Fix syntax highliting in .NET Core, by adding missing dependency

- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
- sources/engine/Stride.Physics/Module.cs
Moves native library preloading to module initializer.
**Question:** Should I also remove the preload call from `Bullet2PhysicsSystem`?
Fixes #368
> [Physics] Move libbulletc.dll preloading to module initializer

- sources/engine/Stride.Physics.Tests/GameAssets/SendCollisionEndedWhenEntityIsRemovedTest.sdscene
- sources/engine/Stride.Physics.Tests/SendCollisionEndedWhenEntityIsRemovedTest.cs
- sources/engine/Stride.Physics.Tests/Stride.Physics.Tests.Windows.csproj
- sources/engine/Stride.Physics.Tests/Stride.Physics.Tests.Windows.sdpkg
- sources/engine/Stride.Physics/Collision.cs
- sources/engine/Stride.Physics/Simulation.cs
Send a message to channels waiting on `physicsComponent.CollisionEnded()` when the collision is removed due to the removal of a physics component. The collision object received by the user will have been _destroyed_, so both `collision.ColliderA` and `collision.ColliderB` will be `null`.
> Note: every collision received from `CollisionEnded` or `NewCollision` is destroyed before the next frame. Here I'm introducing sending of the events in between the last frame scripts and the destroying before the next frame.
Fixes #788 
Removing an entity/physics component should be valid means of ending a collision (rather than sending into some far away location for a frame). Rather than checking the collisions collection on the physics component we should encourage users to rely on the …
> [Physics] Send CollisionEnded on entity/component removal

- sources/assets/Stride.Core.Assets/Stride.Core.Assets.csproj
Stride.Core.Assets has no code, nor package dependencies that use WPF or Winforms.
Having those flags set includes a dependency on `Microsoft.WindowsDesktop.App` framework sdk which is not available on non-Windows platforms.
This PR removes this unused dependency to allow future support of non-Windows platforms accessing `Stride.Core.Assets` package.
N/A
I'm beginning to try to compile my mini Stride.Editor on Linux and got the error
```
The FrameworkReference 'Microsoft.WindowsDesktop.App' was not recognized
```
There's no reason to have the assembly depend on it if no code does.
My testing (I actually tried running the whole test suite this time to find potential hidden cross project issues):
* GameStudio runs fine
* My game (derived from ThirdPerson platformer) runs fine
* …
> [Build] Remove unused dependency on Microsoft.WindowsDesktop.App from Stride.Core.Assets

- sources/engine/Stride/Graphics/Image.cs
- sources/engine/Stride/Graphics/PixelBuffer.cs
will now also convert the format of the pixel buffers.
(cherry picked from commit 659f6eef93e715558ed784eb7870468f32e0b557)
Fixes format to SRgb conversion on image load.
Copying of pixel buffers failed because the formats did not match.
Loading many images as texture array.
> [Graphics] Fixed loading an image as SRgb

- sources/assets/Stride.Core.Assets/Package.cs
- sources/core/Stride.Core.Design/Settings/AppSettingsProvider.cs
- sources/core/Stride.Core.Design/Yaml/YamlSerializer.cs
- sources/core/Stride.Core/Diagnostics/GlobalLogger.cs
- sources/core/Stride.Core/Diagnostics/Logger.cs
- sources/core/Stride.Core/Diagnostics/LoggerConfig.cs
- sources/core/Stride.Core/Reflection/AssemblyRegistry.cs
- sources/core/Stride.Core/Settings/AppSettings.cs
- sources/core/Stride.Core/Settings/AppSettingsManager.cs
- sources/core/Stride.Core/Settings/IAppSettingsProvider.cs
This PR introduces a new way to define application level settings and uses it to allow user to override the minimum log level, which is currently hardcoded to Info.
* `Stride.Core.Settings.AppSettings` is the settings container - a collection of objects which should differ by type (otherwise the first object of the given type is returned).
* `Stride.Core.Settings.IAppSettingsProvider` is an interface that abstracts how we obtain the AppSettings. This is because we don't want to add any dependencies to `Stride.Core`.
* `Stride.Core.Settings.AppSettingsManager` is a static class that uses `AssemblyRegistry` to find a type which implements the above interface, loads the settings and caches them.
* `Stride.Core.Settings.AppSettingsProvider` (in `Stride.Core.Design`) provides a way to load …
> [Core] Customize minimum log level for GlobalLogger by introducing AppSettings

- sources/engine/Stride.Engine/Engine/InstanceComponent.cs
- sources/engine/Stride.Engine/Engine/Processors/InstanceProcessor.cs
- sources/engine/Stride.Engine/Engine/Processors/InstancingProcessor.cs
Small fix to keep state valid for an instance that was removed from the scene and added right back. (previously didn't end up rendering the instance after this operation)
None reported
Fix bug
@tebjan note the modifier changes from ``public``->``internal``, seemed more fitting, was there a specific reason to keep it public ? 
On that note, ``OnEntityComponentAdding`` calling ``FindMasterInParents`` seems to me like unexpected or unwanted behavior, should we keep it ?
> [Rendering] Instancing: fix instance back to scene

- sources/core/Stride.Core/build/Stride.Core.targets
- sources/engine/Stride.Games/Stride.Games.csproj
- sources/engine/Stride.Input/Stride.Input.csproj
This PR fixes two issues with the Stride NuGet packages that made it harder to compile game projects on Linux.
1. On linux there's no `TEMP` variable so the assembly processor was copied to the root directory (which is usually forbidden without root privilages).
2. The Stride.Games and Stride.Input packages were referencing `Microsoft.WindowsDesktop.App` framework which is not present on Linux - when compiling Stride for Linux any code that uses windows stuff is disabled anyways (via `#` directives), so it was just up to the reference.
Fixes #757 
It's much easier for me to test the Linux build if I can compile Stride packages on Windows, expose them as a NuGet source and compile the test project on Linux, rather than deploying the published Linux build from Windows.
Plus, it's now …
> Allow to compile projects on Linux

- sources/tools/Stride.PackageInstall/Program.cs
Moved vs prerequisite install before the other prerequisite installs.
The prerequisites installer somehow keeps the msiexec service in an installing state even though the installer is already finished and closed. This causes the visual studio installer to refuse to install because it thinks there is still an other installer running.
By installing the visual studio prerequisite before installing the other prequisites this problem is avoided. This is a hack because the windows installer state will still be wrong after this, but this will at least allow people to install stride properly without encountering an error that they can't easily solve. The windows installer being in a wrong state will most likely not cause any other problems for the user, because the next windows installer will …
> Fix to stop the visual studio installer exiting with code -1 during prerequisites install

- sources/engine/Stride.Graphics/SDL/Application.cs
- sources/engine/Stride.Graphics/SDL/Window.cs
Provides delegate subscription to listen for dropped files and present clipboard IO through SDL Application
See above.
None
Those things are useful
If @tebjan could take a quick look at this since you have worked around this namespace before, do we want the clipboard to sit within Application.cs ?
Note that I haven't implemented the ``SDL_DROPTEXT`` variant as it doesn't look like it's supported on windows.
> [SDL] Drop files and clipboard

- sources/engine/Stride.Rendering/Rendering/Lights/DirectLightGroup.sdsl
- sources/engine/Stride.Rendering/Rendering/Lights/LightPoint.sdsl
- sources/engine/Stride.Rendering/Rendering/Lights/LightSpot.sdsl
- sources/engine/Stride.Rendering/Rendering/Lights/LightStream.sdsl
- sources/engine/Stride.Rendering/Rendering/Materials/CelShading/MaterialSurfaceShadingDiffuseCelShading.sdsl
- sources/engine/Stride.Rendering/Rendering/Materials/Hair/MaterialSurfaceShadingDiffuseHair.sdsl
- sources/engine/Stride.Rendering/Rendering/Materials/Hair/MaterialSurfaceShadingSpecularHair.sdsl
- sources/engine/Stride.Rendering/Rendering/Materials/SubsurfaceScattering/MaterialSurfaceSubsurfaceScatteringShading.sdsl
Point and spotlight attenuation (i.e.: their range) is not readily accessible but instead baked into lightColor, this pr introduces ``lightAttenuation`` and clears the attenuation from the lightColor.
It is then used to enhance celshading to better reflect how that light model works in 2d animation.
Before:![image](https://user-images.githubusercontent.com/5742236/95007171-deaa2980-060c-11eb-86a9-8c4c886c48be.png)After:![image](https://user-images.githubusercontent.com/5742236/95007670-85dd8f80-0612-11eb-9bca-d62198a839f6.png)
None
See details.
> [Shader] Expose point+spot attenuation and fix celshading

- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/$ProjectName$.csproj.t4
- sources/editor/Stride.Assets.Presentation/Templates/NewGameTemplateGenerator.cs
- sources/editor/Stride.Assets.Presentation/Templates/TemplateSampleGenerator.cs
- sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/SessionTemplateGenerator.cs
- sources/engine/Stride.Assets/Templates/ProjectTemplateGeneratorHelper.cs
* Adds the windows RID to executable project template, so that when someone changes target framework to `netcoreapp3.1` they aren't immediately hit with freetype.dll missing exception.
* Setup Windows project to use .NET Core if created from .NET Core GameStudio
* Add global.json when using .NET Core GameStudio
#911
> Add default RID to Windows, TargetFramework and global.json project template

- samples/Games/SpaceEscape/SpaceEscape.Game/CharacterScript.cs
Because of #860 AsyncScript now has a correct update priority, but it's always running after the Start methods of StartupScripts. This lead to an incorrect order of execution of game logic, which I roughly mitigated here. In the future we may consider making an AsyncScript variant with a Start method that gets executed earlier.
N/A
Tried running the sample game, got an exception.
> Fix using uninitialized CharacterScript in SpaceEscape sample

- sources/editor/Stride.Assets.Presentation/NodePresenters/Updaters/GameSettingsAssetNodeUpdater.cs
- sources/editor/Stride.Assets.Presentation/TemplateProviders/GameSettingAddConfigurationTemplateProvider.cs
- sources/editor/Stride.Assets.Presentation/View/EntityPropertyTemplates.xaml
- sources/engine/Stride.Assets/GameSettingsAsset.cs
This PR modifies the presentation of `GameSettingsAsset.Defaults` in such way, that the Quantum nodes with default configurations are no longer spilled into the root node for the asset, but kept as a collection which allows to use the existing templates to display an add button that provides a way to add custom configurations.
Comparison between old and new look:
I tried to add a button without modifying the way it looks now, but it seems that might not be possible. In particular, after the items in `Defaults` are spilled into the root, any modifications to the collection won't properly update the view without opening a different asset in the property grid and forcing a full refresh.
Closes #844 
We need a quick way to add settings for non-default packages (e.g. Physics or Navigation). It …
> [Editor] Allow adding default configurations to GameSettings

- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
When choosing AssetCompiler version for projects that don't target .NET Framework or .NET Core, choose .NET Framework so that MSBuild tools are used.
Fixes #904 
Mobile projects don't target .NET Framework or .NET Core, but require MSBuild tools to be used rather than dotnet build tool.
> Fallback to net472 AssetCompiler first

- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
Assuming the window has a property called Handle which points to the HWND is not correct. This allows to use the Stride graphics API in other windowing frameworks like for example https://github.com/Ultz/Silk.NET
https://github.com/Ultz/Silk.NET/issues/347
> [Graphics] When creating the swap chain use the handle as provided by the WindowHandle

- sources/engine/Stride.Engine/Engine/Game.cs
- sources/engine/Stride.Engine/Engine/InputSystem.cs
- sources/engine/Stride.Input/Android/InputSourceAndroid.cs
- sources/engine/Stride.Input/InputManager.cs
- sources/engine/Stride.Input/InputSourceFactory.cs
- sources/engine/Stride.Input/SDL/InputSourceSDL.cs
- sources/engine/Stride.Input/SDL/MouseSDL.cs
- sources/engine/Stride.Input/UWP/InputSourceUWP.cs
- sources/engine/Stride.Input/Windows/InputSourceWindowsRawInput.cs
- sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
- sources/engine/Stride.Input/iOS/InputSourceiOS.cs
Allows to create additional input sources through a new static method called `InputSourceFactory.NewWindowInputSource` as well as decouples the input manager and the game by moving the game system specific logic into a new internal class called `InputSystem`.
In [VL.Stride](https://github.com/vvvv/VL.Stride) we support rendering to multiple windows. The changes in this PR are needed to create input sources for those additional game windows. Further the decoupling of the input manager could be useful in other scenarios where we don't even have a game.
> Support multiple window input sources

- sources/engine/Stride.Assets.Models/Stride.Assets.Models.csproj
Seems like something changed in msbuild with the net5 update that the dll isn't copied anymore. I guess in the past it came through the `Stride.Importer.Assimp.vcxproj` reference even though there it's marked as `CopyLocal = false`
Referencing the project directly ensures that the assembly gets copied to the build output folder of `Stride.Assets.Models` - it's needed by the `IncludeExtraAssemblies` target (`<BuildOutputInPackage Include="$(OutputPath)Stride.Assimp.dll" />`).
For reference, this is my build invocation:
`msbuild Stride.build /t:Package /m /v:m /restore /nr:false /p:StridePlatforms="Windows" /p:StrideGraphicsApiDependentBuildAll=false /p:StrideBuildPrerequisitesInstaller=false /p:StrideSign=false /p:StrideOfficialBuild=false`
> [Build] Fixes Stride.Assimp.dll not found during package build

- sources/core/Stride.Core.Mathematics/RectangleF.cs
The `RectangleF.Contains` method for `Vector2` is now exactly the same as for individual x and y values.
> [Mathematics] Fixes RectangleF.Contains method

- sources/engine/Stride.Engine/Profiling/GameProfilingSystem.cs
- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
- sources/engine/Stride.Graphics/GraphicsPresenter.cs
This PR is a little bit related to #923 - it removes the assumption that there's only one presenter. Instead it uses an internal property key to override the present interval on all presenters. We talked about it in our review last week.
Will currently only work in the Direct3D implementation. Vulkan would require to re-create the swap chain while in OpenGL the present interval is controlled through the window? It's not even implementing the Present operation. So I wonder whether it ever even worked on those implementations.
> [Engine] Use property key on graphics device to force present interval on all presenters while profiling

- sources/engine/Stride.Rendering/Rendering/Material.cs
- sources/engine/Stride.Rendering/Rendering/Materials/MaterialBlendLayer.cs
By querying the `Material.Descriptor` property first an in-memory generated material can be used in blend layers.
> [Rendering] Allows to use in-memory generated materials as blend layers

- sources/assets/Stride.Core.Assets.Quantum/Internal/AssetMemberNode.cs
No longer generate item ids for collections that are not supposed to have them. 
It improves performance but not generating item ids when they are not needed.
All directly related tests seems to pass. Quite a few tests fail, but this seems to be the case even without this change.
> AssetMemberNode.ContentChanged only generates missing ids if needed

- sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs
The cached depth stencil view of the `ForwardRenderer` needs to be disposed in case the render target changes. Otherwise the reference count of the render target never goes to zero and we end up with a resource/memory leak.
https://github.com/vvvv/VL.Stride/issues/366
> [Engine] Fixes memory leak in forward renderer

- sources/engine/Stride.Rendering/Rendering/Images/LightStreak/LightStreak.cs
- sources/engine/Stride/Rendering/ParameterCollection.cs
The effect parameters need to be reset when changing the `IsAnamorphic` property so a new parameter with the proper length can be allocated. Not doing so results in a crash when setting the parameter with the different length and in turn crashes the whole application due to constant temporary resource allocations.
https://github.com/vvvv/VL.Stride/issues/336
> [Rendering] Fixes crash when changing the LightStreak.IsAnamorphic property during runtime

- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/CSharpBeginner.Game.sdpkg
- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Windows/CSharpBeginner.Windows.sdpkg
This commit should fix the missing sub-scenes in the beginner tutorial, however I am not aware if there are any additional things required to ensure it gets packaged in the final build (I'm assuming the sub-scenes being in the correct sdpkg is the only thing required).
Moved the missing sub-scenes that were declared in the Windows sdpkg into the Game sdpkg.
Fixes #821
> [Samples] Fix missing sub-scenes in CSharpBeginner tutorial

- sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
Fix WinForms right shift key detection using the correct scan code.
Scan code used for right shift detection is actually a hex code, ie 0x36 == 54 as pointed out by CharlesWoodhill in #929
Fixes #754
Fixes #929
Also tested on the Touch Input project and saw it says RightShift for pressed & down when pressing right shift.
> [Input] Fix detecting WinForms right shift key (fixes #754, fixes #929)

- sources/engine/Stride.Physics/Engine/PhysicsProcessor.cs
Instead of placing the debug shapes in the root scene of the game allow to provide the parent scene through a property.
When rendering to multiple windows / multiple scenes at the same time one wants to choose where the debug shapes shall be placed.
> [Physics] Render physics debug shapes into any given scene

- sources/engine/Stride.Engine/Profiling/GameProfilingSystem.cs
Instead of simply rendering the profiling results into the current presenter, allow to set the render target through a property. If no render target is set the system will still fall back to the current presenter.
When rendering to multiple windows (or even off-screen) it's nice to have the option to choose where the profiling results should be displayed.
> [Games] Allows to set a custom render target for the GameProfilingSystem

- sources/engine/Stride.Engine/Engine/InputSystem.cs
Makes InputSystem public so users can access it.
The input's 'system' was changed due to pull #919
If you need to change the system settings on the InputSystem (eg. UpdateOrder, Enabled), you need public access to it.
> [Input] InputSystem should be public so external users can access it

- sources/engine/Stride.Games/GraphicsDeviceManager.cs
- sources/engine/Stride.Graphics/GraphicsPresenter.cs
Back buffer format adjustments based on the device color space will also be applied on resize. 
It will now also work for all pixel formats by using ToSrgb and ToNonSrgb extension methods.
Also fixes format adjustment not being applied if color space was set to Gamma but device supported Linear space.
> [Graphics] Back buffer format adjustments based on the device color space

- sources/engine/Stride.Games/GameWindow.cs
Allows to set the size of a game window in multi-window scenarios. Up to now the API only allowed setting the window size on creation and when switching out of fullscreen.
We need to be able to set the size of a window manually. For example if one wants to arrange multiple windows.
> [Games] Added SetSize to GameWindow to allow resizing the window by code

- sources/engine/Stride.Input/SDL/KeyboardSDL.cs
- sources/engine/Stride.Input/SDL/MouseSDL.cs
- sources/engine/Stride.Input/SDL/PointerSDL.cs
- sources/engine/Stride.Input/Simulated/KeyboardSimulated.cs
- sources/engine/Stride.Input/Simulated/MouseSimulated.cs
- sources/engine/Stride.Input/Simulated/PointerSimulated.cs
- sources/engine/Stride.Input/Windows/KeyboardWinforms.cs
- sources/engine/Stride.Input/Windows/MouseWinforms.cs
Each window comes with its own mouse and keyboard device. Therefor the generated ids must be unique per window. Further simulated devices must always have a unique id.
#919 
Creating a second input source for a second render window leads currently to a crash due to the shared id. The changes in this PR can be seen as part of #919.
> [Input] Unique input device ids per window as well as for simulated devices

- sources/assets/Stride.Core.Assets/PackageSession.Dependencies.cs
- sources/core/Stride.Core.Design/Reflection/AssemblyContainer.cs
Different approach to what I proposed in https://github.com/stride3d/stride/pull/965. This time all the dependencies as given by the project are registered in the used assembly container to ensure that a later assembly load will work.
https://github.com/stride3d/stride/pull/965
> Register assemblies in the assembly container to ensure later assembly loads succeed

- sources/engine/Stride.Graphics/Direct3D/SharpDXInterop.cs
Allows specifying that a native texture is in gamma space.
Adds a new optional parameter toSRgb.
When receiving or loading a native SharpDX texture, it is often in gamma space. This PR adds a parameter to specify the color space. The parameter already existed in the method that gets called to create the texture.
> [Graphics] Adds toSRgb parameter to CreateTextureFromNative

- README.md
Not exactly sure how we're supposed to build for net5.0 but this worked for me inside VS **only in debug**.
Release fails with a couple of projects outputting 
```
Your project does not reference ".NETCoreApp,Version=v5.0" framework. Add a reference to ".NETCoreApp,Version=v5.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.
```
See [Output.txt](https://github.com/stride3d/stride/files/5742103/Output.txt) for vs output.
Using the command line with dotnet + msbuild seems to work pretty well for both debug and release though.
> [Doc] More troubleshooting guidelines

- sources/core/Stride.Core/Threading/ThreadPool.SemaphoreW.cs
- sources/core/Stride.Core/Threading/ThreadPool.cs
``ThreadPool.Instance`` can now be assigned to, giving users the ability to change the object, and so, amount of threads the pool uses. Users should dispose of a pool if they intend to replace it.
Also imported/ported the latest changes from dotnet source, benchmarking shows a fairly small but significant enough improvement, should also waste slightly less resources on top of that improvement.
Request from @tebjan related to https://github.com/vvvv/VL.Stride/issues/294
I'm sure you can figure that one out :)
> [Threading] Allow switching default pool + small performance improvement

- sources/tools/Stride.PackageInstall/Program.cs
This fixes a problem where Stride installation always fails for the machines which do not have the `Development Tools plus .NET Core 2.1` workload installed and then shows an incorrect error message telling the user to install the incorrect workload `.NET Core 2.1 Runtime (LTS) (inside .NET core cross-platform development)` manually.
This problem was introduced with b73b2a956422171c4173cecc7d5433d2d9c67d36 - the VS installer is invoked incorrectly due to invalid generated arguments. The commit changes the array type containing necessary VS workloads from string to tuple. However, not all places that referred to the tuple were updated to access the appropriate tuple item, which in turn resulted in the tuple being consumed directly by its `ToString()` method instead of the actual workload …
> Correct VS workload name and fix VS installer arguments

- sources/tools/Stride.VisualStudio.Package/Guids.cs
- sources/tools/Stride.VisualStudio.Package/StridePackage.vsct
- sources/tools/Stride.VisualStudio.PackageInstall/Program.cs
Incorrect Stride Visual Studio extension GUID is specified when uninstalling the extension through the launcher. This causes reinstall to fail every time.
Visual Studio extension GUID was changed for Stride only in the VSIX manifest file `/sources/tools/Stride.VisualStudio.Package/source.extension.vsixmanifest`, however there are 3 additional places where the GUID is used:
* `/sources/tools/Stride.VisualStudio.Package/Guids.cs`
* `/sources/tools/Stride.VisualStudio.Package/StridePackage.vsct`
* `/sources/tools/Stride.VisualStudio.PackageInstall/Program.cs`
It needs to be changed there as well, or else the reinstall (from the Launcher) will attempt to remove Xenko Visual Studio extension instead of Stride Visual Studio extension, which causes reinstall to fail.
Xenko GUID: …
> Correct Stride Visual Studio extension GUID

- sources/engine/Stride.Rendering/Rendering/InstancingRenderFeature.cs
`CustomEffect` sample crashes when `InstancingRenderFeature` is enabled in the graphics compositor.
`InstancingRenderFeature.Extract()` does not check if `VisibilityGroup` is null, so the game crashes with `NullReferenceException`.
Fixes #987.
Improvement of stability.
> [Rendering] InstancingRenderFeature: null check for VisibilityGroup

- sources/launcher/Stride.Launcher/ViewModels/LauncherViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/PackageVersionViewModel.cs
Remove packages which are no longer referenced by any GameStudio package after uninstall or update.
When a GameStudio package is uninstalled via launcher, a lot of other packages will remain on disk which are no longer referenced by any of the remaining GameStudio packages. This change makes sure that **only** the packages which are not referenced by any GameStudio package are removed.
#992, #993, #994
Previous solution from #993 was error-prone.
> Remove packages which are no longer referenced by any GameStudio package after uninstall or update

- sources/editor/Stride.Core.Assets.Editor/Services/VisualStudioService.cs
- sources/editor/Stride.GameStudio/StrideGameStudio.cs
- sources/presentation/Stride.Core.Presentation.Quantum/Presenters/MemberNodePresenter.cs
Multiple improvements:
* Fixed crash that occurred when the IDE was changed in the settings (see #668 for more details)
* Fixed opening the solution with the Visual Studio `Default IDE` (see #1002 for more details)
* Changed the Q&A menu link to use the new `gamedev.stackexchange.com` URL (related to #706 changes)
The IDE (combobox) control from the settings window attempted to execute the value setter twice before the events were fully processed the first time. This was resulting in `OnPropertyChanging called twice for property 'NodeValue' without invoking OnPropertyChanged between calls.` exception. Second setter was called with a `null` value. The change now ignores it if the `NotNullAttribute` is set.
Furthermore, launching of the `Default IDE` from the toolbar was fixed (it needs to …
> [Editor] Fix GameStudio IDE selection crash, fix launching with Default IDE and update Q&A link

- sources/engine/Stride.Graphics/Stride.Graphics.csproj
Updates to latest Vortice.Vulkan (target 1.2.167 vulkan SDK).
- This adds support for latest raytracing support and variable rate shading in vulkan bindings.
> ENH: Update to latest Vortice.Vulkan (target 1.2.167 vulkan SDK).

- sources/engine/Stride.Rendering/Rendering/Lights/ForwardLightingRenderFeature.cs
Fixes a null pointer when switching to an empty scene.
https://github.com/vvvv/VL.Stride/issues/411
> [Rendering] Fixes null pointer after switching to an empty scene

- sources/editor/Stride.GameStudio/GameStudioWindow.xaml
- sources/presentation/Stride.Core.Presentation/ValueConverters/TypeToNamespace.cs
- sources/presentation/Stride.Core.Presentation/ValueConverters/TypeToTypeName.cs
Property type should be shown when mouse is hovered over the property in property grid (inspector).
Property type is now shown when the mouse hovers over the property in property grid (inspector). See example below:
Closes #963.
User should be able to tell the data type of the property without having to read the code of the script.
> [Editor] Show property type on hover in property grid

- sources/launcher/Stride.Launcher/Resources/Strings.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Strings.resx
- sources/launcher/Stride.Launcher/ViewModels/StrideStoreVersionViewModel.cs
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
When the Launcher shows that a GameStudio package update is available, it will now show "(local update available)" in case if it is a local build (from disk, with location such as `%LocalAppData%\Stride\NugetDev`).
Previously it was not possible to distinguish between locally built dev packages and official packages from NuGet. This PR changes that by showing "(local update available)" instead of "(update available)" for locally built packages. See the screenshot below (`4.0.*.*` versions are official, whereas `4.1.*.*` versions were built locally).
Closes #719 (proposed solution not implemented exactly as suggested, but instead just the local build indication was implemented - in my opinion, if the package was supposed to get its own separate version section entry, the actual version …
> [Launcher] Distinguish between dev updates and official updates

- sources/editor/Stride.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml
Archetype reference presenter in the editor shows buttons to clear the reference and to change the reference, even if the archetype reference is set to read-only (i.e. when the setter is null).
The archetype reference presenter was fixed. Now the buttons to clear the reference and to change the reference will be collapsed (not-shown) in case where the archetype reference is set to read-only.
This addresses #869 where the archetype reference is set to read-only, so it was never intended to be editable in the first place. It makes no sense to show these buttons for read-only properties.
Fixes #869
This was a bug. Clicking on these buttons did not do anything anyway.
> [Editor] Hide buttons that modify archetype reference when it is set to read-only

- sources/core/Stride.Core/PlatformFolders.cs
The initial assignment to `PlatformFolders.ApplicationBinaryDirectory` crashes the Android app immediately because `GetApplicationBinaryDirectory()` throws an exception (null argument) due to `GetApplicationExecutableDirectory()` returning null leading to the call `FindCoreAssemblyDirectory` -> `Path.Combine(null, "Stride.Core.dll")` where the crash happens.
Changed `GetApplicationExecutablePath` to return `PlatformAndroid.Context.PackageCodePath` which is the path of the apk file.
`GetApplicationExecutableDirectory` also avoids `FindCoreAssemblyDirectory` in Android because Android doesn't really have binaries other than the apk.
This bug was introduced due to #599
`GetApplicationBinaryDirectory` had always returned null on Android, but no code in Android actually used this returned …
> Fix Android crash due to PlatformFolders.GetApplicationBinaryDirectory call

- sources/engine/Stride.UI/Engine/UIComponent.cs
- sources/engine/Stride.UI/Rendering/UI/RenderUIElement.cs
- sources/engine/Stride.UI/Rendering/UI/UIRenderFeature.cs
- sources/engine/Stride.UI/Rendering/UI/UIRenderProcessor.cs
UIComponent sampling option
I add the sampling option just like in SpriteComponent to UIComponent
Now we can select
- Point  (Nearest)
- Linear
- Anisotropic
Comparison between Point(left) and Linear sampler(right)
I see the option is available only in SpriteComponent and at that time I want to have the same thing on UIComponent for my little 2D project
I'm quite new to Stride and maybe this option is available somewhere, but I can't find it so I just implement it.
> Add sampling option to UIComponent

- sources/core/Stride.Core/Settings/AppSettings.cs
- sources/core/Stride.Core/Settings/AppSettingsManager.cs
In #878 I have introduced a class called `AppSettings` for loading settings at runtime (defined outside of compilation as opposed to design time defined `Configuration`). While the previous implementation was usable within the context of `Stride.Core.Design` (based on YAML), when using the `AppSettings` in my game I saw a lot of things were missing for future users of this class.
As such I modified it a bit to allow for creating instances outside of reflection based serialization and provided a way to override the `IAppSettingsProvider` in the `AppSettingsManager` in case there's more than one implementation available.
Here in [RoamingAppSettingsProvider.cs](https://github.com/manio143/RiseOfTheUndeaf/blob/bd013dccdd8228757f5285e3a2109880fed101ab/RiseOfTheUndeaf.Game/Core/Configuration/Roa …
> [Core] Improve AppSettings usability

- sources/core/Stride.Core/Native/NativeLibraryHelper.cs
With the .NET 6 SDK (I used preview 4) you can use `PublishSingleFile` with your game targeting `net5.0`. They fixed the packaging mechanism of .NET 5 which complains when duplicate paths appear in the list of things to include. This allows us to publish much nicer looking applications.
With project setup
```xml
<PublishSingleFile>true</PublishSingleFile>
<IncludeNativeLibrariesInSingleFile>false</IncludeNativeLibrariesInSingleFile>
<IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
```
The `owner.GetTypeInfo().Assembly.Location` in the changes is `null` when running the single file which causes an `ArgumentException` in the `Path.Combine`. So I added safe guards to each case, just in case.
That allowed me to run the single file from it's folder.
However, …
> Enable PublishSingleFile scenarios in NativeLibraryHelper

- sources/engine/Stride.Assets/GameSettingsAssetCompiler.cs
- sources/engine/Stride.Assets/RuntimeTypesCollector.cs
Adds dynamic runtime type detection to the game settings asset compiler.
This change allows the game settings to dynamically detect referenced runtime content types and allowing custom configuration implementation to properly reference assets in a project. 
Closes #1063 
This solves the issue where assets references in custom configurations where not properly included in the build. Note that its preferable to only use `UrlReference<T>` and loading the assets when required as stride is not fully initialized when the game settings are loaded.
> #1063 GameSettingsAssetCompiler dynamically detecs runtime content types

- sources/engine/Stride.Input/PointerDeviceState.cs
The PointerPoints Id property was never set and thus always returning 0 for all pointers.
It is a one-line fix that takes the pointerId coming from PointerEvent and applying it to the created PointerPoint. 
N/A
Without pointer Ids multiple touchpoints cannot be distinguished.
> [Input] fixes PointerPoint.Id always being 0

- sources/engine/Stride.Graphics/Texture.cs
Minor improvement to SetData of Textures.
The passed DataPointer can now point to a memory area that is bigger than the target area of the texture. Before the size had to match exactly.
Allowing more options on how to set texture data.
> [Graphics] Lift SetData restriction of Texture

- sources/engine/Stride.Engine/Engine/Processors/InstancingProcessor.cs
Create and add `ModelRenderProcessor` if it doesn't exist in `InstancingProcessor`.
Fixes #813
`InstancingProcessor` has a hard dependency on `ModelRenderProcessor` which it stores in a field.
A subtle bug can occur (usually in the Game Studio) where a user adds an `InstancingComponent` before adding any `ModelComponent`s in a scene. In this scenario, `InstancingProcessor` will be created first, on its own, and null will be stored in the field, so the fix is to create the processor immediately.
> Fix InstancingProcessor dependency on ModelRenderProcessor

- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/AxialGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/CameraGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/CameraOrientationGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/GizmoEmissiveColorMaterial.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/GizmoShaderMaterial.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/GizmoUniformColorMaterial.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/LightDirectionalGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/LightPointGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/LightSpotGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/NavigationBoundingBoxGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/RotationGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/ScaleGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/TransformationGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/TranslationGizmo.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/VoxelVolumeGizmo.cs
- sources/editor/Stride.Assets.Presentation/SceneEditor/SceneEditorSettings.cs
- sources/engine/Stride.Rendering/Rendering/Editor/CameraOrientationGizmoShader.sdsl
small enhancements to the gizmos
#700 (this is only fixed when using the circular movement which is the default option)
The old gizmos weren't very nice to look at so this pr makes them look better and more user-friendly, it also changes how the rotation gizmo works (see discussion in discord `ui-ux`) and adds scale planes to the scale gizmo.
This pr also changes the text on the `CameraOrientationGizmo` to be XYZ instead of right/left... but there's a setting under the viewport settings that swaps it back to the old text
makes the gizmos look better and makes it easier to use the rotation gizmo
> Improve the editor gizmos

- sources/engine/Stride.Graphics/Rendering/EffectInstance.cs
- sources/engine/Stride.Graphics/ResourceGroupBufferUploader.cs
The buffer uploader of the effect instance allocates constant buffers but doesn't clean them up. Instead it leaves it up to the graphics device to actually dispose them when the device gets disposed. This PR addresses this by simlply cleaning them up directly.
> [Graphics] Disposes the constant buffers allocated by an effect instance

- sources/engine/Stride.Rendering/Rendering/RootEffectRenderFeature.cs
Fixes engine crash with error in effect files
When an sdfx file has an error, the engine crashes and closes. This change will take care of just showing the error material when such an error happens.
Crashes when modifying sdfx files at runtime.
> [Rendering] Fixes engine crash with error in effect files

- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/ViewModels/EntityHierarchyEditorViewModel.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Views/EntityHierarchyEditorView.xaml
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/Game/EditorGameGridService.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/Services/IEditorGameGridViewModelService.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/EditorGridViewModel.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/GridGizmoBase.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/ViewportGridGizmo.cs
- sources/editor/Stride.Assets.Presentation/SceneEditor/PackageSceneSettings.cs
- sources/editor/Stride.Assets.Presentation/View/ImageDictionary.xaml
- sources/presentation/Stride.Core.Presentation/ValueConverters/IntToBool.cs
- sources/presentation/Stride.Core.Presentation/ViewModel/ViewModelBase.cs
(i accidentally deleted the old PR, sorry)
Makes the viewport grid visible in orthographic mode even when not looking along a coordinate axis and adds grid settings to the toolbar (grid axis and opacity)
Closes #1087  and #158
> improve the viewport grid (reopened)

- sources/editor/Stride.Core.Assets.Editor/ViewModel/ProjectViewModel.cs
If you create folders to organize your code, all scripts are visible on the same level in the "Code" folder in GameStudio. That is because the first level folders are skipped in the viewmodel. This PR removes that skip, which means all this organized code is organized in GameStudio as well.
#663 (I've written more details in the comment there)
> [Editor] Don't skip first level directories for code assets

- sources/editor/Stride.Assets.Presentation/ViewModel/MaterialViewModel.cs
- sources/engine/Stride.Shaders.Parser/Mixins/StrideShaderLibrary.cs
- sources/engine/Stride.Shaders.Parser/ShaderMixinParser.cs
- sources/engine/Stride.Shaders.Parser/Utility/StrideMessageCode.cs
Changing shader classes in material composition (see picture below) doesn't add generics necessary for the shader to work.
This PR fixes a bug with the existing code failing to properly add those generics in *and* makes sure that mixin errors are properly logged.
Fixes #855
Fix bug, yes.
> [Graphics] Fix shader generic support

- sources/core/Stride.Core/Collections/ArrayHelper.cs
- sources/core/Stride.Core/Collections/FastCollection.cs
- sources/core/Stride.Core/Collections/FastList.cs
- sources/core/Stride.Core/Collections/FastListStruct.cs
- sources/core/Stride.Core/Collections/OrderedCollection.cs
- sources/core/Stride.Core/Utilities.cs
- sources/engine/Stride.Particles/Sorters/ArrayPool.cs
- sources/engine/Stride.VirtualReality/OculusOVR/OculusOvrHmd.cs
- sources/engine/Stride.VirtualReality/WindowsMixedReality/WindowsMixedRealityHmd.cs
- sources/presentation/Stride.Core.Presentation/Extensions/ObjectExtensions.cs
- sources/presentation/Stride.Core.Presentation/Services/DummyTransaction.cs
- sources/presentation/Stride.Core.Presentation/ViewModel/EditableViewModel.cs
Converts the underlying `ArrayHelper.Empty<T>` implementation to use `Array.Empty<T>` instead. Also adjusts places where array initialization was occurring needlessly.
Deprecated `ArrayHelper.Empty<T>` in favor of `Array.Empty<T>` (marked as obsolete for compatibility). Modifies multiple projects and collections, including `FastCollection`, `FastList`, and `ArrayPool` to use the static empty array instead of producing a new empty array each time. This may have minor improvements in overall memory usage, though the difference would likely be imperceptible for most applications.
#608 
Empty array initialization still requires memory space. Limiting this through use of static readonly values is preferred. .NET has supported `Array.Empty<T>` as far back as .NET Framework 4.6 and implements …
> Converted empty array initialization to Array.Empty<T>. Addresses #608

- sources/engine/Stride.Physics/Simulation.cs
Users most likely wouldn't expect triggers to be returned when looking for collisions through those one shot tests given that triggers don't collide with anything.
If they still would like to test for those as well, they can do so by setting the appropriate boolean when calling those methods.
None reported.
Bug fix, kind of.
> [Physics] Raycast and ShapeSweep can filter out triggers, true by default

- sources/tools/Stride.VisualStudio.Package/Commands/StrideCommandsProxy.cs
Switches the ambiguous and error prone long names to the friendly names instead.
#1113 
In some newer versions of .NET 5 SDK, restoration of the visual studio extension was failing. It was unable to resolve `.NET,Version=v5.0` to the version with the windows binding (and specifying other attributes like `Profile` did not work either). 
The recommendation for Target Framework Names is to standardize around the friendly name as it already encodes the platform and version. https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#mapping-to-long-names
> Changed NuGet restore to use friendly names

- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Android/ProjectExecutable.Android.ttproj
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Android/Resources/Resource.Designer.cs.t4
The Resource.Designer.cs file is required to compile Android apps with Xamarin. By default the file is not included in either Stride/Xenko 3.x or 4.x and is instead generated when the Android project is first compiled. A change in 4.x makes this file a requirement for Stride's Project Generator to create a new Android project, when the file isn't found an error is thrown and the project fails to create.
An empty Resource.Designer.cs.t4 file has been added to the Android template. This file is regenerated in a project specific context when the user first compiles their Android app via Stride or Visual Studio.
#827 
While workarounds are possible (documented in the above issue), this bug prevents the Android platform from working "out of the box" on impacted versions of Stride.
> Missing Resource.Designer.cs fix

- sources/engine/Stride.Rendering/Rendering/Images/SubsurfaceScattering/SubsurfaceScatteringBlur.cs
Simplifies ortho check in SubsurfaceScatteringBlur, much better performance too
Just a simplification.
The orthographic projection matrix has a 1 at the element M44, while perspective matrices have a 0 there.
found during the work on PR #1142.
Performance improvement.
> [Rendering] Simplifies ortho check in SubsurfaceScatteringBlur

- sources/engine/Stride.Engine/Profiling/DebugTextSystem.cs
RenderText.Print() will now work as intended when a custom text color (or colour) is set.
If a custom color is set in RenderText.Print() the text will remain the default Light Green. This is because msg.TextColor != currentColor was essentially comparing against itself and as a result always returning a value of False. With this change, msg.TextColor is now being compared to the current/default TextColor value.
#1155
> DebugText Color Fix

- sources/engine/Stride.Engine/Profiling/DebugTextSystem.cs
This PR backports the DebugText color fix from PR #1156 to Stride 4.0, please see the referenced PR for more information.
#1155
> [Backport ] DebugText Color Fix

- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/AddPrimitiveKeyCommand.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/RenameStringKeyCommand.cs
- sources/editor/Stride.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml
- sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/DictionaryNumberKeyTemplateProvider.cs
- sources/presentation/Stride.Core.Presentation.Quantum/Presenters/ItemNodePresenter.cs
- sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
Fix the problem dictionary with int type key can't change key in editor.
Add support to dictionary editor with key type as char, bool, or other number type, and can modify key now.
> Solve editor problem with dictionary

- sources/engine/Stride.Rendering/Rendering/Materials/MaterialNormalMapFeature.cs
Enables reconstruct z by default on the normal map if construct with an `IComputeColor`
Fixes #983
Reconstruct Z is disabled for materials by default, this is incompatible with the default import setting for normal maps which has compression enabled.
> #983 - Normal map feature enables reconstruct z by default

- sources/launcher/Stride.Launcher/Resources/Urls.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Urls.resx
- sources/launcher/Stride.Launcher/Resources/patreon_mark_coral_24.png
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
Patreon Image related resources were removed from the Stride.Launcher.
- Reference removed from Stride.Launcher.csproj
- LauncherWindow.xaml: Patreon BitmapImage reference removed
- LauncherWindow.xaml: Patreon Button removed
- Patreon image removed from /Resources
- Urls.resx: Link https://www.patreon.com/stride3d removed
https://github.com/stride3d/stride/issues/1186
Stride moved from Patreon to Open Collective. The Open Collective button will be added in a separate PR.
> Patreon references (button, image, ..) removed

- sources/launcher/Stride.Launcher/Resources/Urls.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Urls.resx
- sources/launcher/Stride.Launcher/Resources/opencollective-24.png
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
Open Collective Image related resources were added to the Stride.Launcher.
- Reference added to Stride.Launcher.csproj
- LauncherWindow.xaml: OpenCollective BitmapImage reference added
- LauncherWindow.xaml: OpenCollective Button added
- OpenCollective image added to /Resources
- Urls.resx: Link https://opencollective.com/stride3d added
https://github.com/stride3d/stride/issues/1187
Stride moved to Open Collective so the button was added instead of Patreon.
> OpenCollective icon added and code adjustments made accordingly

- samples/Games/SpaceEscape/SpaceEscape.Game/Effects/CustomFogEffect.sdsl
- samples/Games/SpaceEscape/SpaceEscape.Game/Effects/CustomFogEffect.sdsl.cs
- samples/Games/SpaceEscape/SpaceEscape.Game/Effects/SpaceEscapeEffectMain.sdfx
- samples/Games/SpaceEscape/SpaceEscape.Game/Effects/SpaceEscapeEffectMain.sdfx.cs
- samples/Games/SpaceEscape/SpaceEscape.Game/Rendering/BendFogRenderFeature.cs
Fix for the broken sample game - Space Escape
Name collision of FogEffect in the sample game project with the existing stride IDE object name.  
broken sample game - Space Escape issue https://github.com/stride3d/stride/issues/1183
> Issue 1183 - Fix broken sample game - Space Escape

- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
Change of the mode from NearestNeighbor to HighQuality, which improves icon quality. They are more clear and sharp on the screen.
Fixes #1223
Just to keep consistency with remaining icons which were already changed.
> BitmapScalingMode changed to HighQuality

- build/compile.bat
- sources/tools/Stride.VisualStudio.Package/BuildEngine/IDEBuildLogger.cs
- sources/tools/Stride.VisualStudio.Package/NShader/NShaderLanguageService.cs
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.nuspec
- sources/tools/Stride.VisualStudio.Package/source.extension.vsixmanifest
Updated VS plugin dependencies to build with msbuild x64 to support VS2022. Migrated code that was changed
Updated VisualStudio deps to v17
Targeted VisualStudio 17 in VS plugin
Fixes https://github.com/stride3d/stride/issues/1119
Fixes https://github.com/stride3d/stride/issues/1209
Could not build the VS plugin in VS2022 due to msbuild being x64. The older build targets do not support this.
> Update VisualStudio plugin to VS2022

- sources/engine/Stride.Shaders.Parser/Mixins/ShaderKeyGeneratorBase.cs
- sources/engine/Stride.Shaders.Parser/Mixins/ShaderMixinCodeGen.cs
- sources/engine/Stride.Shaders.Parser/ShaderLinker.cs
- sources/shaders/Stride.Core.Shaders/Analysis/Hlsl/HlslSemanticAnalysis.cs
- sources/shaders/Stride.Core.Shaders/Ast/Hlsl/ByteAddressBufferType.cs
Fixes both parsing and shader key generation for ByteAddressBuffer and RWByteAddressBuffer
Fixes #248 
The current system only works properly for generic types and textures. This change modifies that to also handle the ByteAddressBufferRWByteAddressBuffer types.
> Fixed shader compiler parsing of ByteAddressBuffer and RWByteAddressByffer

- sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs
- sources/engine/Stride.Rendering/Rendering/Utils/OpaqueBase.sdsl
Exposes the output of the opaque render stage in the transparent render stage
Output of opaque render stage is bound during transparent rendering if `BindOpaqueAsResourceDuringTransparentRendering`is enabled on the `ForwardRenderer`. Added shader `OpaqueBase.sdsl` to give access to it.
Fixes #1162 
Improves performance for common scenarios like refraction where access to the opaque output is needed by removing the need for an extra rendering of the entire scene.
> Bind opaque output during transparent render stage

- sources/engine/Stride.Engine/Engine/LightComponent.cs
Added AllowMultipleComponentsAttribute to LightComponent class
issue: https://github.com/stride3d/stride/issues/1138
Added AllowMultipleComponentsAttribute to LightComponent class
Added AllowMultipleComponentsAttribute to LightComponent class
https://github.com/stride3d/stride/issues/1138
No reason to prevent users to add multiple lights on the same entity.
Use case:
Ambient and directional light to have just one entity handling 'sun light', directional for direct and ambient for indirect.
Spot and point light for a lighthouse's beam.
Don't know how to run tests. Just builded engine and checked if multiple light sources allowed in single entity
> Added "AllowMultipleComponents" to LightComponent

- sources/engine/Stride.Games/GraphicsDeviceManager.cs
- sources/engine/Stride.Graphics/Direct3D/Texture.Direct3D.cs
Changes of color space at GameSettings now applied correctly
GraphicsDeviceManager now applies changes to GraphicsDevice.ColorSpace before calling GraphicsDevice.Presenter.Resize (resize method uses color space info stored at graphics device to resize buffer with PixelFormat)
Texture.Direct3D now always converts textureDescrioptionFormat to srgb (most likely it was a bug, so only srgb format converted to srgb again)
https://github.com/stride3d/stride/issues/1035
https://github.com/stride3d/stride/issues/1035
> Color space change bug fix

- sources/core/Stride.Core/Native/NativeLibraryHelper.cs
- sources/engine/Stride.Assets.Models/AssimpAssetImporter.cs
- sources/engine/Stride.Assets.Models/FbxAssetImporter.cs
- sources/engine/Stride.Assets/Physics/ColliderShapeAssetCompiler.cs
- sources/engine/Stride.Graphics/Font/FontManager.cs
- sources/engine/Stride.Physics/Bullet2PhysicsSystem.cs
- sources/engine/Stride.Physics/Module.cs
- sources/engine/Stride.Shaders.Compiler/EffectCompiler.cs
- sources/engine/Stride.VirtualReality/OpenVR/OpenVR.cs
- sources/tools/Stride.TextureConverter/Frontend/TextureTool.cs
For the Stride native libs (`libcore`, `libstride`, `libstrideaudio`) the existing way of locating libraries was mostly fine, but there may be libraries used like `freetype` (and previously SDL) which are assumed to be installed in the system. In order to find those, we need to pass in the correct name of the library file and let the CLR search for it in global library locations.
In order to make the code easier to read, all calls to `PreloadLibrary` should not include the extension (e.g. `.dll`).
This is a follow up to the work of #1173 as I found myself having to manually create links for some libraries the current approach wasn't finding.
> Improve native library search on Linux

- sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
An raised exception prevented those panel to display properly, ``HasDictionary`` doesn't imply that the type itself is a dictionary, this change makes it so that it test the implemented interfaces to find the proper first generic type for the implemented dictionary interface.
Fix: #1272
> [Editor] Fix blank material editor and settings panel

- sources/core/Stride.Core.Yaml/Serialization/YamlAssemblyRegistry.cs
``EscapeDataString`` changes from #1277 swaps ``!`` for ``%21``, we'll look at this whenever ``EscapeUriString`` becomes a problem.
> [Yaml] Revert EscapeDataString changes

- sources/engine/Stride.Rendering/Rendering/ProceduralModels/PrimitiveProceduralModelBase.cs
Another signature added for ```Generate()``` method.
New 
```c# 
public Model Generate(IServiceRegistry services)
```
Existing 
```c# 
public void Generate(IServiceRegistry services, Model model)
```
This will simplify creating Primitive Models from 
```c#
var model = new Model();
new CubeProceduralModel().Generate(game.Services, model);
model.Materials.Add(new Material())
```
to 
```c#
var model = new CubeProceduralModel().Generate(game.Services);
model.Materials.Add(new Material());
```
Resolves #1258
> public Model Generate(IServiceRegistry services) added

- README.md
The dotnet command can't compile C++, which causes build failures. msbuild from the build tool (or vs) just fine on its own.
The previous step adds msbuild to the path, so this should be fine. To my knowedge dotnet is doing this same thing, just it doesn't have the libraries accessable to the msbuild install at the added-path-location.
Using the `dotnet` you get errors of the flavor:
```
$repoPath\sources\tools\Stride.Assimp.Translation\Stride.Assimp.Translation.vcxproj(34,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```
Using `msbuild` it compiles more successfully.
This may be due to me using a different build …
> [Readme] Updated the readme to call out msbuild instead of dotnet.

- build/compile.bat
Switched the default build verbosity to normal to better align with restore.
Either way it's somewhat opaque, but build processes should have more information this way.
This is a follow up from https://github.com/stride3d/stride/pull/1286 and https://github.com/stride3d/stride/pull/1283 .
This change doesn't really effect anything, and it might be making things more verbose, but it does align both steps to use the same command and verbosity. 
It's a bit confusing what the command is doing outside of just calling msbuild with some arguments that could be build file provided, but if it works it works.
https://github.com/stride3d/stride/pull/1286 and https://github.com/stride3d/stride/pull/1283 both relate.
This started with a change to make the build steps a bit clearer, because I …
> Switched the default build verbosity to normal

- sources/engine/Stride.Shaders.Compiler/OpenGL/ShaderCompiler.cs
Something may have changed in path processing in `Process.Start()` - so I had to replace the Windows-style `\` with Unix-style `/`.
N/A
> Fix glslangValidator.bin path for unix platforms

- sources/engine/Stride.Engine/Engine/SceneSystem.cs
Default SceneInstance and empty Scene is created programmatically if the game is run without the default assets (MainScene.sdscene) created by Game Studio. 
Discussed here https://github.com/stride3d/stride/discussions/1253#discussioncomment-1979625
else branch added
```c#
else
{
SceneInstance ??= new SceneInstance(Services) { RootScene = new Scene() };
}
```
More details in the issue below.
Resolves #1290 
We are working on code-only approach and to simplify this approach so a game can be run without a too much boilerplate. Default scene can be always updated/replaced as needed through the code. 
This will help to run a game with a very few lines of the code.
**This change shouldn't affect any existing approach through the Game Studio Editor.**
> Default SceneInstance and Scene added for code-only approach

- sources/engine/Stride.Engine/Rendering/ModelRenderProcessor.cs
Fixes render stage evaluation if the transparency of a material changes
Render models were not moved to the correct render stage if the transparency of a material is changed at runtime.
There was already a check for re-evaluating the render stage if the `IsShadowCaster` changes, this now includes a check for changes of the `renderMesh.MaterialPass.HasTransparency`.
https://github.com/vvvv/VL.Stride/issues/493
Just a bug fix.
> [Materials] Fixes render stage evaluation if the transparency changes

- sources/engine/Stride.Input/Windows/MouseWinforms.cs
For some reason Winforms fires the `MouseCaptureChanged` when holding both and releasing just one of the two mouse buttons, see #1303
[Here's what the docs says about that event](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.mousecapturechanged?view=windowsdesktop-6.0):
> Now, click and hold the left mouse button on the Button control. While still clicking the mouse, press ALT+TAB to switch to another program. Notice that the MouseCaptureChanged event is raised enabling you to potentially handle this scenario.
It makes sense then that the engine removes any mouse button held when that event occurs but afaict it shouldn't occur in this case. I swapped it to `LostFocus` instead anyway since it makes more sense.
#1303
> [Input] Fix mouse release for Winforms

- sources/engine/Stride.Input/Keys.cs
- sources/engine/Stride.Input/SDL/KeyboardSDL.cs
Related to PR #1263 
- Made ``NumPadDecimal`` obsolete, the US key mapped to character ``.`` and ``>`` is ``OemPeriod``, not ``Decimal``. ``Decimal`` already maps to the numpad in winforms and in rawinput most likely as well given that there isn't any specific logic for it. Made changes to the SDL keyboard to reflect that.
- Fixed a conflict between ``OemBackslash`` and ``OemPipe``.
- ``NumPadEnter`` and ``OemPlus`` mapped to the right key.
- Support for ``LaunchApplication1`` and ``LaunchApplication2`` keys.
- Swapped SDL keyboard key mapping from a dictionary to a switch, I'm not too sure why we would use a dictionary for this when a switch is as easy to use and maintain ... ? Separated that change into its own push in case that's something we don't want.
- Improved the summary for most …
> [Input] Improve Input.Keys docs and fix a couple of keymapping in SDL

- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/ViewportGridGizmo.cs
- sources/engine/Stride.Graphics/BatchBase.cs
- sources/engine/Stride.Graphics/Buffer.cs
- sources/engine/Stride.Graphics/Data/BufferSerializer.cs
- sources/engine/Stride.Graphics/Data/TextureContentSerializer.cs
- sources/engine/Stride.Graphics/Data/TextureImageSerializer.cs
- sources/engine/Stride.Graphics/Font/FontCacheManager.cs
- sources/engine/Stride.Graphics/GraphicsResourceBase.cs
- sources/engine/Stride.Graphics/OpenGL/GraphicsDevice.OpenGL.cs
- sources/engine/Stride.Graphics/PrimitiveQuad.cs
- sources/engine/Stride.Graphics/ResumeManager.cs
- sources/engine/Stride.Graphics/Texture.Extensions.cs
Reloading buffers wasn't ever called in editor or in engine I don't think but fixed it just in case someone ends up using it.
Also reduced the amount of unnecessary bloat allocated through some of the more common reload delegate capture, it's not that large but given that those resource are common objects it can quickly add up for a feature that's almost never used.
> [Graphics] Fix and improve Resource.Reload

- sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.sdpkg
- sources/editor/Stride.Assets.Presentation/Templates/Assets/.sdtpl/ColliderStaticMesh.png
- sources/editor/Stride.Assets.Presentation/Templates/Assets/Physics/ColliderShapeStatic.sdtpl
- sources/editor/Stride.Assets.Presentation/Templates/ColliderShapeStaticMeshFactoryTemplateGenerator.cs
- sources/editor/Stride.Assets.Presentation/Templates/StrideTemplates.cs
- sources/engine/Stride.Assets/Physics/ColliderShapeAssetCompiler.cs
- sources/engine/Stride.Assets/Physics/ColliderShapeFactories.cs
- sources/engine/Stride.Navigation/NavigationMeshBuilder.cs
- sources/engine/Stride.Physics/Data/BoxColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/CapsuleColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/ColliderShapeAssetDesc.cs
- sources/engine/Stride.Physics/Data/ConeColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/ConvexHullColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/CylinderColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/HeightfieldColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/IColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/SphereColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/StaticMeshColliderShapeDesc.cs
- sources/engine/Stride.Physics/Data/StaticPlaneColliderShapeDesc.cs
- sources/engine/Stride.Physics/Engine/PhysicsColliderShape.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
- sources/engine/Stride.Physics/Shapes/StaticMeshColliderShape.cs
Finishes implementation of static meshes started in #289 by adding editor and model asset support. 
The shape is created at runtime by deserializing the model's vertex and index buffer from disk since we don't store whole models in cpu memory. (see comments in #289)
Models are shared, using the same model for multiple colliders won't re-allocate vertices and indices, it'll re-use the same buffer in memory.
(model credit: [luyssport on sketchfab](https://sketchfab.com/3d-models/ftm-0970f30574d047b1976ba0aa6f2ef855))
Fix #890 
Started of off and replaces PR #1213 and PR #479
> [Physics] Static mesh, asset and editor support

- sources/engine/Stride.Rendering/Rendering/Images/DepthOfField/DepthOfField.cs
Fixes crash when changing DoF quality at runtime.
Adds an `UpdateEffect()` call after setting the permutation parameter `CombineLevelsFromCoCKeys.LevelCount`. If the quality preset changes, this shader permutation key gets set, which changes the length of an array parameter. If the effect isn't updated, a subsequent `Set` on the array shader parameter throws an exception. The same is already done in the CoCMapBlur effect: https://github.com/stride3d/stride/blob/1c2969e3558228565431e267140557637033a9aa/sources/engine/Stride.Rendering/Rendering/Images/DepthOfField/CoCMapBlur.cs#L81
https://github.com/vvvv/VL.Stride/issues/333
Avoids a crash when changing the quality preset.
> [Rendering] Fixes crash when changing DoF quality at runtime

- sources/engine/Stride.Audio/Native/XAudio2.cpp
FIxed typo.
```
acutally -> actually
```
> Fix typo in XAudio2.cpp

- sources/launcher/Stride.Launcher/Services/SelfUpdater.cs
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/ViewModels/DocumentationPageViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/NewsPageViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/ReleaseNotesViewModel.cs
1) Replaced all instances of WebRequest with HttpClient plus the appropriate Get + Read operations.
2) Replaced the use of WebClient with HttpClient plus Get + stream read.
3) Removed semi-problematic references and the SDK specifier as they caused the compiler to generate a number of warnings.   All these are not needed in .NET 6.
See details above and context below.
#1361 
The top-level motivation is to improve the developer experience when working with the code and ensure that the code is using the most current classes and practices.
This change replaces several instances of deprecated classes with current classes that handle the same functionality.  
Additionally, there were quite a number of warnings output by the compiler due to the .csproj file not being updated for .NET 6. …
> Fix for Issue #1361 - Replace deprecated WebRequest & WebClient

- sources/launcher/Stride.Launcher/ViewModels/StrideVersionViewModel.cs
The launcher executable was moved to a new 'tools' directory as part of the fix for #1139.  Older packages did not contain a tools directory so added code to check for the existence of a target directory before delving into it.
Also tightened up the code in the affected area and removed an unused using statement.
1) Checked for the existence of a target subdirectory before attempting to enumerate it.  This eliminates the exception for all packages.
2) Slightly rearranged the code to make it more efficient in the affected area.
3) Eliminated an unused using statement
#1139 
Eliminates an exception for packages that do not have the current package layout.
> Fix for issue #1185 - Stride.Launcher - Could not find a part of the path

- sources/presentation/Stride.Core.Presentation/Stride.Core.Presentation.csproj
Remove last explicit reference to .NET SDK assembly to eliminate related compiler warning.
Simple change to remove ref to PresentationFramework.Aero left in Stride.Core.Presentation.csproj
#1363
Trivially removes one more warning and a potential source of nondeterminism.  Additional change made in #1362.  This should eliminate the last of the existing issues of this type.
> Fix for #1363 - remove explicit reference to assemblies in .NET SDK to eliminate compiler warning.

- sources/core/Stride.Core.Design/VisualStudio/VisualStudioVersions.cs
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
- sources/tools/Stride.VisualStudio.Package/source.extension.vsixmanifest
- sources/tools/Stride.VisualStudio.PackageInstall/Program.cs
The current VS extension is only valid on VS2019 as the architecture for 2022 has changed and per the code, earlier versions of VS are not supported.   
Update the VISX manifest to only target editions of VS2019 (16.x) and update the stand-alone installer to detect only 2019 as a valid version of VS.
#1388
See above
> Update the Visual Studio Extension and the companion installer to only target VS2019.

- sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
- sources/presentation/Stride.Core.Presentation/Controls/GameEngineHost.cs
See #94
Setting parent to none for the embedded windows (like the scene view) is enough to ensure that all inputs are received, one of the parent control is most likely eating some of the inputs. Debugging the WPF hierarchy would be a real undertaking so I'll leave it at that for now.
This PR sets the ``WS_CHILD`` flag off whenever the layout changes, not exactly sure how it works internally but the window still behaves as a child window while properly receiving inputs and testing the rest of the engine didn't result in any unexpected behavior.
Also removed ``MissingInputHack`` since it relied on rawinput which isn't part of the editor since the net5 changes I think ?
Fix #94
> [Editor] Fix missing editor keyboard input

- sources/assets/Stride.Core.Packages/NugetStore.cs
- sources/core/Stride.Core.Design/VisualStudio/VisualStudioVersions.cs
- sources/engine/Stride.Assets/StrideConfig.cs
- sources/launcher/Stride.Launcher/LauncherInstance.cs
- sources/launcher/Stride.Launcher/Resources/Strings.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Strings.resx
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/ViewModels/LauncherViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/PackageVersionViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/VsixVersionViewModel.cs
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.nuspec
- sources/tools/Stride.VisualStudio.Package/source.extension.vsixmanifest
- sources/tools/Stride.VisualStudio.PackageInstall/Program.cs
**This PR replaces #1405 since that edition had a NuGet package accidentally added then removed in a later comit.  Per suggestion by @xen2, I've squashed the commits and started this new PR so as to preserve the comments attached to the old commits from that PR.**
Since the architecture changed for extensions in 2022, the Stride extension needs to have a new identity and can only be installed on VS 2022.  VS 2019 extension support will come from the 4.0 branch and NuGet package.
- This pulls in and updates @manio143's PR: https://github.com/stride3d/stride/pull/1382
- Update the Launcher to only offer the VS Extension for VS2019 and VS2022.
- Limit the package editions eligible to install VS Extension.  For 2019, this is 4.0.x and for 2022 it's 4.1.x and later.
- Update …
> Support VS 2022 + 2019 Extensions in the launcher

- sources/launcher/Stride.Launcher/Properties/PublishProfiles/FolderProfile.pubxml
Fixes #1417.
Since the Launcher uses WPF, the publish cannot use trimming.  See the above issue for details.
> Do not trim on Stride.Launcher publish step

- samples/Tests/Stride.Samples.Tests.csproj
- sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
- sources/assets/Stride.Core.Assets.Quantum/Stride.Core.Assets.Quantum.csproj
- sources/core/Stride.Core.Design/Stride.Core.Design.csproj
- sources/core/Stride.Core.IO/Properties/AssemblyInfo.cs
- sources/core/Stride.Core.Tasks/Stride.Core.Tasks.csproj
- sources/core/Stride.Core.Yaml.Tests/Serialization/SerializationTests2.cs
- sources/editor/Stride.Core.Assets.Editor/Stride.Core.Assets.Editor.csproj
- sources/engine/Stride.Assets.Tests2/Stride.Assets.Tests2.csproj
- sources/engine/Stride.Assets/Stride.Assets.csproj
- sources/engine/Stride.Particles/Spawners/SpawnerFromParent.cs
- sources/engine/Stride.Particles/VertexLayouts/ParticleBufferState.cs
- sources/engine/Stride.Particles/VertexLayouts/ParticleVertexBuilder.cs
- sources/targets/Stride.UnitTests.targets
Continuing to chip away at numerous varieties of build-time warnings and make minor code cleanup changes.
- Add a runtime ID to Stride.Samples.Tests so the compiler won't evaluate a different architecture as its dependencies and emit a warning.
- In Stride.Samples.Tests, remove link to AttachedChildProcessJob.cs as its not needed and results in a duplicate symbol warning.
- In AssetPropertGraph, actually use the isDisposed field.
- In several projects, use the released version of System.Collections.Immutable rather than the prerelease.
- In Stride.Core.Design, allow it to see the internal NativeLockFile compiled into Stride.Core.IO and avoid the duplicate symbol warning.
- Correct a few cases of sealed classes having protected members.
- As hygene, move ParticleBufferState to its own .cs …
> Removing build-time warnings

- sources/launcher/Prerequisites/launcher-prerequisites.aip
- sources/launcher/Setup/setup.aip
- sources/prerequisites/prerequisites.aip
Update the setup prereqs and main setup installer projects to detect and, if needed, install .NET 6.   At the moment Advanced Installer only knows about 6.0.2 but that will be fine.
Also update to latest Advanced Installer, version 19.4.
Fixes #1410 
Manually tested.
> Update setup packages to detect and install .NET 6

- sources/core/Stride.Core.Design/Reflection/AssemblyContainer.cs
Fixes assembly load exception in asset compiler due to full name comparison being too restrictive.
For example consider App -> Foo -> Bar (1.0) with the App referencing a newer version of Bar (2.0)
A full name comparison would now compare Bar (1.0) to Bar (2.0) and fail to load.
Had a third party dependency referencing an older version of a library we already upgraded.
> Fixes assembly load exceptions in asset compiler

- sources/engine/Stride.Rendering/Rendering/Mesh.cs
A simple fix to the Mesh copy constructor which was missing copying the BoundingSphere property
> Mesh copy constructor was missing BoundingSphere

- sources/engine/Stride.Rendering/Rendering/Materials/MaterialNormalMapFeature.cs
Updates the `DefaultValue` attribute to match the value set in the constructor, this prevents an issue where it would never serialize if the value was changed to `false` as values that match the default are ignored in the yaml serializer.
> #983 Update DefaultValue attribute for IsXYNormal property

- samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/Player/HandController.cs
Just removing a null check, as the type has changed from class to a struct and cannot be null.
Just removes a null check.
Fixes #1457
> [Samples] Fix build error of VRSanbox

- sources/core/Stride.Core/IL/RemoveInitLocalsAttribute.cs
- sources/engine/Stride.Rendering/Rendering/EffectValidator.cs
Migrate `[RemoveInitLocals]` to `[SkipLocalsInit]` and obsolete `RemoveInitLocalsAttribute`
Similar in spirit to #1461.
Eliminates one usage scenario of IL weaving.
> Migrate `[RemoveInitLocals]` to `[SkipLocalsInit]` and obsolete `RemoveInitLocalsAttribute`

- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/Core/Utils.cs
Fix TopDownRPG punch animation caused in raycast not detecting trigger collider when attacking.
Punch logic uses raycast check with a trigger collider.
#1105 disabled trigger check by default, which is a breaking change.
> Fix TopDownRPG sample punch animation

- sources/engine/Stride.Engine/Profiling/DebugTextSystem.cs
Changes a queue into a list so it can be iterated.
Added variable to hold the default time on screen with an arbitrary value of 1 second.
Added methods to expose the configurable times to the user.
Removed clearing the message queue on every update.
Deleted duplicated if check.
Changed foreach into a for loop that can remove entries after they "expire".
None that i know
Debug text dissapear too fast to be useful by itself in a lot of cases
The changes made on the code allows the user set how much do they want the text to stay on screen in each message and the default value when it's not specified.
> DebugTextSystem configurable time on-screen

- sources/core/Stride.Core.Mathematics/Matrix.cs
Fix Matrix.Invert to return zero matrix if inversion fails, which is how it previously behaved before #1301.
This is because System.Numerics.Matrix4x4.Invert behaves differently and sets the matrix to NaNs on failure (but has a bool return value to check which we don't have).
Revert to previous behavior since NaN can cause issues.
> Fix Matrix.Invert to behave as before #1301

- sources/core/Stride.Core.Design.Tests/TestPackageVersion.cs
- sources/core/Stride.Core.Design/PackageVersion.cs
http://semver.org now has Semantic Versioning 2.0.0 and if you reference a csproj that contains something like `<PackageVersion>1.0.0-rc.3</PackageVersion>` (a valid SemVer 2.0.0 format), Stride's Asset compiler will error and you can't build your project.
Expand regex for supporting `.` within "pre-release version", and ignore "build metadata".
Also note that the regex pattern for the "pre-release version" has expanded to allow alphanumeric instead of just an alphabetic char (as allowed by SemVer).
As per the documentation "Build metadata" has no ordering precedence, so can be safely discarded.
Tests have been added to ensure nothing is broken (hopefully!).
> Add build support to referencing projects that use SemVer 2.0.0 format

- samples/Tests/Stride.Samples.Tests.csproj
- samples/Tests/TestServerResolver.cs
- sources/editor/Stride.Assets.Presentation/StrideDefaultAssetsPlugin.cs
- sources/engine/Stride.Games.Testing/GameTestingClient.cs
- sources/shared/Stride.NuGetResolver/NuGetAssemblyResolver.cs
- sources/tools/Stride.SamplesTestServer/Stride.SamplesTestServer.csproj
The Stride.Samples.Tests is a project that allows us to test more complex game scenarios, by executing the actual sample game completely and simulating user input. It has been broken for a while and during my debugging session of Eric's changes to modernize Stride I encountered this problem and tried to fix it ad hoc. Now I was able to put some more time into it.
The issues:
- Fixed by modifying the static path
- Fixed by integrating Stride.NuGetResolver and asking it to resolve the test server, to which I added a reference to GameStudio. This way you can build solution, run Stride.Samples.Tests and in one step it works.
N/A
> Fix Samples.Tests and SamplesTestServer to auto-resolve packages

- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/Player/PlayerInput.cs
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/Player/WeaponScript.cs
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/Assets/MainScene.sdscene
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/Camera/ThirdPersonCamera.cs
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/Player/PlayerInput.cs
Some points in the template use `this.GetSimulation().FixedTimeStep` as the delta time, that represents the delta between fixed update of the physics simulation, not the delta between each update of the game loop.
It also tends to apply that delta to mouse input, which leads to sluggish controls.
Also very small change to camera interpolation for TPP, the camera now comes slightly faster to rest, easier to gauge distances to jump when the camera is not rotating.
None.
Fix bug.
> [Template] Fix first and third person delta time usage

- sources/core/Stride.Core.IO/IVirtualFileProvider.cs
- sources/core/Stride.Core.Serialization/IO/DatabaseFileProvider.cs
- sources/core/Stride.Core.Tests/IO/DatabaseFileProviderTests.cs
Make it more obvious via intellisense on how to use the `ListFiles` method of `IVirtualFileProvider`. For actual file system the behavior corresponds to `Directory.GetFiles()` and I've copied parameter comments from that method. Additionally I added an example specific to URL of `DatabaseFileProvider` and written a unit test of its Regex implementation.
N/A
> Improve documentation of ListFiles and add tests for DatabaseFileProvider implementation

- sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
When building Stride myself I have encountered several times errors in Assets.CompilerApp where the MSBuild.Locator returns the .NET SDK paths without the trailing slash. When concatenating this paths with the MSBuild DLL or any other things, the resulting path is incorrect.
This PR is an easy fix that uses `Path.Combine()` instead of string concatenation to resolve the issue.
> Use Path.Combine() to concatenate MSBuild paths

- sources/core/Stride.Core.Mathematics.Tests/TestMatrix.cs
- sources/core/Stride.Core.Mathematics.Tests/TestQuaternion.cs
- sources/core/Stride.Core.Mathematics.Tests/TestRotationsData.cs
- sources/core/Stride.Core.Mathematics/Matrix.cs
- sources/core/Stride.Core.Mathematics/Quaternion.cs
- sources/editor/Stride.Assets.Presentation/CurveEditor/ViewModels/RotationCurveViewModel.cs
- sources/engine/Stride.Engine/Engine/TransformComponent.cs
- sources/presentation/Stride.Core.Presentation/Controls/RotationEditor.cs
Fixes the edge cases of the yaw/pitch/roll method variants of `Matrix.Decompose` & `Quaternion.RotationYawPitchRoll` and `Matrix.DecomposeXYZ` where pitch (or yaw) is 90 degrees, but not being handled by the correct edge case logic.
Also fixed a minor bug in the editor where rotation X displays `-0` instead of `0`.
Had to fish through google to try and track down what formulas are being used.
The closest I found was ['Euler Angle Formulas' by David Eberly](https://www.geometrictools.com/Documentation/EulerAngles.pdf)
The existing code checked for the +/- 1 edge cases using Asin and Cos, however the loss of precision in operating on Pi/2 when constructing the rotation matrix meant it'd never hit Cos(Angle) == 0, even with ZeroTolerance check. According to Eberly's pdf, just checking `M32` …
> Fix rotation yaw/pitch/roll decompose calculation bugs on edge cases

- sources/core/Stride.Core.Mathematics/Color3.cs
- sources/core/Stride.Core.Mathematics/Color4.cs
- sources/core/Stride.Core.Mathematics/ColorBGRA.cs
- sources/core/Stride.Core.Mathematics/ColorHSV.cs
- sources/core/Stride.Core.Mathematics/Double2.cs
- sources/core/Stride.Core.Mathematics/Double3.cs
- sources/core/Stride.Core.Mathematics/Double4.cs
- sources/core/Stride.Core.Mathematics/Half2.cs
- sources/core/Stride.Core.Mathematics/Half3.cs
- sources/core/Stride.Core.Mathematics/Half4.cs
- sources/core/Stride.Core.Mathematics/Int2.cs
- sources/core/Stride.Core.Mathematics/Int3.cs
- sources/core/Stride.Core.Mathematics/Int4.cs
- sources/core/Stride.Core.Mathematics/Point.cs
- sources/core/Stride.Core.Mathematics/Size2.cs
- sources/core/Stride.Core.Mathematics/Size2F.cs
- sources/core/Stride.Core.Mathematics/Size3.cs
- sources/core/Stride.Core.Mathematics/UInt4.cs
- sources/core/Stride.Core.Mathematics/Vector2.cs
- sources/core/Stride.Core.Mathematics/Vector3.cs
- sources/core/Stride.Core.Mathematics/Vector4.cs
Just adding deconstructors to most of the basic struct types in Mathematics.
Pretty straight forward add. The only hiccup is I noticed I included a document format on Int2.cs. That change was immaterial so I didn't bother to revert it. 
for example: new Init2() became new();
none
I wanted my syntactic sugar high.
> Added deconstructors to most of the structs in Stride.Mathematics

- .gitignore
- .vscode/settings.json
I think the vscode settings should be individual choice for each developer, so this prevents from making settings.json file in this repo
> Remove settings.json and update gitignore

- sources/engine/Stride.Games/SDL/GameWindowSDL.cs
Addressing the issue reported in #1543 - this time only regarding SDL.
Cleaned up the code and tested it, pinging @tebjan since that's kind of his thing. I would like your input on the change I introduced that removed the tests for `GameFormSDL` to always operate on window, is there a specific reason for it ?
#1543
> [Rendering] Addressing PVS report - SDL

- sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
`UpdatePhysicsTransformation()` is likely to set the transformations of the physics-engine side object based on previous frame transformation instead of latest, [see summary of `WorldMatrix` to explain why](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Engine/Engine/TransformComponent.cs#L45-L49).
It makes sense that an `Update` function works with up to date data, so this looks more like a bug to me.
More context here https://github.com/stride3d/stride/pull/1401#discussion_r850608711 and in the discussion further below.
Also took the time to clean things up a bit.
Fix bug.
> [Physics] Update WorldMatrix when forcing transformation on PhysicsComponent

- sources/assets/Stride.Core.Packages/Stride.Core.Packages.csproj
- sources/core/Stride.Core.Design/Stride.Core.Design.csproj
- sources/editor/Stride.Assets.Presentation/AssetEditors/ProjectWatcher.cs
- sources/tools/Stride.NuGetLoader/Stride.NuGetLoader.csproj
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
Updating NuGet dependencies to version `6.4.0`.
Removing legacy C# language check which no longer applies. Putting instead something for diagnosing issues in the future.
Temporary patch for #1453 
See https://github.com/stride3d/stride/issues/1453#issuecomment-1433729780
> Update NuGet dependencies to 6.4.0 (temporary fix for ScriptEditor issues)

- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/InstantiatingPrefabsDemo.cs
- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LoadingContentDemo.cs
an issue was found in the beginner csharp tutorial template. This PR should resolve the issue as it seems the Constructor may have changed its formatting in a previous release.
I only had to switch the location of the values in the constructor at the below locations:
InstantiatingPrefabsDemo line 28
LoadingContentDemo.cs line 71
https://github.com/stride3d/stride/issues/1617
makes sure new users can load the beginner templates without having to fix issues.
> fixed constructors in CsharpBeginner template

- sources/targets/Stride.UnitTests.targets
Some tests were crashing with a type load exception due to missing native libraries (for example Stride.Navigation.Tests).
> [Build] Fixes native libraries not copied to output folder of unit tests

- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
Vsync off was no longer working since we use the new flip model (#1594).
This PR re-enables that feature, taking most of the code from https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/variable-refresh-rate-displays
> [Graphics] Fixes Vsync off when using new flip model

- sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
- sources/editor/Stride.GameStudio/Program.cs
Remade from https://github.com/stride3d/stride/pull/1641 because I broke my master branch.
This PR should make the readabilty of a common error easier to understand.
I added references to the .NET 6 package in 2 places where an error describes needing MSBuild 16.0. I added these because even the VS2022 installation does not solve this error and user need to manually install the .NET 6 SDK in order for gamestudio 4.1 to run.
I also did a little bit of code clean up with some if statements.
https://github.com/stride3d/stride/issues/1612
also at least one question about this problem a week in the discord.
There are a lot of new Stride user coming in that have not manually installed the .NET 6 SDK. I am hoping this error message will be a bit more friendly to read.
> rebased branch

- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
This is a follow up on #1631 - while debugging a different issue it turned out that the `AllowTearing` flag must not be set when not using the flip model.
> [Graphics] Fixes crash when flip model is not supported

- sources/tools/Stride.Importer.FBX/AnimationConverter.h
This is a (possible) fix for https://github.com/stride3d/stride/issues/1567 and https://github.com/stride3d/stride/issues/1584 .
Due to a possible bug in FBX SDK:
```cpp
FbxTime::GetOneFrameValue(FbxTime::eFrames30Drop)
```
returns `0`. While the documentation says it returns the same value as  (citation: http://docs.autodesk.com/FBX/2014/ENU/FBX-SDK-Documentation/index.html?url=cpp_ref/class_fbx_time.html,topicNumber=cpp_ref_class_fbx_time_html29087af6-8c2c-4e9d-aede-7dc5a1c2436c )
```cpp
FbxTime::GetOneFrameValue(FbxTime::eNTSCDropFrame)
```
The smallest numerical values of the `GetOneFrameValue function` were determined with this short C++ program:
```cpp
#include <iostream>
#include <vector>
#include <algorithm>
#include <unordered_map>
#include <string>
#include …
```
> Possible fix for the animation importer crashing

- sources/editor/Stride.GameStudio/StrideGameStudio.cs
Update the link used in the editor from the closed Stride forums to Github community.
Use the GitHub community as forum, since `https://forums.stride3d.net/` is marked as read only. I didn't consider creating a issue since this change is trivial to implement.
- **N/A** Bug fix (non-breaking change which fixes an issue)
- **N/A** New feature (non-breaking change which adds functionality)
- **N/A** Breaking change (fix or feature that would cause existing functionality to change)
- **N/A** My change requires a change to the documentation.
- **N/A** I have added tests to cover my changes.
> Update the forum link with Github discussions link

- sources/engine/Stride.Graphics/Direct3D/CommandList.Direct3D.cs
I added a simple null check as when I was working with the source built version of stride this caused crashes about 3 times.
I am not 100% sure what causes this to be null since this seems to be called per frame but there were a few times when I added some new models that when I selected them the Gamestudio would pop up the crash message. 
I could not recreate this consistantly but after adding this I wasnt getting anymore issues.
Should fix some crash issues when NativeDeviceContext is null
> fix Crash when NativeDeviceContext is null

- build/Stride.Android.sln
- build/Stride.Runtime.sln
- build/Stride.iOS.sln
- build/Stride.sln
- sources/targets/Stride.Core.props
The solution files have wrong `.targets` and `.props` file links in the sections `00-Targets.Private` and `00-Targets.Build`.
Some of these files no longer exist. Others have the old name from pre-Stride days in the form of `Stride.PreSettings.targets` and `Stride.PostSettings.targets` instead of the new pattern `Stride.props` and `Stride.targets`. As these were broken links in the solution files, they were listed by Visual Studio, but couldn't open them.
This PR removes the missing ones, and renames the other ones to point to the corresponding files in `build` and `targets` directories. Also adds some new files that were not in the solution files but can be useful to have.
This should be a pretty innocuous change.
> Renamed build scripts in solution files and removed missing ones

- sources/core/Stride.Core.Design/Reflection/AssemblyContainer.cs
It seems .NET Core behaves slightly different in this regard, throwing a different kind of exception, so previous code no longer applies, even though it's the same assembly being loaded (irrKlang.NET4.dll)
#1072
> [Reflection] Fixes loading of mixed mode assemblies in .NET Core

- sources/engine/Stride.Physics/Shapes/BoxColliderShape.cs
This PR fixes incorrect BoxCollider detection when the is2D checkbox is selected, simply by creating a 2D BoxShape version.
#1707
> Fix BoxColliderShape by creating Box2D shape when is2D

- sources/editor/Stride.Assets.Presentation/AssetEditors/ProjectWatcher.cs
The Comparison was wrong as the UPath always fits the main Project.
It will never reach the other Projects
So i changed the Comparison to be Project related and not UPath related
that bug was annoying.
Each change in a sub project didnt get reloaded.
> fix #1703 Changing the comparison project related and not UPath related

- sources/engine/Stride.Graphics/Direct3D12/Buffer.Direct3D12.cs
- sources/engine/Stride.Graphics/Direct3D12/CommandList.Direct3D12.cs
- sources/engine/Stride.Graphics/Direct3D12/QueryPool.Direct3D12.cs
- sources/engine/Stride.Graphics/Direct3D12/Texture.Direct3D12.cs
- sources/engine/Stride.Graphics/OpenGL/Texture.OpenGL.cs
- sources/engine/Stride.Graphics/Vulkan/Buffer.Vulkan.cs
- sources/engine/Stride.Graphics/Vulkan/CommandList.Vulkan.cs
- sources/engine/Stride.Graphics/Vulkan/PipelineState.Vulkan.cs
- sources/engine/Stride.Graphics/Vulkan/Texture.Vulkan.cs
- sources/engine/Stride.Particles/ParticlePool.cs
- sources/targets/Stride.props
- sources/tools/Stride.TextureConverter.Wrappers/FreeImage.Net/Classes/MemoryArray.cs
- sources/tools/Stride.TextureConverter.Wrappers/FreeImage.Net/Classes/MetadataTag.cs
- sources/tools/Stride.TextureConverter.Wrappers/FreeImage.Net/Classes/Palette.cs
- sources/tools/Stride.TextureConverter.Wrappers/FreeImage.Net/FreeImageWrapper.cs
- sources/tools/Stride.TextureConverter.Wrappers/FreeImage.Net/Structs/FIICCPROFILE.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/MemoryArray.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/MetadataTag.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/Palette.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/FreeImageWrapper.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Structs/FIICCPROFILE.cs
When building the runtime, the other graphics APIs that are not Direct3D 11 (OpenGL, Vulkan, Direct3D 12) results in errors stating that `Utilities.CopyMemory()` and `BinarySerialization.Read()` don't exist.
A previous PR replaced several many interop and IL weaved methods with the use of `ref`s, `Span<T>`, and `Unsafe` calls, but several of those for the other graphics APIs were not replaced.
This PR completes the replacement and fixes those errors when building `Stride.Runtime.sln`.
* Replaces several uses of `Utilities.CopyMemory()` with `Unsafe.CopyBlockUnaligned()`.
* Replaces several uses of `BinarySerialization.Read()` with `Unsafe.Read()`.
* Adds a small section in `Stride.props` where users can set the design-time graphics API to override the default one with so the proper …
> Fix missing Utilities.CopyMemory for other graphics APIs

- sources/engine/Stride.Graphics/Direct3D/Texture.Direct3D.cs
Right now creating a texture from a native texture with D3D11_RESOURCE_MISC_SHARED_NTHANDLE  will fail unless it is also D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX. This combination is recomended but not mandatory acording to the specification: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_resource_misc_flag
The PR changes the code that checks for shared handles from a switch/case to an if/else where the check is done for flags using a bitwise and instead of comparing the full flag to an specific value. Shared NT is checked first as Shared & SharedNT can be set at the same time.
https://github.com/stride3d/stride/issues/1758
Allows to use DX11 textures with an NT handle but no keyed mutex
> Fix DX11 shared textures

- sources/core/Stride.Core/PlatformFolders.cs
A user had an issue running tests from Rider, the folder returned from that function pointed next to the test runner executable instead of the dlls. Pinging @tebjan since this is his area.
None logged
> [System] Fix binary path location when dlls run from an unexpected executable

- sources/engine/Stride.Graphics/Shaders/ColorUtility.sdsl
Adds the basic conversion methods for sRGB, and screen gamma.
Stride already has `ToLinear` methods, which are there same as `SRgbToLinear`, I could not remove them because it could potentially break existing shaders. Stride also has additional methods for single `float` and `float3`, which I have not provided, but I am open to adding this if requested.
We had this in a temporary file in the vvvv code, but it would be better to put this into the official ColorUtility of Stride:
https://github.com/vvvv/VL.Stride/pull/395#issuecomment-760253956
Getting color issues right when working with designers.
> Adds sRGB and Gamma conversions to ColorUtility.sdsl

- sources/engine/Stride/Graphics/Image.cs
Fixes "Image size different than expected." in the Asset Compiler when compiling for Android with graphics level 10+.
Gets the correct 'bpb' value for certain ETC2 pixel formats.
Solves the first part of #1600 however my machine isn't set up correctly to fix the other ETC2 issues.
> [Graphics] Fix expected image size for OpenGL textures.

- sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs
Could extend to cover issue #1633 depending on what we want ?
> [Asset] Show warning message when importing assets that are not inside of the resource folder

- sources/core/Stride.Core.Tasks/Program.cs
Here's how it looks now when building without the right SDK installed:
None logged in github as far as I could find
> [Build] Show useful error message and directions for users lacking requirements to run Stride.Core.Tasks

- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityTransformService.cs
- sources/editor/Stride.Assets.Presentation/SceneEditor/SceneEditorSettings.cs
Implements a dynamic snapping used while holding down a key (default: Left Shift) on manipulating (rotating/moving/scaling) an object/entity. It is possible to use STRG + Shift to duplicate with snapping, too.
* New: Add new Hotkey Setting for dynamic snapping
* New: Add Method to handle dynamic snapping
To prevent from having to toggle the snapping on in the first place before manipulating an object, it is now possible to quickly (de)activate it, when it is (not) needed.
> [Editor] Add dynamic snapping for selected objects

- README.md
Bullet points alignment fixed from:
to:
> Update README.md - Bullet point fixed in Prerequisites

- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
Flip model supports 3 different formats, none of them are sRGB.
The asset view swaps between gamma and linear rendering depending on the asset, so non-sRGB and sRGB format.
When the swap chain is initialized, the logic stripped out the sRGB specifier from the format provided, so it never could crash then.
But when the view changes size or format, ResizeBuffer is called, if the format requested is sRGB it won't be stripped out, so it'll silently crash the application.
Ensures that the format, when creating and on resize, is not only non-sRGB but also supported by flip model.
This seems a bit weird for me though, should we not require the callers to provide a format that is compatible with the flip model if they do enable it, instead of silently fixing the format for them ? I can understand …
> [Graphics] Dx11: Fix ResizeBuffer when swap chain is under flip model and changing format

- sources/assets/Stride.Core.Assets/Package.cs
- sources/assets/Stride.Core.Assets/PackageSession.Dependencies.cs
- sources/assets/Stride.Core.Assets/PackageSession.cs
- sources/assets/Stride.Core.Assets/SupportedProgrammingLanguage.cs
This PR adds support for additional project types: `.fsproj` and `.vbproj`, enabling **F#** and **Visual Basic** coding in Stride's code-only approach. Further work may be required to integrate F# and Visual Basic into the Stride Game Studio, which I will leave to more experienced contributors.
This PR serves as a follow-up to the incomplete https://github.com/stride3d/stride/pull/1078. I've implemented the changes necessary for a "code-only" approach, as I'm currently not familiar with Stride Game Studio.
To accommodate these changes, I've introduced a `SupportedProgrammingLanguage` record and a `SupportedProgrammingLanguages` class. I opted for these names as `SupportedLanguage` is already used within the codebase for a different purpose.
I'm open to feedback on the naming conventions …
> Feature: Add Support for F# and VB Project Types

- sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs
This pull request adds a prompt to copy imported assets to the Resources directory directly from the editor.
- I added a prompt asking if the user wishes to copy the file they imported to the Resources directory.
- If they say yes, another prompt asks them if they want to copy it to the default directory, if they say yes, it will copy it to the default Resources directory following the structure of the Assets dir (if they import the file TheSong.mp3 in Assets/Music the resource would get copied to Resources/Music/TheSong.mp3), else, a save file dialog will appear allowing them to choose where in the resources directory they want to place the file.
- If they say no, the file will get imported as is.
- If the resource already exists, a prompt will appear allowing them to either override the …
> Added the ability to copy imported assets automatically to the Resources dir

- sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
- sources/editor/Stride.GameStudio/Program.cs
Stride 4.1 requires the .NET 6.0 SDK. The existing FindAndSetMSBuildVersion() method can be bypassed if an older version of the SDK is installed (i.e., 5.0) because the method is checking for .NET Core 3 or above.
After bypassing this prerequisite check, Stride will function normally until the user attempts to build their project.
The _x.Version.Major_ requirement was raised in Stride.Core.Assets\PackageSessionPublicHelper.cs, the check is performed when the user opens Stride 4.1.x. If the SDK is missing the user is prompted to install it, the detected SDK version is provided to help with troubleshooting.
Prompted by discussion in issue https://github.com/stride3d/stride/issues/1753
> Check to see if the .NET 6.0 SDK is Installed When Launching Stride

- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.iOS/$ProjectName$.csproj.t4
The iOS .csproj template does not support .NET Core, this results in various exceptions when generating iOS projects with Stride 4.1.
The template file was updated to support .NET Core/6.0, GenerateAssemblyInfo is false to avoid build conflicts with the Stride generated AssemblyInfo file.
https://github.com/stride3d/stride/issues/1414
> iOS Project Template Updated to Support .NET 6

- sources/engine/Stride.Physics/Simulation.cs
Add events to Simulation, users can subscribe to those to have their logic run before or after a physics tick occur.
#1153 - changing that one to cover the implementation of a processor over those new events
See #1153
> [Physics] Pre and Post simulation tick event

- sources/presentation/Stride.Core.Presentation/Controls/TextLogViewer.cs
Stacktrace are always hidden by default in the editor logger, UX is not there yet to properly convey to the user that they should press on the `(...)` button to show it, so let's turn it on by default.
> [Editor] Log viewer shows stacktrace by default

- deps/Gettext.Net/GNU.Getopt.dll
- deps/Gettext.Net/GNU.Gettext.Msgfmt.dll.config
- deps/Gettext.Net/GNU.Gettext.Msgfmt.exe
- deps/Gettext.Net/GNU.Gettext.Msgfmt.exe.config
- deps/Gettext.Net/GNU.Gettext.dll
- deps/Gettext.Net/System.Configuration.ConfigurationManager.dll
- deps/Gettext.Net/System.Security.AccessControl.dll
- deps/Gettext.Net/System.Security.Permissions.dll
- deps/Gettext.Net/System.Security.Principal.Windows.dll
- sources/core/Stride.Core.Translation/Stride.Core.Translation.csproj
- sources/targets/Stride.Core.targets
- sources/tools/Stride.Core.Translation.Extractor/Stride.Core.Translation.Extractor.csproj
PR fixes translations by using dlls and updated code from my gettext fork : https://github.com/Jklawreszuk/gettextnet.
Although, It works correct and imho it could be merged I would say that is only temporary fix.
There are couple things need to do in the future:
#1714
> Translations fix

- sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptEditor/Resources/ThemeScriptEditor.xaml
Improve editor tooltip legibility in Light Steel Blue theme
- Updated the `Background` property to use a dynamic resource for the background color.
- Updated the `BorderBrush` property to use a dynamic resource for the border color.
The Light Steel Blue theme had issues with legibility in editor tooltip, where it used black font on an almost-black background. This change addresses this problem by updating the theme style.
Fixes: #1191
Improve Editor UI UX
> fix(theme): Improve editor tooltip legibility in Light Steel Blue theme

- sources/assets/Stride.Core.Assets/Serializers/IdentifiableObjectSerializer.cs
- sources/core/Stride.Core.Design/Extensions/TypeDescriptorExtensions.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Views/EntityPickerWindow.xaml.cs
- sources/editor/Stride.Assets.Presentation/NodePresenters/Commands/PickupEntityComponentCommand.cs
- sources/editor/Stride.Assets.Presentation/SceneEditor/Services/StrideDialogService.cs
- sources/editor/Stride.Assets.Presentation/TemplateProviders/EntityComponentReferenceTemplateProvider.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/AbstractNodeEntryNodeUpdater.cs
- sources/presentation/Stride.Core.Presentation/View/TemplateProviderSelector.cs
Previously, interface fields and properties were treated as value types in the editor, having such a field would show a combo box where the user could select the type of field they wanted to create.
Now components marked with an interface can be assigned to a field of that interface type on another component, enabling more complex gameplay architecture.
https://github.com/stride3d/stride/assets/5742236/b3081938-e9d7-42df-9dc9-e3c1ad85d464
The serialization already mostly supported this feature, just had to change how `IdentifiableObjectSerializer` operates slightly.
Fixes #764
> [Serialization][Editor] Reference type support on interface fields and properties

- sources/engine/Stride.Physics/PhysicsSettings.cs
- sources/engine/Stride.Physics/Simulation.cs
Right now VSync and other update rate control may affect the simulation speed when under 30 fps;
Physics updates at 60hz, by default there is one additional substep, so if the game runs between 60fps (one tick per update) and 30fps (two ticks per update) the substep will continue to make the simulation run at the expected speed, but under that point the simulation will do the additional substep and ignore the rest of the delta time, which will make it look like the simulation 'slows down'.
To fix this we could naively increase the amount of substeps that the simulation can do, to a point where it could cover from 60 to 5fps let's say. This has the side-effect of creating a negative feedback loop where the reason we have such low FPS is because of the simulation, and the added substeps are …
> [Physics] Change simulation substeping behavior

- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/LightDirectionalGizmo.cs
The logic for hiding/showing the directional light arrow based on whether it has been selected was removed. The arrow is now always visible in the editor. This current implementation is identical to JackPilley's, but that branch was quietly closed before it was merged into the main branch. As was mentioned in the related issue, this is the simplest approach to solving the issue, but we can also look at alternative methods if they're preferred.
I've marked this PR as a work-in-progress in case we want to explore alternative solutions.
This is how the directional light looks with the change, regardless of whether it's been selected:
This is in follow-up to the issue requesting the arrow for directional lights always be visible:
https://github.com/stride3d/stride/issues/909
This change is …
> Always show directional light arrow

- sources/editor/Stride.Editor.CrashReport/CrashReportForm.cs
Clicking the Privacy Policy link in the Crash Reporter will generate an exception.
The Process requires shell execute to be enabled, this was the default setting in .NET Framework but is no longer the case with .NET Core.
This PR can be tested by adding the following to Main() in Stride.GameStudio/Program.cs,
```
try
{
throw new Exception("Test");
}
catch (Exception ex)
{
HandleException(ex, 0);
}
```
> Fixed Exception Caused By Privacy Policy URL in Crash Reporter

- sources/engine/Stride.Graphics/OpenGL/OpenGLConvertExtensions.cs
Fix loading certain textures on Android.
eg. With TopDownRPG template, the game would crash with
```
Stride.Core.Serialization.Contents.ContentManagerException: Unexpected exception while loading asset [Textures/LensFlare01]. Reason: Unsupported texture format: ETC2_RGB.
```
Add the missing ETC2 formats.
> Fix missing OpenGLES texture formats.

- sources/editor/Stride.Core.Assets.Editor/ViewModel/EditorViewModel.cs
Fixes the issue where projects were disappearing from the launcher after exiting without saving an already saved project. Now, projects will persist in the launcher.
This commit addresses the bug reported where projects were not persisting correctly in the launcher after unsaved exits of saved projects.
- The EditorViewModel's RemoveRecentFile method calls the RemoveFile method in the MRUDictionary.
- This triggers the execution of mostRecentlyUsedFiles.RemoveWhere(x => string.Equals(x.FilePath, filePath, StringComparison.OrdinalIgnoreCase)).
- Similarly, when the AddFile method is used in the MRUDictionary, it also executes the same RemoveWhere operation.
Refs: #1184
Address the problem of recent projects disappearing from the list.
> Fixes the issue where projects were disappearing from the launcher

- sources/targets/Stride.Core.targets
Fixes a typo in the translations generation. Replaces `traduction` with `translation`. Also reformats the XML in the `.target` file a bit so it's easier to read with less long lines.
> Fix typo in translations generation

- sources/tools/Stride.Importer.FBX/MeshConverter.cpp
Use the first material with a given name instead of failing the import with an exception.
Fixes an error I ran into importing a FBX that was created with 3ds Max 2023.
> Handle importing meshes with duplicate material names

- sources/launcher/Stride.Launcher/ViewModels/LauncherViewModel.cs
To be honest, I don't even know it should automatically close when the update process fails, it should just let the user know and still give the user the ability to launch the gamestudio ...
None reported
> [Launcher] Prevent launcher automatically closing when offline

- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityComponentSourceCodeResolver.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/ViewModels/AddAssetPolicies/AddEntityComponentFileAssetPolicy.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/ViewModels/EntityHierarchyItemViewModel.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/IEntityComponentSourceCodeResolver.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/VisualScriptEditor/VisualScriptEditorViewModel.cs
- sources/editor/Stride.Assets.Presentation/NodePresenters/Commands/AddNewScriptComponentCommand.cs
- sources/editor/Stride.Assets.Presentation/ViewModel/VisualScriptMethodViewModel.cs
- sources/editor/Stride.GameStudio/ViewModels/DebuggingViewModel.cs
Also includes a fix to avoid crashing the editor when a file which previously had a script now doesn't anymore but is still drag and dropped onto an entity.
None
> [Editor] Allow drag and drop of EntityComponent

- sources/engine/Stride.Physics/PhysicsSettings.cs
- sources/engine/Stride.Physics/Simulation.cs
This is propagated to rigidbodies if their gravity override isn't set individually. (0, -10, 0) is Bullet's default, so this should cause no change.
> Let the user set the default Bullet gravity vector in PhysicsSettings

- sources/core/Stride.Core.AssemblyProcessor/Stride.Core.AssemblyProcessor.csproj
- sources/targets/Stride.Core.targets
A fix of #1939, fixing all issues I encountered when building `Stride.Core.AssemblyProcessor` and the errors in `Stride.sln` when generating satellite assemblies (the localization assemblies).
Adding `&quot;` to the `.csproj` file commands that are failing due to spaces in the user name.
- #1939 
I am unable to contribute to the project since it can't build on my machine, which happens to have a space in the user name until issue #1939 is fixed, so I'm working through fixing it.
> [Build] Fixed an errors in the build pipeline associated with having a space in the user name

- sources/engine/Stride.Graphics/FastTextRenderer.cs
`FastTextRenderer` was overwriting the start of the vertex buffer for every string. This change advances the start of the span to prevent that.
> fix(graphics): Stop FastTextRenderer VB clobbering

- sources/engine/Stride.Assets/Stride.Assets.csproj
Update SSH.NET to the latest version https://www.nuget.org/packages/SSH.NET/2023.0.0
* Support for .NET 6, 7, and .NET Standard 2.0/2.1
* Support for RSA-SHA256/512 signature algorithms
* Support for parsing OpenSSH keys with ECDSA 256/384/521 and RSA
* Support for SHA256 and MD5 fingerprints for host key validation
* Added async support to SftpClient and SftpFileStream
* Added ISftpFile interface to SftpFile
* Removed support for old target frameworks
* Improved performance and stability
* Added the ability to set the last write and access time for Sftp files
> Update SSH.NET to 2023.0.0

- sources/engine/Stride.Audio/StreamedBufferSound.MediaCodec.cs
- sources/engine/Stride.Audio/StreamedBufferSoundSource.MediaCodec.cs
- sources/engine/Stride.Video/Android/MediaCodecExtractorBase.cs
Fixes the broken Android build. (https://github.com/stride3d/stride/pull/1788#issuecomment-1764245435)
Missed using statements in files that only gets built for Android.
> [Build] Fix Android build error

- sources/editor/Stride.Assets.Presentation/StrideDefaultAssetsPlugin.cs
- sources/editor/Stride.Editor/Thumbnails/StrideThumbnailCommand.cs
- sources/engine/Stride.Engine/Engine/AnimationComponent.cs
- sources/engine/Stride.Graphics/SDL/Window.cs
- sources/engine/Stride.Rendering/Rendering/Images/GaussianBlur/GaussianBlur.cs
- sources/engine/Stride/CompilationMode.cs
- sources/shaders/Stride.Core.Shaders/Convertor/HlslToGlslConvertor.cs
- sources/shared/ConsoleProgram.cs
Use proper XML documentation list syntax (`<list type="bullet">`) (documented [here on MSDN](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#list) for lists across the project.
This makes the IDE experience better by properly formatting lists. Also moved some of the lists from `<Summary>` to `<Remarks>` where single-line summaries are preferred.
- None
This makes the IDE experience better by properly formatting lists.
> [Docs] Use XML documentation lists

- samples/Tests/Stride.Samples.Tests.csproj
- sources/assets/Stride.Core.Assets.Quantum.Tests/Stride.Core.Assets.Quantum.Tests.csproj
- sources/assets/Stride.Core.Assets.Quantum/Stride.Core.Assets.Quantum.csproj
- sources/assets/Stride.Core.Assets.Tests/Stride.Core.Assets.Tests.csproj
- sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.csproj
- sources/editor/Stride.Core.Assets.Editor.Tests/Stride.Core.Assets.Editor.Tests.csproj
- sources/editor/Stride.Core.Assets.Editor/Stride.Core.Assets.Editor.csproj
- sources/editor/Stride.Editor/Stride.Editor.csproj
- sources/editor/Stride.GameStudio.Tests/Stride.GameStudio.Tests.csproj
- sources/editor/Stride.GameStudio/Stride.GameStudio.csproj
- sources/presentation/Stride.Core.Presentation.Dialogs/Stride.Core.Presentation.Dialogs.csproj
- sources/presentation/Stride.Core.Presentation.Graph/Stride.Core.Presentation.Graph.csproj
- sources/presentation/Stride.Core.Presentation.Quantum.Tests/Stride.Core.Presentation.Quantum.Tests.csproj
- sources/presentation/Stride.Core.Presentation.Quantum/Stride.Core.Presentation.Quantum.csproj
- sources/presentation/Stride.Core.Presentation.Tests/Stride.Core.Presentation.Tests.csproj
- sources/presentation/Stride.Core.Presentation/Stride.Core.Presentation.csproj
- sources/presentation/Stride.Core.Quantum.Tests/Stride.Core.Quantum.Tests.csproj
- sources/presentation/Stride.Core.Translation.Presentation/Stride.Core.Translation.Presentation.csproj
- sources/targets/Stride.Core.TargetFrameworks.Editor.props
- sources/tools/Stride.ConnectionRouter/Stride.ConnectionRouter.csproj
- sources/tools/Stride.Core.Translation.Extractor/Stride.Core.Translation.Extractor.csproj
- sources/tools/Stride.EffectCompilerServer/Stride.EffectCompilerServer.csproj
- sources/tools/Stride.Importer.FBX/Stride.Importer.FBX.vcxproj
- sources/tools/Stride.SamplesTestServer/Stride.SamplesTestServer.csproj
- sources/tools/Stride.TestRunner/Stride.TestRunner.csproj
Target .NET 6 (cross-platform) for editor libraries that don't have any Windows dependencies.
Introduce `StrideEditorAppTargetFramework` in `sources\targets\Stride.Core.TargetFrameworks.Editor.props` and change existing `StrideEditorTargetFramework` to target `net6.0` only.
N/A
Some editor libraries should be cross-platform (esp. `Stride.Core.Assets.Quantum`). This will allow to reuse these libraries for other tools that don't necessarily target Windows.
On the other hand, editor libraries with `Presentation` in their name have a strong dependency to either Windows Form or WPF.
> [Editor] Remove some windows dependencies in editor libraries

- sources/presentation/Stride.Core.Presentation/Controls/NumericTextBox.cs
enables numpad usage for cultures that use comma for decimals
Changes parsing and formatting culture in the NumericTextBox from InvariantCulture to CurrentCulture. Therefore decimal numbers in the property grid will be displayed using the current culture of the user and can be input using that same culture. Most importantly this enables culture settings like mine('en-AT') to use the numpad to input decimals with the comma key.
- [x ] New feature (non-breaking change which adds functionality)
> parse numbers in NumericTextBox using CurrentCulture

- sources/presentation/Stride.Core.Presentation/Controls/NumericTextBox.cs
Following #1811, remove some string allocations.
> [Presentation] Reduce allocations when parsing number in NumericTextBox

- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
Fix issue where CompilerApp is trigger multiple times (concurrently) which locks files then fails building when building for the Android project.
Due to this change https://github.com/xamarin/xamarin-android/pull/5142
we can see in this line
https://github.com/xamarin/xamarin-android/blob/95a9c28d10827c61bdf04a050b9020c11d78966d/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets#L66-L71
the MSBuild will do a nested MSBuild per RID when your own Android.csproj does not specify a `<RuntimeIdentifier>` or `<RuntimeIdentifiers>` tag.
This fix is a bit of a hack where we change our target file to detect when we're in a nested MSBuild based on them setting the property `_ComputeFilesToPublishForRuntimeIdentifiers` to true and don't …
> Fix compiling assets in Android build

- sources/launcher/Stride.Launcher/Resources/Strings.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Strings.resx
- sources/launcher/Stride.Launcher/Resources/Urls.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Urls.resx
- sources/launcher/Stride.Launcher/ViewModels/VsixVersionViewModel.cs
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml.cs
- Update launcher extension button labels
- New labels: "Visual Studio Shader {0} Extensions"
- Add link under `VisualStudioExtension` label: "An installed Visual Studio is required, which can be found here"
This commit addresses the issue of misleading launcher extension button labels, making it clearer that users are installing an extension, not the IDE itself. The new labels and added clarification help redirect users to the Visual Studio download page to avoid confusion.
Resolves: #1773
Improves Launcher UX
No Visual Studio 2019 or 2022 found (hovering over the link shows the tooltip in the bottom part of the screen with the Visual Studio download page URL):
When one or another is found:
> feat(extension): Rename launcher buttons for clarity

- sources/targets/Stride.Core.targets
Removed a double /deps/ as was in variable.
(look at the commit)
https://github.com/stride3d/stride/pull/1894
It didn't build. Now it does.
> Fix Building

- samples/Tests/Stride.Samples.Tests.csproj
- sources/assets/Stride.Core.Assets.Quantum.Tests/Stride.Core.Assets.Quantum.Tests.csproj
- sources/assets/Stride.Core.Assets.Quantum/Stride.Core.Assets.Quantum.csproj
- sources/assets/Stride.Core.Assets.Tests/Stride.Core.Assets.Tests.csproj
- sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.csproj
- sources/editor/Stride.Core.Assets.Editor.Tests/Stride.Core.Assets.Editor.Tests.csproj
- sources/editor/Stride.Core.Assets.Editor/Stride.Core.Assets.Editor.csproj
- sources/editor/Stride.Editor/Stride.Editor.csproj
- sources/editor/Stride.GameStudio.Tests/Stride.GameStudio.Tests.csproj
- sources/editor/Stride.GameStudio/Stride.GameStudio.csproj
- sources/presentation/Stride.Core.Presentation.Dialogs/Stride.Core.Presentation.Dialogs.csproj
- sources/presentation/Stride.Core.Presentation.Graph/Stride.Core.Presentation.Graph.csproj
- sources/presentation/Stride.Core.Presentation.Quantum.Tests/Stride.Core.Presentation.Quantum.Tests.csproj
- sources/presentation/Stride.Core.Presentation.Quantum/Stride.Core.Presentation.Quantum.csproj
- sources/presentation/Stride.Core.Presentation.Tests/Stride.Core.Presentation.Tests.csproj
- sources/presentation/Stride.Core.Presentation/Stride.Core.Presentation.csproj
- sources/presentation/Stride.Core.Quantum.Tests/Stride.Core.Quantum.Tests.csproj
- sources/presentation/Stride.Core.Translation.Presentation/Stride.Core.Translation.Presentation.csproj
- sources/targets/Stride.Core.TargetFrameworks.Editor.props
- sources/tools/Stride.ConnectionRouter/Stride.ConnectionRouter.csproj
- sources/tools/Stride.Core.Translation.Extractor/Stride.Core.Translation.Extractor.csproj
- sources/tools/Stride.EffectCompilerServer/Stride.EffectCompilerServer.csproj
- sources/tools/Stride.Importer.FBX/Stride.Importer.FBX.vcxproj
- sources/tools/Stride.SamplesTestServer/Stride.SamplesTestServer.csproj
- sources/tools/Stride.TestRunner/Stride.TestRunner.csproj
This reverts commit 329becbecf0c392b37feb5c8bc6007bd4ee2f567.
See #1968 and #1969
> Revert "[Editor] Remove some windows dependencies in editor libraries (#1908)"

- sources/core/Stride.Core.AssemblyProcessor/Stride.Core.AssemblyProcessor.csproj
Directory specified went a level up too far so nothing gets packed/copied to the deps folder.
Issue caused by #1894
AssemblyProcessor project does not complete its build properly due to incorrect path for dll copying and IL packing.
> [AssemblyProcessor] Fixed packing path.

- sources/core/Stride.Core.Serialization/Storage/ObjectDatabase.cs
On Linux, on creating simple empty window app by simply calling `Game.Run()`, Stride will throw `FileNotFoundException: Could not find file myproj/net6.0/data/db/index`. This bug should also appear on macOS in the same way.
I have now extended setting `isReadOnly` variable to `false` for all desktop platforms, so that the index file doesn't have to be created manually. Tested on Fedora 38, Windows 10.
> Fix failing to load data/db/index file on non-Win desktop platforms

- sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
- sources/presentation/Stride.Core.Presentation/Controls/GameEngineHost.cs
Looked into this issue for the past two weeks, and still no clue as to what the heck is going on here.
Right now the workaround is only active while right click is being held in the scene view, keeping drag and drop working as intended.
Microsoft Spy++ does show all key message as being received by the window, but the different `WndProc` and `PeekMessage` do not receive some of the key up and key down.
Also included a very small change to improve how fast the view is brought back when swapping between tabs. Detach occurs every time tabs are changed, there's no need to unparent the window at that time.
#94
> [Editor] Re-introduce workaround for missing input while navigating

- sources/shared/Stride.NuGetResolver/RestoreHelper.cs
NuGet importer allows 'non-native' files in `LockFileTargetLibrary.NativeLibraries`, however as per research https://github.com/stride3d/stride/issues/1750#issuecomment-1783774705 this leads to a subtle incorrect dll loading if multiple files with the same file name exists (eg. `freetype.dll` & `freetype.pdb`).
Wasn't sure whether a blacklist, whitelist or some priority sort would be preferred to ensure the correct file get loaded. ~I've settled on a small blacklist set but I'm open to change it to a different way.~
EDIT: Changed to allowlist logic.
Fixes #1750
> [Build] Fix native library loading picking up invalid files

- sources/core/Stride.Core/ComponentBaseExtensions.cs
- sources/core/Stride.Core/Utilities.cs
> _"3rd PR and I'm already suggesting breaking changes; I hope this isn't too intrusive, but I considered this quite high priority."_
Adding a generic scope to unscoped generic extension methods.
This means that these extension methods no longer work with `IntPtr` and `IReferencable` types, however this feature was unused internally and the engine continues to compile like normal.
Should we be interested in using a similar extension method, separate extension methods for `IReferencable` types could be created, potentially without "Dispose" in the name, and instead use the "Release" naming associated with `IReferencable` types.
- None
This was causing every object to have additional methods appearing in the IDE and on the documentation, which can be very confusing for new developers and …
> [Breaking] Scoping generic extension methods

- sources/engine/Stride.Engine/Rendering/Compositing/VRDeviceDescription.cs
- sources/engine/Stride.VirtualReality/OpenVR/OpenVR.cs
- sources/engine/Stride.VirtualReality/OpenVR/OpenVrHmd.cs
I.e.: support this slider and update at runtime
None reported
> [OpenVR] Handle custom resolution specified by the user through VR settings

- sources/assets/Stride.Core.Packages/Stride.Core.Packages.csproj
- sources/core/Stride.Core.Design/Stride.Core.Design.csproj
- sources/shared/Stride.NuGetResolver/RestoreHelper.cs
- sources/tools/Stride.NuGetLoader/Stride.NuGetLoader.csproj
- sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
Updating NuGet libraries from 6.4.0 to 6.4.2 as advised by dependabot due RCE vulnerability.
Closes #2016
Closes #2013
Closes #2012
Closes #2011
Closes #2010
Closes #2009
@Basewq I had to change your recent code as `net472` didn't have `string.Contains` which took in comparison hint.
> Update NuGet libraries to 6.4.2

- sources/engine/Stride.Assets.Models/AnimationAsset.cs
- sources/engine/Stride.Assets.Models/AnimationAssetCompiler.cs
- sources/engine/Stride.Assets.Models/AssimpAssetImporter.cs
- sources/engine/Stride.Assets.Models/FbxAssetImporter.cs
- sources/engine/Stride.Assets.Models/ImportAssimpCommand.cs
- sources/engine/Stride.Assets.Models/ImportFbxCommand.cs
- sources/engine/Stride.Assets.Models/ImportModelCommand.Animation.cs
- sources/tools/Stride.Importer.Assimp/MeshConverter.cs
- sources/tools/Stride.Importer.FBX/AnimationConverter.h
- sources/tools/Stride.Importer.FBX/MeshConverter.cpp
If multiple animation stacks are present in an fbx, let the user choose the index to import.
This only allows it to be set after the asset is initially created and imported. Also, the index is clamped so it doesn't break if you set something out of bounds.
Tested with a mixamo animation, since they set everything in the 2nd stack and a t-pose in the first.
> Let the user pick which animation stack to import in an fbx

- sources/engine/Stride.Graphics/CommandList.cs
- sources/engine/Stride.Rendering/Rendering/Images/ImageEffect.cs
- sources/engine/Stride.Rendering/Rendering/Images/ImageEffectShader.cs
Adding support for multiple viewports as well as scissors for image effects
Adding support for multiple viewports as well as scissors for image effects
#1971 
I want to apply image effects only to specific regions in a render texture as far as I understand this should be possible with scissor rectangles. However the image effect base class resets the current pipeline so setting it before the image effect is applied has no effect.
Unfortunately I can not run the tests locally at least a lot of them fail during the build but doesn't seem to be related to my changes so probably sth is missing in my setup?
> Add support for multiple viewports and scissors

- sources/tools/Stride.Importer.FBX/MeshConverter.cpp
Fix: Exception material names contains "/". #1989
Replaced "/" with "_" in GenerateMaterialNames.
https://github.com/stride3d/stride/issues/1989
> Fix: Exception material names contains "/". 

- sources/engine/Stride.Native/Stride.Native.csproj
- sources/engine/Stride.Native/StrideNative.cpp
- sources/native/Stride.Native.targets
This ensures `libstride` is built.
Without that, neither `libstrideaudio` nor `libstridenavigation` were built.
#1926
> Rollback changes to Stride.Native.targets and add StrideNative.cpp

- Directory.Packages.props
- sources/targets/Stride.Core.props
- sources/targets/Stride.Core.targets
Build system was confused with the `VersionOverride` when building from zero.
Fixes #2059
Pinging @Kryptos-FR to verify this, I know you left a comment on that particular change in #2045 but it builds fine on my end - let me know if the changes I introduced are problematic.
> [Build] Fix build following changes from #2045

- sources/tools/Stride.Importer.FBX/MeshConverter.cpp
This fixes the NaN issue in Starbreach, caused by zero-length tangents in the input model. 
Also makes sure the same issue can't happen with normals and tangent handedness.
#325
> fix(fbx import): Prevent zero-length tangents/normals (partial fix for #325)

- sources/engine/Stride.Native/Lightprobes/predicates.c
- sources/engine/Stride.Native/Stride.Native.csproj
`Stride.Rendering.Lightprobes.BowyerWatsonTetrahedralization` class is throwing an exception because it's looking for a method from `libstride` native that was accidentally removed. This PR brings back predicates.c file
> [Native] Undo lightprobe-related code removal

- sources/core/Stride.Core.Serialization/Storage/IOdbBackend.cs
- sources/core/Stride.Core.Serialization/Storage/ObjectDatabase.cs
- sources/core/Stride.Core/Collections/PoolListStruct.cs
- sources/core/Stride.Core/Threading/ConcurrentCollector.cs
- sources/core/Stride.Core/Threading/PooledAttribute.cs
I was looking through the collections and threading documentation and noticed some typos, this should fix the ones I found.
Documentation clarity is useful.
> Fix Typos in XML docs

- sources/core/Stride.Core/Threading/Dispatcher.cs
- sources/core/Stride.Core/Threading/ThreadPool.SemaphoreW.cs
- sources/core/Stride.Core/Threading/ThreadPool.cs
- sources/engine/Stride.Engine/Engine/Processors/TransformProcessor.cs
- sources/engine/Stride.Rendering/Rendering/Materials/MaterialRenderFeature.cs
- sources/engine/Stride.Rendering/Rendering/SkinningRenderFeature.cs
- sources/engine/Stride.Rendering/Rendering/TransformRenderFeature.cs
Threadpool now accepts generic work items, allowing the dispatcher and other callers to compose work items out of structures, in turn enabling the JIT to inline the composed call tree into just one function call from the thread's scope up to the actual work the caller dispatched.
Arguments can now be passed by ref to the dispatcher, which is also passed by ref to threads resolving a lot of issues that would require painful workarounds and allocations, like allowing jobs to read and write to a shared structure, interlocked operations per dispatch, and outputting from a job.
Added an interface for processing items in batches, allowing for improved throughput for jobs that have thousands of items to process.
I only changed a couple of engine calls to be batched, others may benefit in more …
> [Dispatcher] improve api, reduce overhead, improve performances for items > 1k

- sources/targets/Stride.Core.targets
This was preventing them from being included in all projects.
Fixes #2073. Partially reverts #2061.
Related to #2045, #2052, and #2055.
> [Build] Restore rules on stride analysers

- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
Update the minimum required VC++ redist to 2019.
We were still requiring VC++ 2013 when building a game from Visual Studio. However, the dependency was updated to VC++ 2019 in commits ed09ac017de04e18429ddc070d21cc3c9bdc383b and 4571b048e04d789a27989effbd5a8fdf1fe82988.
Discussion: #1498
> [Build] Require VC++ 2019 redist minimum

- samples/Audio/SimpleAudio/SimpleAudio.Game/SimpleAudio.Game.sdpkg
- samples/Games/JumpyJet/JumpyJet.Game/JumpyJet.Game.sdpkg
- samples/Games/SpaceEscape/SpaceEscape.Game/SpaceEscape.Game.sdpkg
- samples/Graphics/AnimatedModel/AnimatedModel.Game/AnimatedModel.Game.sdpkg
- samples/Graphics/CustomEffect/CustomEffect.Game/CustomEffect.Game.sdpkg
- samples/Graphics/MaterialShader/MaterialShader.Game/MaterialShader.Game.sdpkg
- samples/Graphics/SpriteFonts/SpriteFonts.Game/SpriteFonts.Game.sdpkg
- samples/Graphics/SpriteStudioDemo/SpriteStudioDemo.Game/SpriteStudioDemo.Game.sdpkg
- samples/Input/GravitySensor/GravitySensor.Game/GravitySensor.Game.sdpkg
- samples/Input/TouchInputs/TouchInputs.Game/TouchInputs.Game.sdpkg
- samples/Particles/ParticlesSample/ParticlesSample.Game/ParticlesSample.Game.sdpkg
- samples/Physics/PhysicsSample/PhysicsSample.Game/PhysicsSample.Game.sdpkg
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/FirstPersonShooter.Game.sdpkg
- samples/Templates/Packs/MaterialPackage/MaterialPackage.sdpkg
- samples/Templates/Packs/PrototypingBlocks/PrototypingBlocks.sdpkg
- samples/Templates/Packs/SamplesAssetPackage/SamplesAssetPackage.sdpkg
- samples/Templates/Packs/VFXPackage/VFXPackage.sdpkg
- samples/Templates/Packs/mannequinModel/mannequinModel.sdpkg
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/ThirdPersonPlatformer.Game.sdpkg
- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/TopDownRPG.Game.sdpkg
- samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/VRSandbox.Game.sdpkg
- samples/UI/GameMenu/GameMenu.Game/GameMenu.Game.sdpkg
- samples/UI/UIElementLink/UIElementLink.Game/UIElementLink.Game.sdpkg
- samples/UI/UIParticles/UIParticles.Game/UIParticles.Game.sdpkg
Samples don't have the resource folder configured for the Game package. This results in failure when importing an asset from file.
1. Create a new game from a sample (e.g. `FirstPersonShooter`).
2. In the asset viewer, select add an asset from file.
4. Select a file from a folder on the machine that is **not** relative to the current project (e.g. in user Documents).
5. When ask to copy the file to the default location, click "Yes"
6. Crash
```
Exception: ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
at System.Collections.Generic.List`1.get_Item(Int32 index)
at Stride.Core.Assets.Editor.ViewModel.AssetCollectionViewModel.GetAssetCopyDirectory
```
Bug fix.
> [Samples] Fix ResourceFolders reference in package file

- sources/core/Stride.Core.Yaml.Tests/Serialization/SerializationTests.cs
- sources/core/Stride.Core.Yaml/Serialization/DefaultObjectFactory.cs
- sources/core/Stride.Core.Yaml/Serialization/IObjectFactory.cs
Serialization throws with a random null ref exception when the type being deserialized does not have a parameterless constructor defined, this PR throws with a more specific exception. Users should be able to figure it out from there until @IXLLEGACYIXL work gets integrated.
^ It would seem like this would be a breaking change, but all calling logic to that method actually expected it to never return null.
> [Serialization] More useful throw when missing parameterless ctor

- sources/engine/Stride.VirtualReality/OpenXR/OpenXRException.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRHmd.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRInput.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRUtils.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXrTouchController.cs
- sources/engine/Stride.VirtualReality/VRDeviceSystem.cs
The essential part here is that `OpenXRHmd.CanInitialize` will now return false if no device is present. This ensures that the `VRDeviceSystem` sets up a dummy device which in turn prevents many parts from crashing.
To truly know whether or not an actual device is connected we first need to establish contact with the OpenXR runtime. Therefor code has been moved around a bit to be able to call various parts individually. Tested on two machines, one without any VR related things installed and another one with an actual device.
This commit also contains a bunch of code cleanups:
- Enables C# nullable feature on OpenXR files
- Adds null checks to various places
- Disposes XR API after shutting down the device
- Makes various fields and methods private
- Moves initialization code to a …
> [OpenXR] Fixes crashes when no device is present

- sources/engine/Stride.Graphics/SDL/Window.cs
I wanted an easy way to embed Stride into other UI frameworks so I decided to make a simple breakdown of https://github.com/stride3d/stride/pull/1474 without the built in demos.
This PR allows for SDL to take in a parent handle and use that for rendering.
WinForms example:
In the future I would like to use this for experimenting with Avalonia as the parent host using the NativeControlHost.
https://github.com/stride3d/stride/pull/1474
Some people have asked for an easy way to embed Stride into UI frameworks in the Discord this will allow an easy constructor to pass in a parent handle.
> added option to add a parent reference for SDL window

- samples/Audio/SimpleAudio/SimpleAudio.Game/SimpleAudio.Game.csproj
- samples/Games/JumpyJet/JumpyJet.Game/JumpyJet.Game.csproj
- samples/Games/SpaceEscape/SpaceEscape.Game/SpaceEscape.Game.csproj
- samples/Graphics/AnimatedModel/AnimatedModel.Game/AnimatedModel.Game.csproj
- samples/Graphics/CustomEffect/CustomEffect.Game/CustomEffect.Game.csproj
- samples/Graphics/MaterialShader/MaterialShader.Game/MaterialShader.Game.csproj
- samples/Graphics/SpriteFonts/SpriteFonts.Game/SpriteFonts.Game.csproj
- samples/Graphics/SpriteStudioDemo/SpriteStudioDemo.Game/SpriteStudioDemo.Game.csproj
- samples/Input/GravitySensor/GravitySensor.Game/GravitySensor.Game.csproj
- samples/Input/TouchInputs/TouchInputs.Game/TouchInputs.Game.csproj
- samples/Particles/ParticlesSample/ParticlesSample.Game/ParticlesSample.Game.csproj
- samples/Physics/PhysicsSample/PhysicsSample.Game/PhysicsSample.Game.csproj
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/FirstPersonShooter.Game.csproj
- samples/Templates/Packs/MaterialPackage/MaterialPackage.csproj
- samples/Templates/Packs/PrototypingBlocks/PrototypingBlocks.csproj
- samples/Templates/Packs/SamplesAssetPackage/SamplesAssetPackage.csproj
- samples/Templates/Packs/VFXPackage/VFXPackage.csproj
- samples/Templates/Packs/mannequinModel/mannequinModel.csproj
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/ThirdPersonPlatformer.Game.csproj
- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/TopDownRPG.Game.csproj
- samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/VRSandbox.Game.csproj
- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/CSharpBeginner.Game.csproj
- samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/05_Async/AsyncWebApi.cs
- samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/CSharpIntermediate.Game.csproj
- samples/UI/GameMenu/GameMenu.Game/GameMenu.Game.csproj
- samples/UI/UIElementLink/UIElementLink.Game/UIElementLink.Game.csproj
- samples/UI/UIParticles/UIParticles.Game/UIParticles.Game.csproj
Update all samples to use Stride 4.2.
Also removes `Newtonsoft.Json` dependency for CSharpIntermediate.
Fixes #2130
> Update samples to Stride 4.2

- sources/assets/Stride.Core.Assets.Tests/TestFileVersionManager.cs
- sources/editor/Stride.GameStudio.Tests/TestCopyPasteComponents.cs
- sources/editor/Stride.GameStudio.Tests/TestCopyPasteWithEntities.cs
Some of the tests in Stride.GameStudio.Tests must not run in parallel as they access a shared class which is not thread safe.
> [Tests] Fixes random test failures

- sources/Directory.Packages.props
- sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs
- sources/engine/Stride.Engine/Rendering/Compositing/VRRendererSettings.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRExt_FB_passthrough.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRHmd.cs
- sources/engine/Stride.VirtualReality/OpenXR/OpenXRUtils.cs
- sources/engine/Stride.VirtualReality/Stride.VirtualReality.csproj
- sources/engine/Stride.VirtualReality/VRDevice.cs
- sources/engine/Stride.VirtualReality/VRDeviceSystem.cs
Follow up on #2119 and #2121. It adds the following new public APIs:
- `VRDeviceSystem.RequestPassthrough` - needs to be set in order for the OpenXR extension to get considered.
- `VRRendererSettings.RequestPassthrough` - can be set in GameStudio and get passed to the VR device system by the `ForwardRenderer`
- `VRDevice.SupportsPassthrough` - does the device support it?
- `VRDevice.StartPassthrough` - needs to be called by user code to turn the feature on
The PR is a little bit different to the original one not exposing internal classes to the user. Not entirly sure here what is the best approach. It's only supported by OpenXR and there also by some devices, but having to cast on these types manually in Stride game code seems awkward as well.
#2119 and #2121
> [OpenXR] Adds a minimal API to request and control Passthrough

- sources/engine/Stride.Engine/Engine/AudioEmitterComponent.cs
This fixes the bug where changing the parent of an entity with an audio emitter component referencing the same sound asset multiple times would cause a crash.
Previously when the parent of such an entity was changed, there would be a crash because detach would be called on the same SoundBase object for each corresponding key in Sounds. Now, when an entry is removed from Sounds in AudioEmitterComponent, the corresponding SoundBase is only detached if there are no other keys referencing it in Sounds.
This is accomplished by maintaining a dictionary mapping each SoundBase to its set of keys in Sounds, and only detaching a SoundBase when its set of Sound keys is empty. This implementation still keeps just one AudioEmitterSoundController per SoundBase. …
> Audio emitter multiple references to same asset bugfix

- sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs
Changes asset file import overwrite dialog to show the correct file being replaced.
There is a bug in the current dialog that prompts if it is okay to overwrite the source file instead of the destination file. This PR corrects that so that it shows the correct file that is about to be replaced.
Additionally, added Path.GetFullPath to use/show the proper directory separator in an OS agnostic way as seen in other places in the project. 
No issue created, but can easily be reproduced by importing an external resource twice and choosing to use the default location.
The current dialog makes it seem as if Stride is going to modify a file outside of the project, which is not true. This should help eliminate that confusion.
> Overwrite dialog fix

- samples/Audio/SimpleAudio/SimpleAudio.Windows/SimpleAudioApp.cs
- samples/Games/JumpyJet/JumpyJet.Windows/JumpyJetApp.cs
- samples/Games/SpaceEscape/SpaceEscape.Windows/SpaceEscapeApp.cs
- samples/Graphics/AnimatedModel/AnimatedModel.Windows/AnimatedModelApp.cs
- samples/Graphics/CustomEffect/CustomEffect.Windows/CustomEffectApp.cs
- samples/Graphics/MaterialShader/MaterialShader.Windows/MaterialShaderApp.cs
- samples/Graphics/SpriteFonts/SpriteFonts.Windows/SpriteFontsApp.cs
- samples/Graphics/SpriteStudioDemo/SpriteStudioDemo.Windows/SpriteStudioDemoApp.cs
- samples/Input/GravitySensor/GravitySensor.Windows/GravitySensorApp.cs
- samples/Input/TouchInputs/TouchInputs.Windows/TouchInputsApp.cs
- samples/Particles/ParticlesSample/ParticlesSample.Windows/ParticlesSampleApp.cs
- samples/Physics/PhysicsSample/PhysicsSample.Windows/PhysicsSampleApp.cs
- samples/StrideSamples.userprefs
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Windows/FirstPersonShooterApp.cs
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Windows/ThirdPersonPlatformerApp.cs
- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Windows/TopDownRPGApp.cs
- samples/Templates/VRSandbox/VRSandbox/VRSandbox.Windows/VRSandboxApp.cs
- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Windows/CSharpBeginnerApp.cs
- samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Windows/CSharpIntermediateApp.cs
- samples/UI/GameMenu/GameMenu.Windows/GameMenuApp.cs
- samples/UI/UIElementLink/UIElementLink.Windows/UIElementLinkApp.cs
- samples/UI/UIParticles/UIParticles.Windows/UIParticlesApp.cs
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Linux/$PackageGameNameShort$App.cs.t4
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/$PackageGameNameShort$App.cs.t4
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.macOS/$PackageGameNameShort$App.cs.t4
- sources/engine/Stride.Input.Tests/AdvancedInputTest.cs
- sources/engine/Stride.Input.Tests/TestInputEvents.cs
This PR applies top-level statements to samples and template generator to generate less boilerplate code
> feat: Update samples/template to top-level statements

- sources/core/Stride.Core/build/Stride.Core.targets
Android projects in Stride 4.2.0.2122 will generate the following error when attempting to build,
`Error MSB4096 The item "obj\Debug\_Microsoft.Android.Resource.Designer.dll" in item list "ReferencePath" does not define a value for metadata "CopyLocal".`
Credit to @Basewq for the solution. Changes made to `_StrideListDepsFiles` in `Stride.Core.PostSettings.Dependencies.targets` were not replicated in `Stride.Core.targets`, the two files must be kept in sync.
https://github.com/stride3d/stride/issues/2198
> Fix for "CopyLocal" Android Bug

- sources/shaders/Stride.Core.Shaders/Convertor/HlslToGlslConvertor.cs
Vulkan uses gl_InstanceIndex and gl_VertexIndex instead of gl_InstanceId and gl_VertexId as the latter are not supported. 
https://github.com/stride3d/stride/issues/2214
gl_InstanceId and gl_VertexId are removed in https://github.com/KhronosGroup/GLSL/blob/main/extensions/khr/GL_KHR_vulkan_glsl.txt
> #2214  Vulkan uses gl_InstanceIndex and gl_VertexIndex instead of gl_InstanceId and gl_VertexId as the latter are not supported. 

- sources/engine/Stride.Engine/Engine/Game.cs
- sources/engine/Stride.Games/GameBase.cs
This PR allows to add scripts using code approach. Before, following example will throw an exception: 
```cs
using Stride.Engine;
using var game = new Game();
game.Script.Add(new FooExampleScript()); // SyncScript logic doesnt matter
/*
Unhandled exception. Stride.Core.ServiceNotFoundException: Service [IContentManager] not found
at Stride.Core.ServiceRegistryExtensions.GetSafeServiceAs[T](IServiceRegistry registry) in stride/sources/core/Stride.Core/ServiceRegistryExtensions.cs:line 23
at Stride.Engine.ScriptComponent.Initialize(IServiceRegistry registry) in stride/sources/engine/Stride.Engine/Engine/ScriptComponent.cs:line 59
at Stride.Engine.Processors.ScriptSystem.Add(ScriptComponent script) in stride/sources/engine/Stride.Engine/Engine/Processors/ScriptSystem.cs:line 164
at …
```
> fix: Add possibility to add ScriptComponent before running game

- sources/core/Stride.Core/PlatformFolders.cs
Stride applications built for Windows will crash when PublishSingleFile is set to true.
When a Stride application is launched, `Assembly.Location` is used to find the executable directory and create cache folders. This returns a null value when PublishSingleFile is true. It is instead recommended to use `AppContext.BaseDirectory` to check for the executable directory.
Additional Info: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/warnings/il3000
https://github.com/stride3d/stride/issues/2204
> fix: PublishSingleFile Launch Crash

- sources/engine/Stride.Rendering/Rendering/Shadows/ShadowMapCasterAlphaDithered.sdsl
Explicitly declare the data components used in the modulo operator & the data conversion to take place (ie. float modulo and convert to int2 data type).
See above.
Using material Transparency -> Dithered Shadows (enabled by default) on a model would trigger "implicit truncation of vector type" warning at run-time.
Feature was introduced in #1256
`streams.ShadingPosition` is `float4` data type. The original code would do a float modulo operation returning a `float4` and implicit convert to int2. This would trigger a warning due to zw components being dropped.
While the explicit `int2(...)` is probably not needed, it's better to spell it out that we're not the same data type.
Full disclosure: I did not build/run the editor. I tested the original line & modified line on a local project with …
> Fix implicit truncation of vector type shader warning

- deps/Stride.GitVersioning/Nerdbank.GitVersioning/GitExtensions.cs
- sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
- sources/core/Stride.Core/Platform.cs
PR replaces all occurrences of IsOSPlatform in favor of the more modern OperatingSystem.IsXyz available in NET5+.
None
The main motivation is less preprocessor directives and modernizing the code. In theory, methods should be faster because they are constants
> fix: Use OperatingSystem.IsXyz instead of RuntimeInformation.IsOSPlatform

- sources/tools/Stride.Importer.3D/MeshConverter.cs
Adds Noahs Fix for a regression where the AssImp library didnt import FBX embedded textures.
Tested importing FBX file with embeeded textures [here](https://www.turbosquid.com/3d-models/emily-blender-2157992)
https://github.com/stride3d/stride/issues/2213
> fix: Regression of new FBX importer on behalf of Noah

- sources/core/Stride.Core.Serialization/Serialization/Contents/ContentManager.cs
- sources/engine/Stride.Graphics/Data/TextureContentSerializer.cs
when reloading a Texture it would try to pass in a value of type Image to the content manager for an asset that of type Texture.
This adds a new method to the Content loader to check the type of an asset from the URL.
This also adds that check to the Texture class to determine how it should be treated when reloading.
https://github.com/stride3d/stride/issues/2008
https://github.com/stride3d/stride/issues/1493
Its the start of a fix for a seemingly larger problem with disposing of the graphics device when the game is in fullscreen.
> fix: Update Texture reload to prevent crash due to wrong type.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation_update.md
- .github/ISSUE_TEMPLATE/feature_request.md
GitHub issue templates improvements. Some grammar fixes and consistency fixes, including a new template for Docs and optional links to other repositories added.
GitHub issues don't have a template related to Stride engine docs referring to XML comments and any markup files updates.
N/a
Workflow improvements
> GitHub docs improvements

- sources/core/Stride.Core.Design/IO/UPath.cs
- sources/engine/Stride.Assets/Media/SoundAssetCompiler.cs
- sources/engine/Stride.Assets/Media/VideoAssetCompiler.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
- sources/engine/Stride.Assets/ToolLocator.cs
This branch is obsolete. Please merge changes (this branch contains only https://github.com/stride3d/stride/pull/2142 PR ) and delete this branch.
> fix: Adjust ToolLocator for all platforms

- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
Reverts 3a9b4d6a5a2e3ef4d51c6cc408074bd4491572c3 ("Adjust ToolLocator for all platforms") to fix a compilation error.
None.
Fixed a compilation error caused by https://github.com/stride3d/stride/pull/2142/commits/3a9b4d6a5a2e3ef4d51c6cc408074bd4491572c3 (https://github.com/stride3d/stride/pull/2142)
- [N/A] Docs change / refactoring / dependency upgrade
- [N/A] New feature (non-breaking change which adds functionality)
- [N/A] Breaking change (fix or feature that would cause existing functionality to change)
- [N/A] My change requires a change to the documentation.
- [N/A] I have added tests to cover my changes.
- [?] All new and existing tests passed. (Not sure, but it could fix "Windows D3D11" and "Tests Windows Simple").
> Revert "Add ToOSPath() for msdfgen executable" to fix compilation error

- README.md
- sources/engine/Stride.Assets.Models/Stride.Assets.Models.csproj
- sources/targets/Stride.Core.props
- sources/tools/Stride.Importer.3D/Stride.Importer.3D.csproj
- sources/tools/Stride.Importer.Common/Stride.Importer.Common.csproj
This PR enables to build following projects : 
- Stride.Assets.Models, Stride.Importer.Common, Stride.Importer.3D - these were restricted to win, because Visual c++ only available for NET FW - this is no longer the case
- Stride.Games, Stride.Input - for some reason  Stride.Core.prop adds net8.0-windows as Runtime framework but there is no windows specific code for both projects (**update**: Stride.Games is being used for GameStudio with WinForms). I restricted to windows only just in case
Make less windows restricted experience
> feat: Enable to build engine and modeling related projects on any OS

- sources/engine/Stride.Assets/Physics/ColliderShapeAssetCompiler.cs
- sources/engine/Stride.Physics/ColliderShape.cs
- sources/engine/Stride.Physics/Data/ConvexHullColliderShapeDesc.cs
Allow specification of margin for collider shapes. Shows to be useful for ConvexHull colliders. 
Margin property now able to be set on ConvexHull collider shape. Added margin getter and setting vars onto ConvexHullColliderShape as well as the viewable field in the properties box for the user to adjust. The base class ColliderShape contains where margin is defined as recommened so all collider shapes can potentially benefit from the new variable.
Link to issue: 
https://github.com/stride3d/stride/issues/1577
Link to initial discussion: 
https://github.com/stride3d/stride/discussions/1574
Originally reported as a missing field that solves an issue related to a test project not being able to adjust the corresponding collider. This margin not being able to be adjusted was causing unintended …
> [Physics] Adding margins to convex hull colliders (Issue1577)

- sources/core/Stride.Core.Tests/TestContentManager.cs
Added a new test case to cover the Reload method in ContentManager.cs.
The test was added to TestContentManager.cs and is named SimpleReloadData.
The new test verifies the following functions of the Reload method:
- Reloading an unloaded asset
- Reloading a loaded asset
- Reloading a loaded asset with a new URL to replace the asset
The Reload method in ContentManager previously had 0 test coverage, now it has 100% test coverage.
> Add Reload test to TestContentManager

- sources/core/Stride.Core.Tests/TestContentManager.cs
Tests saved object verification for use of isLoaded and TryGetAssetUrl functions.
Noticed that coverage in ContentManager required more test cases. Aimed at making a test case to increase coverage.
Added a test case named VerifyLoadedData that creates Test Classes B and A, the normal databaseProvider class as well as 2 assetManagers. We then save our B class with a urlName of "test". We then load this asset and check if the asset is properly loaded. After we run TryGetAssetUrl to lookup the B class object and verify the url output with the resulting urlName.
None found.
After some discussions in the discord, it was recommended to look in this area as a place to add more test cases for the existing test suite. Test coverage could be improved here.
> [Tests] Added new Test Case for ContentManager

- sources/engine/Stride.Assets/StrideConfig.cs
IsVSComponentAvailableAnyVersion method currently may throw exception if executed on platform other than Windows - this prevents AssetCompilerApp from running e.g. on Linux.
This PR is a part of making AssetCompiler crossplatform.
> fix: VS component check should only be performed for Win OS

- deps/Stride.GitVersioning/Nerdbank.GitVersioning/GitExtensions.cs
Those signatures don't exist in 472 and it prevents release.
#2247
> fix: [Build] Rollback OperatingSystem.IsXYZ for net472 project

- sources/assets/Stride.Core.Assets.CompilerApp/Stride.Core.Assets.CompilerApp.csproj
- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
Since CompilerApp does not contain any Windows-dependent code (at least directly), I suggest using the `dotnet Stride.Core.Assets.CompilerApp.dll` instead of running Stride.Core.Assets.CompilerApp.dll
This ensures working on any platform: 
https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent
✔️ Tested on Linux it works perfectly. Need to ensure though, there is not regression on Windows
> fix: Use CompilerApp crossplatform binary instead of exe

- sources/assets/Stride.Core.Assets/Compiler/PackageCompiler.cs
PR simplifies getting correct SdkDirectory path. The previous way of moving folders two up, used `UriBuilder`, but it threw an exception on Unix systems
This PR is a part of making AssetCompiler crossplatform.
> fix: Get correct PackageCompiler.SdkDirectory for all platforms

- sources/engine/Stride.Input/InputManager.cs
- sources/engine/Stride.Input/VirtualButton/VirtualButtonBinding.cs
- sources/engine/Stride.Input/VirtualButton/VirtualButtonConfig.cs
- sources/engine/Stride.Input/VirtualButton/VirtualButtonConfigSet.cs
Added `IsVirtualButtonPressed`/`Down`/`Released` methods to the InputManager and surrounding classes.
Added `IsVirtualButtonPressed`, `IsVirtualButtonDown` and `IsVirtualButtonReleased` methods to the `InputManager`, mirroring the `GetVirtualButton` method.  Added `IsPressed` .etc methods to `VirtualButtonBinding`, `VirtualButtonConfig` and `VirtualButtonSet`. Again, mirring the `GetValue` methods.
Renamed `GetVirtualButton` to `GetVirtualButtonValue`.
Allows pressed, down, and release states to be used with VirtualButtons from the InputManager.
Renamed  `GetVirtualButton` to `GetVirtualButtonValue` since now that there are more `VirtualButton` methods it was confusing as to what it was doing (not actually getting a VirtualButton, but reading a input value from one). And matches the …
> Added IsPressed, IsDown, & IsReleased for virtual buttons to Inputmanager

- sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
PR relates to my other recent PR (https://github.com/stride3d/stride/pull/2279). 
When now Asset.CompilerApp is a cross-platform project, the project does not generate an exe file which may cause an error when generating a nuget package, because currently `Stride.NuGetResolver.Targets.projitems` tries to copy Asset.CompilerApp.exe even though it does not exist. 
Probably when Gamestudio will be cross-platform this file should be revisited.
> fix: Adjust coping exe to nuget package lib folder

- sources/presentation/Stride.Core.Presentation.Tests/TestWindowsManager.cs
Paraphrasing Xen2 on these tests failing: 
https://teamcity.stride3d.net/buildConfiguration/Engine_Tests_WindowsSimple/25284?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildDeploymentsSection=false
> We currently run Teamcity as a service (using some system account).  Since it runs in the background without real UI, it behaves differently.
> This wasn't happening before because I was launching the teamcity agent as a specific user. I set it up in this user startup -- however it's annoying because I need to either  login the user manually since it can't start without the user being logon (I also tried auto login, but I forgot if it worked or if login to init UI was necessary?).
> On April 21st, I had …
> tests: Disable TestBlockingWindow, our Teamcity agent does not support it yet.

- sources/editor/Stride.Assets.Presentation/AssetEditors/Gizmos/ModelGizmo.cs
This PR adds bounding box gizmo for ModelComponent in editor, can be disabled like any other gizmo in scene view.
Detecting problems with mesh/models rendering can become a problematic when you do not know if bounds have correct position and extents.
Updating to 64bit coords showed problematic when converting Meshes to use Double BoundingBoxes and could not see if the correct data was there.
> Added: ModelComponent bounds gizmos

- sources/editor/Stride.Assets.Presentation/AssetEditors/ProjectWatcher.cs
The Issue was if you have the Projects
```
...\\...\\FancyGame\\FancyGame.csproj
...\\...\\FancyGame.Test\\FancyGame.Test.csproj
```
Then the first one to compare the starts with path is always the root project of the game
now if you change the file `...\\...\\FancyGame.Test\\Bob.cs` the path comparison starts with the first project and a normal StartsWith , which results in true the directory path of the file `...\\...\\FancyGame.Test` starts with the root projects directory path `...\\...\\FancyGame` so the root project gets reloaded as lowest level of the dependencies of the solution.. but that isnt true FancyGame.Test is lower and has the file but it isnt even checked as the first trigger yields
fix #2200
> fix: Repair Projectwatcher on Projects referencing each other

- sources/assets/Stride.Core.Assets/Compiler/AssetCompilerBase.cs
- sources/assets/Stride.Core.Assets/Package.cs
- sources/engine/Stride.Assets/SpriteFont/SystemFontProvider.cs
This PR refactors GetFontPath to find system fonts for Linux for Asset Compiler.
> feat: [SystemFontProvider] - Implement GetFontPath for Linux

- sources/assets/Stride.Core.Assets.CompilerApp/ProcessBuilderRemote.cs
- sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
- sources/assets/Stride.Core.Assets/Analysis/AssetCollision.cs
- sources/assets/Stride.Core.Assets/AssetRegistry.cs
- sources/buildengine/Stride.Core.BuildEngine.Common/Builder.cs
- sources/core/Stride.Core.Design/Reflection/AssemblyContainer.cs
- sources/core/Stride.Core.Yaml/Schemas/SchemaBase.cs
- sources/core/Stride.Core/Reflection/AssemblyRegistry.cs
- sources/core/Stride.Core/Serialization/DataSerializerFactory.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameNavigationMeshService.cs
- sources/engine/Stride.Input/VirtualButton/VirtualButton.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsShapesRenderingService.cs
- sources/shaders/Stride.Core.Shaders/Convertor/HlslToGlslConvertor.cs
- sources/shaders/Stride.Core.Shaders/Grammar/ShaderLanguageData.cs
- sources/tools/Stride.Importer.3D/MeshConverter.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/FreeImageWrapper.cs
Uses the new NET8 TryAdd instead of ContainsKey  guard clause + Add
It's faster as you dont need a double lookup in the dictionary
> fix: use tryadd instead of containskey guard clause

- sources/assets/Stride.Core.Assets.Tests/TestFileVersionManager.cs
- sources/assets/Stride.Core.Assets/FileVersionManager.cs
This test occasionally fails because the test runner is too slow to process some of the requests, ensured we don't have an arbitrary 500ms timeout.
https://teamcity.stride3d.net/buildConfiguration/Engine_Tests_WindowsSimple/25340?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true
> test: Fix inconsistent FileVersion test

- sources/engine/Stride.Games/Desktop/GameForm.cs
- sources/engine/Stride.Games/Desktop/GameWindowWinforms.cs
- sources/engine/Stride.Games/GameBase.cs
- sources/engine/Stride.Games/GameContext.cs
- sources/engine/Stride.Games/GameWindow.cs
- sources/engine/Stride.Games/GraphicsDeviceManager.cs
- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
- sources/engine/Stride.Graphics/ResumeManager.cs
There were 2 different issues here. One was an issue with the OnToggle event causing the switch from fullscreen to windowed to be reset to true within the same call causing an exception.
The other issue was with the exit game call trying to recreate a disposed graphics device in the GameBase class.
https://github.com/stride3d/stride/issues/2008
https://github.com/stride3d/stride/issues/1493
Window changes shouldnt cause a crash.
> fix: fullscreen and game exit windowing crashes

- sources/engine/Stride.Engine/Profiling/DebugTextSystem.cs
Fixes this exception if using `DebugText.Print(null, ...)` by adding a plain null check inside the `Print` function.
```
System.NullReferenceException
HResult=0x80004003
Message=Object reference not set to an instance of an object.
Source=Stride.Graphics
StackTrace:
at Stride.Graphics.FastTextRenderer.DrawString(GraphicsContext graphicsContext, String text, Int32 x, Int32 y)
```
None, this is just a trivial bug fix. I didn't decide to create a issue for this.
- N/A Docs change / refactoring / dependency upgrade
- N/A New feature (non-breaking change which adds functionality)
- N/A Breaking change (fix or feature that would cause existing functionality to change)
- N/A My change requires a change to the documentation.
- N/A I have added tests to cover my changes.
- N/A All new and existing …
> Fix: Fixed a NullReferenceException if printing null text

- sources/core/Stride.Core.Yaml/Schemas/SchemaBase.cs
See title, TryAdd doesn't exist on net472
#2299
> fix: Rollback one of the TryAdd introduced through #2299, VS Package is still on net472

- sources/assets/Stride.Core.Assets.Quantum.Tests/Helpers/Types.cs
- sources/assets/Stride.Core.Assets.Quantum.Tests/TestReconcileWithBase.cs
- sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
- sources/presentation/Stride.Core.Quantum/IGraphNode.cs
As per #2048, Margin is a struct `Thickness`, with itself holding float fields (`Left`, `Right`, etc).
If an object has a `Thickness` struct as a field/property and you override it in a derived asset, it is marked as overridden, however the fields of the `Thickness` are not marked overridden.
When `AssetPropertyGraph` encounters the `Thickness`'s fields it was not aware its parent has been marked overridden so it mistaken itself as not overridden and overwrites itself with the value from the base asset.
This change ensures any encountered member (field/property) that is a value type must check if it is part of another value type that may be marked overridden, and reject taking the base asset's value if this is the case.
2nd commit is to fix some typos.
Fixes #2048
> Fix UI overridden margin in derived controls being reset

- sources/core/Stride.Core.CompilerServices.Tests/AnalyzerTests/STRDIAG001_Test.cs
- sources/core/Stride.Core.CompilerServices/Analyzers/STRDIAG001InvalidDataContract.cs
file scope didnt work as its not an accessor like public internal, this is now fixed
fix #2263
> fix: strdiag001 on file scoped classes

- sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
Reverts stride3d/stride#2308
Visual Studio solutions and Stride.ConnectionRouter fail to pack the dll as they don't have the referenced dll in their output path
https://teamcity.stride3d.net/buildConfiguration/Engine_Tests_WindowsSimple/25642?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildChangesSection=true&expandBuildProblemsSection=true
Could you look into this @azeno ?
Now naively adding a condition to this `BuildOutputInPackage` works but best to check if those projects actually need this dll.
> Revert "fix: assembly load failure when building Stride based project on clean machine"

- sources/core/Stride.Core/Collections/FastList.cs
Added info on the deprecation of FasLists list. Better alternatives have been made easier since .NET 5+ to make the base List class twice as fast.
https://github.com/stride3d/stride/discussions/2298
> refactor: Make FastList Obsolete

- sources/assets/Stride.Core.Assets/PackageSessionPublicHelper.cs
- sources/editor/Stride.GameStudio/Program.cs
Updated error message to not confuse new users.
Should probably make a central var or something to make this better since there are a few places where .NET X is hard coded.
> .NET 6 reference missed

- sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
This is the second attempt to get a grip on #2232. My previous attempt caused build errors in other projects (like Stride.ConnectionRouter) not having `System.Security.Cryptography.Pkcs.dll` in their output folder. Whether or not that particular dll is in the build output folder seems to depend on the target framework of the project including Stride.NuGetResolver.
I've added a check, the solution seems to build fine now (seems I was a bit sloppy in this regard in my previous attempt, sorry for that).
#2232
> Fixes assembly load failure when building Stride based project on clean machine (2. attempt)

- sources/engine/Stride.Assets.Models/ImportModelCommand.Model.cs
- sources/engine/Stride.Assets.Models/ImportThreeDCommand.cs
- sources/engine/Stride.Assets.Models/ModelAssetCompiler.cs
- sources/engine/Stride.Rendering/Rendering/Skinning/TransformationSkinning.sdsl
- sources/tools/Stride.Importer.3D/MeshConverter.cs
Primary aim is to fix `TransformationSkinning.sdsl` shader where skinning wasn't working on Android, due to mismatched data type being passed from app to shader. Due to dropping OpenGL ES 2, blend indices can now just behave like non-ES 2 versions (ie. just use `uint` data type, instead of using `float`).
Fixes #2284 where the background info/problem arose from.
Here's my understanding of the original intention/code:
OpenGL ES 2 did not support passing `int`/`uint` data types, so needed a workaround to use `float` instead.
https://github.com/stride3d/stride/blob/1fc0d5137750a8c3d8acd5f89e3b63c75b6bea7f/sources/engine/Stride.Rendering/Rendering/Skinning/TransformationSkinning.sdsl#L28-L33
As seen in this code (and the comments I removed from the `TransformationSkinning.sdsl` file), the …
> Remove signed blend indices due to dropping OpenGL ES 2 support

- sources/presentation/Stride.Core.Quantum/NodeAccessor.cs
Fixed an error when duplicating an Entity with a not null `List<T>` variable crashes the editor. This happen when T is something referenceable in a scene like Entities or Components.
When trying to cast a Node as IMemberNode, it resulted in a null and the editor crashing, this PR just prevent to call Update on a null.
#2255
> [GameStudio] Prevents a null IMemberNode to update

- sources/editor/Stride.Assets.Presentation/SceneEditor/PackageSceneSettings.cs
Following #2294 - No need to have them visible by default I would think, checking with @kristian15959 just in case ?
> style: Set initial visibility for ModelComponent gizmos off

- sources/engine/Stride.Engine.Tests/TestEntityManager.cs
- sources/engine/Stride.Engine/Engine/EntityManager.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/IComponent.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/IDrawProcessor.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/IProcessorBase.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/IUpdateProcessor.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/ProcessorManager.cs
This PR enables building of processors from interfaces, enabling unrelated types to be processed by the same system. 
The current processor implementation force users to derive from the same root type to build their logic, this does not work well with the fact that we have different 'Script' variant which have all their specific use. It becomes a composition issue when more abstract concepts, like event functions, are introduced. 
A good example of that is when components should manipulate physics object, it is preferable to do so in lockstep with the physics engine's tick. But those component may also require an async or update loop to process inputs. We would be forced to either create another new 'script' type which users have to derive from which would split their logic between two …
> feat: FlexibleProcessing as alternative to EntityComponentProcessor for lightweight, abstract and typesafe processing in idiomatic c#

- sources/editor/Stride.Core.Assets.Editor/Components/Properties/PackageSettingsWrapper.cs
`[DataMember]` makes the user settings appear again, probably was caused by #1875
Fixes #2347
> [Editor] Fix displaying & editing project User Settings

- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
Fixes missing `dotnet` command when executing some Targets
https://github.com/stride3d/stride/issues/2358
> fix: Update Stride.Core.Assets.CompilerApp.targets file

- sources/tests/tools/Stride.TextureConverter.Tests/Stride.TextureConverter.Tests.csproj
- sources/tools/Stride.TextureConverter/Backend/Wrappers/DxtNetWrapper.cs
This PR fixes TextureConverter tests that previously couldn't even be run. In addition, I fixed a bug related to loading dds on Linux I detected by running unit tests
> fix: Enable to run broken TextureConverter Tests

- sources/core/Stride.Core.Mathematics/GuillotinePacker.cs
- Replace link in `GuillotinePacker` documentation
While browsing the `Core.Mathematics` namespace, I noticed that the link to http://clb.demon.fi/files/RectangleBinPack.pdf seems to have rotted. After a bit of googling, I think I was able to find the author's github and a link to the PDF there.
None, just a documentation change.
> Update guillotine packer documentation link

- sources/core/Stride.Core.Design/Settings/AppSettingsProvider.cs
- sources/core/Stride.Core/PlatformFolders.cs
- sources/engine/Stride.Engine/Engine/Game.cs
- sources/engine/Stride.Games/Desktop/GamePlatformDesktop.cs
- sources/engine/Stride.Games/GameContext.cs
Use `PlatformFolders.ApplicationExecutablePath` instead of `Assembly.GetEntryAssembly().Location`
https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility
Under 'API incompatibility' `Assembly.Location` is not available with single file deployment.
https://learn.microsoft.com/en-us/dotnet/api/system.environment.processpath?view=net-8.0
`Environment.ProcessPath` can be used as a fallback, but do note that even that can return null.
Fixes #2304 where Icon is set via `GameContext.ProductLocation`
Also fixes the super secret LeftCtrl + C+ F1 screenshot command in PublishSingleFile.
> Fix getting app exe path when using PublishSingleFile

- sources/editor/Stride.Assets.Presentation/EffectCompilerServerSession.cs
Only one fix:
1. When checking for effect log changes, `EffectCompilerServerSession` should try to find any existing EffectCompilerLog asset in the active project (or its referenced projects, eg. the Game project) if the current package it's looking at does not contain one, and reuse that.
This is because there can only be one EffectCompilerLog asset (see #2361 for the related problem)
Related to #301, but this only fixes it so it reuses the existing EffectCompilerLog asset if it exists, however if none exists it will generate the log asset in the active project's asset folder.
> fix: importing effects to the EffectCompileLog 

- sources/Directory.Packages.props
Successor to #2281 
Must wait until pull at https://github.com/stride3d/SharpFont/pull/1 is merged and its nuget package has been updated to 1.0.1.
My understanding of Stride's build of SharpFont:
* vonderborch's repo, aka [SharpFont.NetStandard](https://github.com/vonderborch/SharpFont) did not contain any major changes compared to Robmaister's repo- it mainly moved files around (no code changes) and the single code change involved loading/switching 32bit/64bit dll, which Stride already does (I think). So the above pull only merged and modified from the latest of Robmaister's repo.
* Stride does not use `freetype6` as provided in Robmaister's branch which is only on v2.6 - Stride uses v2.6.3 https://github.com/stride3d/freetype/tree/2.6.3 (and is named `freetype`), as per this …
> [Font] Update SharpFont library for additional fixes

- sources/engine/Stride.Graphics/GeometricPrimitives/GeometricPrimitive.Cylinder.cs
- sources/engine/Stride.Graphics/GeometricPrimitives/GeometricPrimitive.Torus.cs
> Update : geometric primitive.cylinder to avoid GC

- sources/core/Stride.Core.IO/DirectoryWatcher.Desktop.cs
For some reason Path is transformed to lowercase, but on Linux distros it causes a runtime error - "The directory name .... does not exist" during game runtime.
> fix: [DirectoryWatcher] - Folders are case sensitive on Linux

- sources/launcher/Stride.Launcher/Resources/Urls.Designer.cs
- sources/launcher/Stride.Launcher/Resources/Urls.resx
- sources/launcher/Stride.Launcher/Resources/facebook_24.png
- sources/launcher/Stride.Launcher/Resources/opencollective-24.png
- sources/launcher/Stride.Launcher/Resources/opencollective_24.png
- sources/launcher/Stride.Launcher/Resources/reddit_24.png
- sources/launcher/Stride.Launcher/Resources/twitch.png
- sources/launcher/Stride.Launcher/Resources/twitch_24.png
- sources/launcher/Stride.Launcher/Resources/twitter_24.png
- sources/launcher/Stride.Launcher/Resources/twitter_bird_24.png
- sources/launcher/Stride.Launcher/Resources/xtwitter_24.png
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml
Replace old brand icons for new brand icons
Any, just some icons change
> Update launcher brand icons

- sources/core/Stride.Core.MicroThreading/ChannelMicroThreadAwaiter.cs
When >= 4096 awaiters are pooled, more awaiters are also added to the pool without being reset. This has the effect of possibly causing some `await Script.NextFrame()` points to continue immediately. This PR fixes that issue.
n/a
> Fix: ChannelMicroThreadAwaiter pooling bug

- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
Fix horizontal/vertical alignment of glyphs from generated SDF bitmaps.
According to [the original author](https://github.com/Chlumsky/msdfgen/issues/108#issuecomment-657286643) `-autoframe` more meant for previewing rather than actual usage due to it centering the glyph to fit exactly centered on the bitmap rather than how it should be fitted on the bitmap (ie. snapped to the top-right corner).
Other change is debug build, dump the SDF bitmaps in into a sub-folder in the temp directory instead of straight into the temp directory so it's easier to delete. This does not affect the release build.
#2172 Only fixes the vertical alignment, not the kerning issue (which I have no clue about).
Merely an FYI, but this is the original logic for autoframe: …
> [Font] Fix glyph bitmap alignment from SDF fonts

- samples/Games/JumpyJet/Assets/Shared/Font.sdfnt
- samples/Games/SpaceEscape/Assets/Shared/Font.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/AliasedFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/AntialiasedFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/BoldFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/ClearTypeFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/DynamicFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/ItalicFont.sdfnt
- samples/Graphics/SpriteFonts/Assets/Shared/StaticFont.sdfnt
- samples/Input/GravitySensor/Assets/Shared/SpriteFont.sdfnt
- sources/engine/Stride.Assets/SpriteFont/SpriteFontAssetFactories.cs
- sources/engine/Stride.Engine.Tests/GameAssets/Font.sdfnt
- sources/engine/Stride.Engine/AssetPackage/Assets/Shared/StrideDefaultFont.sdfnt
My PR tries to hide default default font name for SystemFontProvider. I also changed default font name from `Courier New` to `Arial` for sake of consistency - (Almost) all samples are using `Arial` font anyway.
In addition, `Arial` is a sans-serif font - these types of fonts are more popular and easier to read.
> feat: Hide default font name for SystemFontProvider, change default font

- sources/engine/Stride.Assets/SpriteFont/SystemFontProvider.cs
This PR includes a fix for searching the font path on Linux. Previously when a font did not exist CompilerApp ignored the search for a default font, because of error.
> fix: Change the error to a warning when searching for font path

- sources/engine/Stride.Assets/Materials/ComputeShaderClassHelper.cs
- sources/engine/Stride.Rendering/Rendering/Materials/ComputeColors/ComputeColorParameter.cs
- sources/engine/Stride.Rendering/Rendering/Materials/ComputeColors/ComputeShaderClassBase.cs
Bug in editor where declaring a shader, eg.
```
shader MyShader<bool ShaderArg>
{
}
```
won't show the bool argument in the editor when used as a material shader, and you won't be able to build the shader due to the missing parameter.
This fix exposes the bool argument to the editor and allows it to save/load properly.
Also added a separate commit to simplify the type checking.
> Fix shader bool generics to appear in the editor

- sources/assets/Stride.Core.Assets.CompilerApp/Stride.Core.Assets.CompilerApp.csproj
- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
May be controversial to bring the windows specific CompilerApp back.
Pinging @Jklawreszuk & @Kryptos-FR since they've spent a lot of time on the cross-platform transition side of things.
This does not remove the cross-platform version, but rather includes the Windows specific version and use that over the cross-platform version.
Fixes #2244
The problem is referencing any Stride libraries that touch WPF code, the ModuleInitializer will try to load the WPF framework if it's not loaded, however WPF is Windows only, so it can't be loaded in any way except by having the Windows specific version.
> Add back Windows specific CompilerApp to fix libraries with WPF references

- sources/engine/Stride.Physics/Elements/CharacterComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
Having no Physics shapes on character component causes unhandled exceptions when user tries to use physics methods on corresponding character component. (Note: Originally showed as a bug)
Originally threw: Unhandled Exception: System.InvalidOperationException: Attempted to call a Physics function that is available only when the Entity has been already added to the Scene.
Now gives warning from logger when a character component has no shapes and shows error via logger when physics method is ran on character component (Much earlier than original exception). Also gives good logging info to user as to where the physics method was called for tracing purposes.
Issue: https://github.com/stride3d/stride/issues/760
> feat: No Physics Shapes On The CharacterComponent Causes Unhandled Exception 

- sources/engine/Stride.Physics.Tests/ColliderShapesTest.cs
- sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
When using `GetOrCreate<T>` to create physics components such as `Rigidbody` component, certain properties such as `ColliderShape` are not properly setup. Setting other properties afterwards result in a no-op.
Added a `ReAttach` method to `PhysicsComponent` that can run and reconfigure those properties when `ColliderShapes` is added. Also added a Test case to showcase. 
Issue: https://github.com/stride3d/stride/issues/1504
> fix: PhysicsComponent created with GetOrCreate<T> is unusable

- sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
Fix restoring NuGet packages in the editor
Finer details regarding the TFM are explained in the comments of #2426
When using shorthand TFM (eg. `net8.0-windows`), MSBuild sets the default platform version in `TargetPlatformVersion` when not explicitly set and the expanded canonical version (eg. `net8.0-windows7.0`) is passed to packaging to NuGet.
NuGet resolver requires the canonical form of the target framework moniker (TFM) when the OS/platform has been specified
ie. [framework]-[platform][platform_version]
This fix ensures the platform version is passed when applicable.
Fixes #2426
Caused by #2205
> Fix restoring NuGet packages in the editor

- sources/tools/Stride.TextureConverter.Wrappers/DxtWrapper/dxt_wrapper.cpp
- sources/tools/Stride.TextureConverter/Backend/TexLibraries/DxtTexLib.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/DxtNetWrapper.cs
Partial revert of #2314 and #2338 for Windows to allow loading non-32-bit pixel formats.
Note that (as far as I'm aware) DxtWrapper.dll for Windows was not rebuilt with the 'dxtLoadWICFile' function removed, so it also means it does not need to be rebuilt for this revert.
Problem raised in #2376.
Technically it only fixes it for Windows, but the issue will persist for the non-Windows editor (which doesn't exist yet) and will require implementation/alternative solution if the intention is to remove it again.
> fix: Restore LoadWICFile for Windows due to incomplete cross-platform functionality

- sources/engine/Stride.Physics/Elements/CharacterComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
Assigning a new `ColliderShape` into `CharacterComponent` and running `ComposeShape()` causes a UAF related exception to be thrown. Related to an issue with the `KinematicCharacter` reference inside of the `discreteDynamicWorld` in the `Simulation` object. 
Solution would be to add additional setup to a overridden `ComposeShape()` method inside CharacterComponent. This setup would include the complete removal, reconstruction and reintegration of the KinematicCharacterController to the Simulation. Also added an additional function to try and maintain various physics properties onto the `KinematicCharacter` such as Gravity, Fallspeed, etc. 
https://github.com/stride3d/stride/issues/2005
> bug: Unable to Change CharacterComponent's collider shape properties without causing crash

- sources/tools/Stride.Importer.3D/Material/Materials.cs
- sources/tools/Stride.Importer.3D/MeshConverter.cs
Documentation on assimp texture behavior is described here:
https://assimp-docs.readthedocs.io/en/latest/API/API-Documentation.html#_CPPv49aiTexture
(Search `struct aiTexture` if the link doesn't jump to the correct section)
glTF materials referencing embedded textures may be denoted by `*` + index of the texture array, and the full file name must be determined by examining the Texture data.
Apparently it is possible to have uncompressed textures in the file (ie. the 'raw' texture is directly embedded).
I have opted to output a log error rather than implement it.
Used the model from #2406 (this pull does *not* fix the animation issue in that link)
> fix: extracting embedded texture files for materials from glTF file

- sources/tools/Stride.Importer.3D/MeshConverter.cs
See model in #2406 (be aware the second animation seems to play strangely, but this is consistent with how it plays in Blender 3.6 - it didn't import properly in a higher version of Blender)
Assimp has a generic 'Node' hierarchy structure and a 'Bone' list (per mesh).
Each Bone has a corresponding 'Node', however the link between the two is only done by name.
Unfortunately, this is a problem when a model has duplicate names, eg. the model's armature and bone, and Stride will more than likely link the 'Bone' to the non-Bone node.
This fix attempts to make an educated guess whenever duplicated names occurs.
If it fails to properly detect what should be linked, then it'll output a warning/error telling the end-user to make the name unique.
While …
>  Fix Assimp skeleton/animation importer for models with duplicate node names

- sources/engine/Stride.Graphics/SpriteBatch.cs
As per https://github.com/stride3d/stride/blob/fe4aa87cdac41ca7ec45cd26660fd5d8c9632944/sources/engine/Stride.Native/Sprite/SpriteBatchNative.c#L24
the original code assigned SinCos to (Y, X), but the C# code changed to (X, Y)
This changes it back to restore the original behavior.
Fixes #2456 
Caused by #1896
> fix: SpriteBatch rotation logic to original code

- sources/core/Stride.Core.AssemblyProcessor/SerializationProcessor.cs
- sources/core/Stride.Core.AssemblyProcessor/Serializers/CecilSerializerContext.cs
The binary serializer can lose serialized data when round-tripped with a specific inheritance setup;
```cs
[DataContract]
public class D : C<AnyType>{ public bool bill; }
public class C<T> : B<T>{}
public class B<T> : A{}
[DataContract(Inherited = true)]
public class A : EntityComponent{}
```
The following logic fails to capture `B<T>`
https://github.com/stride3d/stride/blob/37bbf0c85262711f56786319effab2621479bab9/sources/core/Stride.Core.AssemblyProcessor/Serializers/CecilSerializerContext.cs#L198-L204
Which in turn means that all serialized data contained in its base types would be discarded, most obvious with the component Id inherited from `EntityComponent`, which right now shows up as a new Id on every save caused by the asset collision Id de-duplication using binary serialization …
> fix: Cecil serialization inheritance cutoff with complex base types

- sources/engine/Stride.Physics.Tests/ColliderShapesTest.cs
- sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
Test cases inside `Stride.Physics.Tests.SendCollisionEndedWhenEntityIsRemovedTest` suite started failing after introduction of PR https://github.com/stride3d/stride/pull/2422. Further investigation showed that while entities are being setup inside `Attach`, the `ReAttach` method could potentially run and cause duplicate entities to be added to simulation, resulting in possible null ref exceptions and in this case, test failures.
Added flag `attachInProgress` that only allows the ReAttach method to run when Entity has fully competed all `Attach` behaviors. Still maintains same behavior that was tested and verified in `Stride.Physics.Tests.ColliderShapesTest.VerifyColliderShapeSetup`.
Original Issue: https://github.com/stride3d/stride/issues/1504
Merged PR: …
> fix: Found and fixed bug pertaining to ReAttach method for PR #2422

- sources/core/Stride.Core.Mathematics/MathUtil.cs
- sources/engine/Stride.Rendering/Rendering/Utils/Math.sdsl
Add `ExpDecay` to both `MathUtil` and SDSL as an alternative to damping using linear interpolation.
Closes #2301 .
- [N/A] Docs change / refactoring / dependency upgrade
- [N/A] Bug fix (non-breaking change which fixes an issue)
- [N/A] Breaking change (fix or feature that would cause existing functionality to change)
- [N/A] My change requires a change to the documentation.
- [N/A] I have added tests to cover my changes.
- [N/A] All new and existing tests passed.
> feat: [Math] - Exponential damping

- sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs
- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
Ignore reattach call if the component hasn't been attached yet.
This situation occurs when the editor gizmo wants to show the physics shape.
Not sure if null checking in both places is overkill or not, this shouldn't be a frequent call so any performance hit should be minimal. Maybe change to `Debug.Assert` in `ReAttach()`?
I've tested this opening the editor and at run-time and did not encounter any issue, however I did not test whatever the original implementation was for.
Also I couldn't build/run the tests (for an unrelated issue), so someone do a quick run to check this didn't break an existing test.
Fixes #2464
Caused by #2422 and #2439
> Fix PhysicsComponent reattach logic crashing the editor

- sources/tools/Stride.Importer.3D/MeshConverter.cs
Some projects fail to build due to a possible regression in the AssImp importer from FBX. The failure is due to FBX files being given virtual nodes that describe translation, rotation and scale in the form of `$AssimpFbx$` nodes. This changes the error to be a warning ~as it seems to be importing correctly and animating correctly.~
These were 3 previously problematic models that seem to be working fine:
https://github.com/stride3d/stride/issues/2459 - technically a fix for the reported issue but not for the actual cause.
> changed AssImp error to warning

- build/Stride.Build.props
- sources/targets/Stride.Core.props
My PR corrects graphics API detection for Linux. The main reason was to improve the graphics detection in code editors like VSCode or Rider : instead of OpenGL as the default api, Direct3D is always selected  which is not correct.
> feat: [Build] - Better Platform detection for Linux

- sources/engine/Stride.Rendering/Rendering/MaterialPass.cs
- sources/engine/Stride.Rendering/Rendering/Materials/MaterialAttributes.cs
- sources/engine/Stride.Rendering/Rendering/Materials/MaterialRenderFeature.cs
- sources/engine/Stride.Rendering/Rendering/MeshPipelineProcessor.cs
Provides the ability for users to set custom depth testing functions per material for special effects
Here, a sphere clipped into another sphere by using the `Greater` depth function
This is often used for bullet impacts, selections in RTS, previews in level editors ...
None afaict.
> feat: Custom Depth Test Function for Materials

- sources/engine/Stride.Graphics/Direct3D/CommandList.Direct3D.cs
Small fix in CommandList.Direct3D.cs
CommandList.DrawInstanced(Buffer argumentsBuffer, int alignedByteOffsetForArgs = 0) call DrawIndexedInstancedIndirect instead of DrawInstancedIndirect
```
public void DrawInstanced(Buffer argumentsBuffer, int alignedByteOffsetForArgs = 0)
{
if (argumentsBuffer == null) throw new ArgumentNullException("argumentsBuffer");
PrepareDraw();
// was DrawIndexedInstancedIndirect( ... ) but should be DrawInstancedIndirect( ... )
NativeDeviceContext.DrawInstancedIndirect(argumentsBuffer.NativeBuffer, alignedByteOffsetForArgs);
GraphicsDevice.FrameDrawCalls++;
}
```
> Small fix in CommandList.Direct3D.cs

- sources/engine/Stride.Assets/Skyboxes/SkyboxAssetCompiler.cs
- sources/engine/Stride.Graphics/OpenGL/GraphicsDevice.OpenGL.cs
- sources/engine/Stride.Graphics/OpenGL/Texture.OpenGL.cs
- sources/engine/Stride.Graphics/Texture.cs
- sources/engine/Stride.Rendering/Rendering/ComputeEffect/GGXPrefiltering/Hammersley.sdsl
- sources/engine/Stride.Rendering/Rendering/ComputeEffect/GGXPrefiltering/RadiancePrefilteringGGXNoCompute.cs
This PR implements / fixes compiling Skybox Asset for OpenGL. I also made few related refactoring changes
_Example of a game using Skybox : FirstPersonShooter_
https://github.com/stride3d/stride/issues/2496
> feat: Enable to build SkyBoxAsset using OpenGL

- sources/engine/Stride.Graphics/OpenGL/CommandList.OpenGL.cs
This PR fixes incorrect buffer clearing for OpenGL when mapping a resource. It turns out that IntPtr.Zero was treated as some kind of value while this was not the author's intention. I also did a small refactoring
- https://github.com/stride3d/stride/issues/2189
- https://github.com/stride3d/stride/issues/2079
> fix: Resolve crashing issue for OpenGL UIPage (#2189)

- sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameCameraPreviewService.cs
- sources/editor/Stride.Assets.Presentation/Thumbnails/AnimationThumbnailCompiler.cs
- sources/editor/Stride.Editor/Thumbnails/ThumbnailBuildHelper.cs
- sources/engine/Stride.Graphics/Buffer.Constant.cs
- sources/engine/Stride.Graphics/Buffer.Index.cs
- sources/engine/Stride.Graphics/Buffer.Raw.cs
- sources/engine/Stride.Graphics/Buffer.Structured.cs
- sources/engine/Stride.Graphics/Buffer.Typed.cs
- sources/engine/Stride.Graphics/Buffer.Vertex.cs
- sources/engine/Stride.Graphics/Buffer.cs
- sources/engine/Stride.Graphics/FastTextRenderer.cs
- sources/engine/Stride.Graphics/Texture.cs
- sources/engine/Stride.Physics/Shapes/StaticMeshColliderShape.cs
- sources/engine/Stride.Rendering/Rendering/InstancingRenderFeature.cs
- sources/engine/Stride.Video/VideoTexture.cs
- sources/engine/Stride/Graphics/DataPointer.cs
- sources/engine/Stride/Graphics/Image.cs
DataPointer are just the more rigid and error prone version of what Span provides, marked that type as deprecated, created new signatures providing support for spans instead and moved over the engine calls to that one instead.
One thing I tried to tackle is replacing `T[]` with `Span<T>` to reduce the ridiculous amount of signatures Buffer and its variants already hosts, but arrays do not implicitly convert to spans when the function they are passed into is generic. Replacing all cases of `T[]` with `Span<T>` would fail to find the method. We'll have to mark those methods as obsolete as well if we want to clean that up.
None
> feat: Deprecate DataPointer in favor of Span

- sources/core/Stride.Core.Mathematics/Matrix.cs
- sources/core/Stride.Core.Mathematics/Quaternion.cs
- sources/core/Stride.Core.Mathematics/Vector2.cs
- sources/core/Stride.Core.Mathematics/Vector3.cs
- sources/core/Stride.Core.Mathematics/Vector4.cs
- sources/engine/Stride.Engine.Tests/TestTransformComponent.cs
- sources/engine/Stride.Engine/Engine/EntityTransformExtensions.cs
Introduce `TransformComponent.SetWorld` to set the position and rotation of a transform component to world space values. We previously could retrieve the world position from them, but we did not have any extensions to set it.
Introduce `EqualsStrict` to compare vector and quaternion for equality using the same rules as floating point numbers.
Fix a couple of types in matrix, vector and quaternion.cs
> feat: TransformComponent.SetWorld, strict equality and fix misc. typos

- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/$ProjectName$.csproj.t4
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/ProjectExecutable.Windows.ttproj
- sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Windows/app.manifest.t4
- sources/engine/Stride.Graphics/Direct3D/GraphicsOutput.Direct3D.cs
- sources/engine/Stride.Graphics/GraphicsOutput.cs
Fix for the bug https://github.com/stride3d/stride/issues/2492.
References:
- https://www.gamedev.net/forums/topic/689459-sharpdx-dxgi-trying-to-get-the-current-display-mode/
- https://github.com/MonoGame/MonoGame/pull/5096
> Fixed getting actual bounds and refresh rate of the output (monitor/display) from GraphicsOutput.CurrentDisplayMode when using Direct3D

- sources/editor/Stride.Assets.Presentation/StrideDefaultAssetsPlugin.cs
User-defined gizmos did not load in when reloading the assembly, whether they were part of the previous version or not.
Same deal for `DisplayAttribute` stuff, also cleaned up registered types when assemblies are unloaded, and replaced the unreadable linq into someting more readable
None afaict.
> fix: Add in gizmos on assembly load

- sources/shared/Stride.NuGetResolver/NuGetAssemblyResolver.cs
Getting LocalAppData path shouldn't be hardcoded if we want more universal code for all platforms. It should be received from Environment.GetFolderPath with Environment.SpecialFolder enum which contains common paths for OS folders.
> feat: Get LocalAppData path from Environment.SpecialFolder enum

- sources/Directory.Packages.props
Our current NuGet.* packages version 6.8.0 have depedency on vulnerable `NuGet.Protocol` 6.8.0 package.
45 occurences in the Visual Studio Build Output window.
Warnings when the **Solution.sln** is built.
```
D:\Projects\GitHub\stride\sources\editor\Stride.GameStudio\Stride.GameStudio.csproj : 
warning NU1904: Package 'NuGet.Packaging' 6.8.0 has a known critical severity vulnerability,
https://github.com/advisories/GHSA-68w7-72jg-6qpp
```
> [Build] Update NuGet.* packages to version 6.12.1

- sources/engine/Stride.Engine/Engine/EntityManager.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/IProcessorBase.cs
- sources/engine/Stride.Engine/Engine/FlexibleProcessing/ProcessorManager.cs
> feat: ExecutionMode control for Flexible Processing

- sources/engine/Stride.UI/KeyEventArgs.cs
- sources/engine/Stride.UI/UIElement.Events.cs
Made KeyPress Events public on UI Elements to allow for custom UI Hotkeys
https://github.com/stride3d/stride/issues/2515
This is my first PR, let me know if I am missing something.
All the UI tests passed, I am still working on getting my environment setup for other tests.
> feat: Made UIElement Key Events public

- samples/Templates/Packs/MaterialPackage/Resources/Models/MaterialModel.fbx
**MaterialModel.fbx** in **Material Package** still had the Xenko logo. I replaced the file for @CodingSea 's slightly changed model that has Stride's logo.
Simple change, but it helps with the engine cohesion. 
#1505
> fix: Replace Xenko logo with Stride logo in MaterialModel.fbx

- sources/Directory.Packages.props
- Updated the ServiceWire package version in Directory.Packages.props from 5.5.4 to 5.6.0.
The new package resolves System.Text.Json vulnerabilities, and some bug fixes, summary:
https://github.com/tylerjensen/ServiceWire#namedpipeserverstreamfactory-and-other-improvements-560
1. Contributed fix where accepting TCP clients synchronously may block new clients from being accepted until the terminating request is received on the synchronous client.
1. Contributed NamedPipeServerStreamFactory to allow greater level of permissions control in using named pipes.
1. Introducted injectable ILog and IStats across channels and clients with default NullLogger and NullStats, making InjectLoggerStats obsolete.
1. Code improvements for code consistency and eliminating outdated frameworks from tests and …
> chore: Update ServiceWire package to version 5.6.0

- sources/engine/Stride.Assets.Tests/TestMemberRequiredComponentChecks.cs
- sources/engine/Stride.Assets/Entities/ComponentChecks/RequiredMembersCheck.cs
Now that `required` is an actual keyword, we can use it to notify users when some of their components have missing references, just like our `MemberRequiredAttribute`.
`required` is an essential part of projects using the nullable reference feature, using it in stride to benefit from null-state analysis from both the compiler and our asset builder requires writing a fairly redundant property definition:
```cs
[MemberRequired] public required MyRef myRef { get; set; }
```
When the intent of the attribute is already made clear through the use of the `required` keyword.
```cs
public required MyRef myRef { get; set; }
```
None
Hopefully you have some time to get back to me about this one @manio143 , would like to hear your thoughts given that this is your feature.
> feat: Process required keyword like MemberRequiredAttribute

- sources/core/Stride.Core.Design/Windows/FileLock.cs
- sources/core/Stride.Core.IO/NativeLockFile.cs
- sources/core/Stride.Core.Serialization/IO/Store.cs
Stride should avoid direct references to any OS if possible. This PR Hides Lock/UnLockEx methods under already made Lock/Unlock methods that wrap them.
None, but this relates to Stride.Launcher which is using `FileLock.Wait` method, so this provides cross-platform experience
> feat: LockFileEx/UnLockFileEx methods shouldn't be called explicitly

- sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
- sources/engine/Stride.Input/Windows/MouseWinforms.cs
On deselecting Edit Text, via  `myEditTextElement.IsSelectionActive = false;`, focus was lost which triggered two behaviors which both triggered button releases. One mouse and keyboard and the other just the mouse release. This PR affects the following inputs: STRIDE_UI_WINFORMS and STRIDE_UI_WPF.
I have checked the box that this maybe a breaking change due to the following comment in the removed code.
`// Release keys/buttons when control focus is lost (this prevents some keys getting stuck when a focus loss happens when moving the camera)`
I tried to test moving the camera around while typing in an EditText, but was not able to reproduce a key or mouse button press being stuck.
My reasoning for a possibly breaking change is that due to 
- The lack of test coverage or documentation for …
> fix: Removed Focused loss triggering button Release

- sources/engine/Stride.UI/Controls/TextBlock.cs
- sources/engine/Stride.UI/Renderers/DefaultTextBlockRenderer.cs
Added support for text outlines in `TextBlock` with two new properties:
- `OutlineColor`: (Color) Specifies the color of the outline.
- `OutlineThickness`: (float) Determines the thickness of the outline.
When `OutlineThickness` is set to `0` or `OutlineColor` is `null`, the text will render normally without any outline.
Fixes #2581
- Introduced `OutlineColor` and `OutlineThickness` properties in the `TextBlock` class.
- Updated text rendering logic to apply an outline when these properties are configured.
- added them in the appearance section in TextBlock settings section in the editor
- This change does not break existing functionality.
- Supports both default and custom font rendering workflows.
> feat: added outline support for TextBlock

- sources/engine/Stride.Graphics/Direct3D/Texture.Direct3D.cs
`QueryInterface` increases the reference count and must be paired with a call to `Release`.
> [Graphics] Fixes memory leak when creating D3D11 texture with shared options

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs
Docs are kind of the only thing I can contribute atm, not sure what we should do with `SpeculativeMargin`, is that even useful to surface given how it is described in bepu ... left it as is for now
None.
> docs: Bepu, missing property summaries

- sources/editor/Stride.Core.Assets.Editor/View/Controls/GridLogViewer.cs
See title, the issue is specifically related to this window, if it hasn't been opened before and an error message is sent to it, opening it would show an empty list even though the tab mentions a non-zero amount of asset errors
This PR makes sure to fill in the message list as soon as the element is created.
None afaict
> fix: Empty GridLogViewer when messages are appended before the element is on screen

- sources/engine/Stride.Games/Desktop/GameForm.cs
This PR fixes the full-screen toggle being activated repeatedly while holding the `Alt + Enter` key combination. The fix involves checking if the key combination was not already held down by ensuring the previous key state flag (aka `KF_REPEAT`) in the `LParam` of the Windows message is 0.
With the fix applied, one can toggle full screen only by pressing `Enter` (down and up) while holding `Alt`.
See documentation on the `WM_SYSKEYDOWN` message (including the `LParam` details I mentioned) here: https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-syskeydown#remarks
Fixes #1530
> fix: Fix full-screen toggling repeatedly while holding Alt + Enter

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics.Tests/BepuTests.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics.Tests/Stride.BepuPhysics.Tests.csproj
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Contacts/ContactEventsManager.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Contacts/IContactEventHandler.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/StaticComponent.cs
See title, doing this causes some issues in the tracking of contact events, refactoring the logic to avoid this.
None reported afaict
> fix: bepu, removal of collidables while running a contact event leaves contact tracking in an unexpected state

- sources/core/Stride.Core/IService.cs
- sources/core/Stride.Core/IServiceRegistry.cs
- sources/core/Stride.Core/ServiceRegistry.cs
Adds two new methods to the service registry to help manage singleton-like objects and improve safety when un-registering services.
This is the shortest form to get and create a service if it doesn't exist:
```cs
if (Services.GetService<MySingleton>() is { } singleton == false)
Services.AddService(singleton = new MySingleton(Services));
singleton.DoWhatever();
```
Now this is fine, but singletons are more often than not used all over the place throughout a codebase, meaning that users will either have to copy paste the above, or create an extension method.
This pr would reduce the above into the following:
```cs
var singleton = Services.GetOrCreate<MySingleton>();
singleton.DoWhatever();
```
It is also easier to maintain as users now have only one entry point to their singleton's …
> Core: ServiceRegistry, GetOrCreate<T> and Remove(instance)

- sources/engine/Stride.Assets/SpriteFont/Compiler/BitmapImporter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/BitmapUtils.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/CharacterRegionTypeConverter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/FontNotFoundException.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/Glyph.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/GlyphCropper.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/GlyphPacker.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/OfflineRasterizedFontCompiler.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/OfflineRasterizedSpriteFontWriter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontCompiler.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontWriter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/TrueTypeImporter.cs
- sources/engine/Stride.Assets/SpriteFont/FileFontProvider.cs
- sources/engine/Stride.Assets/SpriteFont/FontProviderBase.cs
- sources/engine/Stride.Assets/SpriteFont/SystemFontProvider.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/FreeImageBitmap.cs
This PR moves font import from DirectWrite to FreeType. Also, It replaces System.Drawing.Bitmap with the FreeImageBitmap class + small refactor.
> Crossplatform font loading

- sources/engine/Stride.Rendering/Rendering/RootEffectRenderFeature.cs
Adds support for logical groups to the per frame resource groups, this allows for easy binding of per frame global resources. It's the same implementation as the per view / draw resource groups.
Sample usage:
```csharp
// Setup globally available resource group in sdsl
// It then only have to be bound once no matter how which materials use it.
rgroup PerFrame.Test
{
stage Texture2D GlobalTexture;
}
// Locate all per frame resource layouts that have the logical grou present.
// This is preferably done in SubRenderFeature.Prepare
var logicalGroupKey = ((RootEffectRenderFeature)RootRenderFeature).CreateFrameLogicalGroup("Test");
foreach (var frameLayout in ((RootEffectRenderFeature)RootRenderFeature).FrameLayouts)
{
var resourceGroup = frameLayout.Entry.Resources;
var logicalGroup = …
```
> feat: Added support for per frame logical groups in RootEffectRenderFeature

- sources/engine/Stride.Engine/Rendering/Compositing/ForwardRenderer.cs
- sources/engine/Stride.Rendering/Rendering/RootEffectRenderFeature.cs
- sources/engine/Stride.Rendering/Rendering/RootRenderFeature.cs
Generalizes the binding of per view resources in the `ForwardRenderer`. This change allows any `RootRenderFeature` to make use of depth and opaque render targets instead of being limited to only `RootEffectRenderFeature` and thus giving advanced users more options in how to implement features without being forced to use `RootEffectRenderFeature`, implement a custom `ForwardRenderer` or use other hacks.
> feat: Generalized per view resource binding

- sources/engine/Stride.Assets/SpriteFont/Compiler/BitmapImporter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/BitmapUtils.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/CharacterRegionTypeConverter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/FontNotFoundException.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/Glyph.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/GlyphCropper.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/GlyphPacker.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/OfflineRasterizedFontCompiler.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/OfflineRasterizedSpriteFontWriter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontCompiler.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontWriter.cs
- sources/engine/Stride.Assets/SpriteFont/Compiler/TrueTypeImporter.cs
- sources/engine/Stride.Assets/SpriteFont/FileFontProvider.cs
- sources/engine/Stride.Assets/SpriteFont/FontProviderBase.cs
- sources/engine/Stride.Assets/SpriteFont/SystemFontProvider.cs
- sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/FreeImageBitmap.cs
We'll revert stride3d/stride#2530 for now as that PR introduced an issue on windows with fonts of specific sizes, for example Calibri with a size of 17 threw an exception. #2636 fixes that issue but there is still some issues with some font rendering in an incorrect glitchy way.
> Revert "feat: Crossplatform font loading"

- sources/engine/Stride.Navigation/NavigationMeshBuilder.cs
- sources/engine/Stride.Navigation/Processors/NavigationProcessor.cs
- sources/engine/Stride.Physics/Shapes/StaticMeshColliderShape.cs
1. Ensure NavigationProcessor looks for DynamicNavigationMeshSystem when added, in case DynamicNavigationMeshSystem exists before itself.
2. Guard against null `eventArgs` which occurs when DynamicNavigationMeshSystem.Enabled = false
3. Ensure `Navigation.DestroyBuilder(builder)` is always called otherwise memory is never released on failed cases.
4. Call dispose on BulletMesh & RecastNavigationMesh to ensure memory released.
Fixes #2630
> fix: Legacy DynamicNavigationMeshSystem bugs and memory leak

- sources/engine/Stride.UI/Controls/TextBlock.cs
If TextBlock is given an available space that the width is so small to fit in even one character, TextBlock will enter an infinite loop of repeatedly adding and removing the first character, and creating a new line in the wrapped text. This unexpected infinite loop will crash the editor due to a memory leak.
With this PR, the wrapped text will have at least one character (even if the character is zero width) from the original text in each new line.
(Wrap Text option disabled, horizontal overflow)
(Wrap Text option enabled with the fix, horizontal wrapped with vertical overflow. Without this fix the engine will crash eventually given enough time)
Fixes #2514
> fix: TextBlock enters an infinite loop if the given available space is too small to fit even one character.

- sources/assets/Stride.Core.Assets.CompilerApp/build/Stride.Core.Assets.CompilerApp.targets
- sources/core/Stride.Core/Serialization/ContentRefOutOfSyncException.cs
- sources/core/Stride.Core/Serialization/MemberSerializerCore.ttinclude
- sources/core/Stride.Core/Serialization/MemberSerializerGenerated.cs
Content out of sync exception triggers when removing/adding a property to a [custom asset](https://doc.stride3d.net/latest/en/manual/scripts/custom-assets.html), this change ensures users are aware of how to proceed when encountering this issue.
Kindly pinging @Jklawreszuk to check this one as he is more experienced with the build system than I am
> fix: Add assets cleanup target when calling dotnet clean, clarify ref out of sync issues

- sources/assets/Stride.Core.Assets.Quantum/AssetPropertyGraph.cs
- sources/assets/Stride.Core.Assets/Analysis/BuildAssetNode.cs
- sources/assets/Stride.Core.Assets/Analysis/CollectionItemIdsAnalysis.cs
- sources/assets/Stride.Core.Assets/AssetRegistry.cs
- sources/assets/Stride.Core.Assets/CollectionIdGenerator.cs
- sources/assets/Stride.Core.Assets/Serializers/ContentReferenceSerializer.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/ContentReferenceCollector.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/GameEditorChangePropagator.cs
- sources/editor/Stride.Core.Assets.Editor/Components/FixAssetReferences/AssetReferenceReplacementViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Components/FixAssetReferences/FixAssetReferencesViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Components/FixReferences/FixReferencesViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Components/FixReferences/ReferenceReplacementViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/AddNewItemCommand.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/FetchAssetCommand.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/PickupAssetCommand.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Commands/SetContentReferenceCommand.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/AbstractNodeEntryNodeUpdater.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/SessionNodeUpdater.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/ViewModels/AssetNodeViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Services/ContentReferenceHelper.cs
- sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/ContentReferenceTemplateProvider.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModel/ContentReferenceViewModel.cs
- sources/editor/Stride.Editor/EditorGame/ContentLoader/LoaderReferenceManager.cs
- sources/engine/Stride.Assets/RuntimeTypesCollector.cs
- sources/engine/Stride.Debugger/Debugger/CloneReferenceSerializer.cs
Properties of interface types can now be assigned to assets which implement that interface. Similar to the changes done in #1842
None reported
Excerpt of the idea:
```cs
public class Inventory
{
public List<IItem> Items { get; set; } = new();
}
public interface IITem;
public class HealthPotion : IItem
{
public int HealthGained = 10;
}
public class Armor : IItem
{
public int Value;
}
```
Setup required for the above to work as assets removed, see full example project using this feature [MyGame2.zip](https://github.com/user-attachments/files/18924510/MyGame2.zip)
> feat: Add asset support for interface properties

- sources/editor/Stride.GameStudio/Stride.GameStudio.csproj
Hotfix : UI nuget resolver doesn't work because it needs Avalonia which requires... running the nuget resolver 🙃
> fix: Temporarily disable the resolver UI as there is a dependency issue with Avalonia.

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
We have to explicitly notify bepu when moving a body, even more so when sleeping, otherwise its internal representation inside the physics scene is not updated, leading to misses when doing physics tests
fix #2649
> fix: Ensure teleporting bodies notify bepu's data structure

- sources/editor/Stride.GameStudio/Stride.GameStudio.csproj
- sources/shared/Stride.NuGetResolver.Targets/NuGetResolverModuleInitializer.cs
- sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
- sources/shared/Stride.NuGetResolver.UI/NuGetAssemblyResolver.private.cs
- sources/shared/Stride.NuGetResolver.UI/SplashScreenWindow.axaml.cs
- sources/shared/Stride.NuGetResolver.UI/Stride.NuGetResolver.UI.csproj
- sources/shared/Stride.NuGetResolver/NuGetAssemblyResolver.cs
- sources/shared/Stride.NuGetResolver/Stride.NuGetResolver.csproj
Following #2651, properly solves the issue with displaying the new Nuget Resolver UI that broke `releases/4.2.0.2371`.
The new Resolver UI uses Avalonia instead of WPF.
By design (and because of its function) the resolver runs very early in the startup of the GameStudio (or of the ConnectionRouter). Stride packages(and their dependencies) might not have ever been resolved on the user machine and the purpose of the resolver is also to locate such packages so that their paths can be known and their respective assembly resolved. It is also required because the GameStudio is started from its nuget package which doesn't bring all of its dependencies with it (but rather links them as is the usual way).
However, Avalonia itself is also not resolved and the UI cannot be loaded because of that. On …
> fix: Restore Nuget Resolver UI

- sources/editor/Stride.Assets.Presentation/Templates/Assets/UI/Page.sdtpl
- sources/editor/Stride.Core.Assets.Editor/Resources/Images/default-template-icon.png
PR fixes incorrect display of UIPage asset icon - previously default template icon was selected.
I also modified the default icon for assets
> fix: Correct UIPage icon and update default template icon

- sources/assets/Stride.Core.Assets/Package.cs
Fixes a bug in the UpdateSourceFolders method of the package class, which updates the root asset folders. The issue was introduced during the modernization refactoring in commit cb520de77b33bfdd8efc3b0de36ddbe9ea0004a4. This fix ensures that only new folders are stored in the asset folder list and avoids duplicated and absolute folders.
Closes #2667
> fix: add only new asset folders to the package

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
Basically, bodies set to interpolate would interpolate with outdated data if the user happened to teleport the body between two physics tick. Also removed a couple of unnecessary operations around those areas.
> fix: Interpolation discontinuities after teleporting a body component

- sources/engine/Stride.Graphics/Vulkan/GraphicsDevice.Vulkan.cs
- sources/engine/Stride.Shaders.Compiler/OpenGL/ShaderCompiler.cs
* Fixed concurrency issues that caused a full driver crash when texture streaming is enabled.
* Fixed a validation error casued by the default `NoSampler` that is used when converting `Texture.Load` to `texelFetch`.
Found some validation errors when running in debug mode and also full driver crash when texture streaming was enabled.
> Vulkan concurrency and validation error fixes

- sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs
Followup to #2320 - filters that are added by the engine, like `UIPage` when opening the picker for field of that type, persisted to new instance of the picker, meaning that new pickers for `Texture` would have a `UIPage` filter added in as well.
This change ensures that we only persist user-defined filters across instances.
> fix: Prevent editor-inserted filters from persisting across views

- sources/engine/Stride.Graphics/SDL/Window.cs
This PR fixes an issue for Wayland based DE like Gnome that causes a crash. Issue was fixed by setting driver to X11. 
https://github.com/stride3d/stride/issues/2487
> fix: Wayland crash workaround

- sources/assets/Stride.Core.Assets.Tests/Yaml/TestCollectionIdsSerialization.cs
- sources/assets/Stride.Core.Assets/Yaml/CollectionWithIdsSerializer.cs
- sources/assets/Stride.Core.Assets/Yaml/CollectionWithIdsSerializerBase.cs
- sources/assets/Stride.Core.Assets/Yaml/DictionaryWithIdsSerializer.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/DictionaryDescriptor.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializers/CollectionSerializer.cs
- sources/core/Stride.Core.Yaml/Serialization/Serializers/DictionarySerializer.cs
The yaml serializer adds its serialized items on top of those that may already be contained in the list. The following snippet would continuously add one more `0.5` to the collection's serialization data on every save.
```cs
public List<float> Coll { get; } = new List<float>(){ 0.5f };
```
This PR ensures that, if yaml has data about items for a collection, the pre-existing ones are cleared before adding those that are serialized.
Do note that this was already handled on the `AssemblyProcessor` side, see `ListSerializer.PreSerialize()` and other collection serializers.
Pinging @IXLLEGACYIXL to let him know of this rule given the work he is doing for the next yaml serializer.
None logged afaict
> fix: Handle initial collection items appropriately, YAML

- README.md
installing the latest arm build tools didn't help building the engine because is needed ARM64 build tools and ARM64 build tools have no latest version but there is one called ARM64/ARM64EC build tools and it has a latest version and after asking on discord @Eideren said that i should install it and when i installed it i had no problem building the engine
> Update README.md for ARM64 latest version is called ARM64/ARM64EC

- sources/editor/Stride.Assets.Presentation/NodePresenters/Commands/SetComponentReferenceCommand.cs
- sources/editor/Stride.Assets.Presentation/NodePresenters/Updaters/EntityHierarchyAssetNodeUpdater.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/AbstractNodeEntryNodeUpdater.cs
The exception thrown is because the handler always tries to create a new instance of whichever type is selected while the editor expects `EntityComponent` to live on an entity in a scene.
Drag and drop support for interface properties specifically, other property types already works.
Here's how it looks like *without* this PR:
https://github.com/user-attachments/assets/e04b40b8-4c6d-48fc-b33d-3b6db4b6dc1a
None reported afaict.
> fix: internal exception being thrown when selecting a EntityComponent type in interface properties + drag and drop support

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Contacts/ContactEventsManager.cs
Events should have been collected and passed to the user through the main thread instead of using the worker thread, this caused an issue reported in #2703 as some other part of the event management logic did not expect concurrent access.
Fix: #2703
> fix: Avoid race condition in parallelized contact event collection

- README.md
- Added a note that Visual Studio 2022 workloads can be installed via Visual Studio Build Tools.
- Updated C++ build tools section to clarify default enabled status.
- Emphasized that ARM64/ARM64EC build tools are not enabled by default and provided instructions for enabling them.
- Adjusted formatting for improved clarity.
I did 3 tests of building Stride from source in Windows 11, all in a clean Windows installations:
- Build Stride with Visaul Studio 2022 - **Success**
- Build Stride without Visual Studio - **Success**
- Build Stride without Visual Studio without installing ARM64/ARM64EC - **Build Error** (Expected) because of missing ARM64/ARM64EC
Based on the tests and following current instructions I propose minor adjusments in the instructions (this PR).
----------------------- …
> docs: README.md - Update Visual Studio 2022 installation notes

- sources/assets/Stride.Core.Assets.Tests/TestAssetInheritance.cs
- sources/assets/Stride.Core.Assets/Yaml/AssetObjectSerializerBackend.cs
The parsing events, which are effectively tokens that the deserializer reads to create the final object, are mutated when deserializing. If you were to re-use those parsing events a second time, it would generate the same object, but the metadata would be partially lost.
A reader-like object should not be writing to the stream it is reading from.
The spot where it is called twice with the same parsing events is located here:
https://github.com/stride3d/stride/blob/8d3547a7de1d3f3fdbd796a998915c461bbaa1e9/sources/editor/Stride.Assets.Presentation/AssemblyReloading/GameStudioAssemblyReloader.cs#L423-L466
And it is because
https://github.com/stride3d/stride/blob/8d3547a7de1d3f3fdbd796a998915c461bbaa1e9/sources/editor/Stride.Assets.Presentation/AssemblyReloading/GameStudioAssemblyReloader.cs#L …
> fix: yaml, rollback trimming of the override tag when parsing collection index to ensure inputs can be re-used

- sources/editor/Stride.Assets.Presentation/AssemblyReloading/GameStudioAssemblyReloader.cs
- sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/GameEditorChangePropagator.cs
Replaced the `ReloadingVisitor` - we already have the paths to the items we need to reload, no need to go through every leaf of the tree of the asset.
https://github.com/stride3d/stride/blob/8d3547a7de1d3f3fdbd796a998915c461bbaa1e9/sources/editor/Stride.Assets.Presentation/AssemblyReloading/GameStudioAssemblyReloader.cs#L300-L305
Calls `ProcessObject` twice for the same object/path combination, once right in this scope, another one through `VisitObject` down the base call.
Here I'm not 100% certain:
https://github.com/stride3d/stride/blob/8d3547a7de1d3f3fdbd796a998915c461bbaa1e9/sources/editor/Stride.Assets.Presentation/AssetEditors/GameEditor/ViewModels/GameEditorChangePropagator.cs#L170-L178
The use of `CanBeAssignedToContentTypes()` with `GetInnerCollectionType()` is to ignore …
> fix: Optimize assembly reloading

- sources/assets/Stride.Core.Assets.Quantum/IAssetObjectNode.cs
- sources/assets/Stride.Core.Assets.Quantum/Internal/AssetBoxedNode.cs
- sources/assets/Stride.Core.Assets.Quantum/Internal/AssetObjectNode.cs
- sources/assets/Stride.Core.Assets.Quantum/Internal/AssetObjectNodeExtended.cs
- sources/core/Stride.Core.Reflection/TypeDescriptors/ArrayDescriptor.cs
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/ImageResources.axaml
- sources/editor/Stride.Core.Assets.Editor.Tests/TestArchetypesBasicUndoRedo.cs
- sources/editor/Stride.Core.Assets.Editor/Components/Properties/SessionObjectPropertiesViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Components/Transactions/ActionHistoryViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/Components/Transactions/TransactionViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModels/SessionViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModels/SessionViewModel.static.cs
- sources/editor/Stride.Core.Assets.Presentation/Quantum/AssetContentValueChangeOperation.cs
- sources/editor/Stride.Core.Assets.Presentation/Quantum/ContentValueChangeOperation.cs
- sources/editor/Stride.Core.Assets.Presentation/Quantum/ViewModels/AssetNodeViewModel.cs
- sources/editor/Stride.Core.Assets.Presentation/Quantum/ViewModels/AssetNodeViewModelFactory.cs
- sources/editor/Stride.Core.Assets.Presentation/ViewModels/AssetViewModel.cs
- sources/editor/Stride.GameStudio.Avalonia/Views/MainView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/MainView.axaml.cs
- sources/presentation/Stride.Core.Presentation/ViewModels/EditableViewModel.cs
- sources/presentation/Stride.Core.Quantum/IObjectNode.cs
- sources/presentation/Stride.Core.Quantum/ObjectNode.cs
Displays the transaction history into the dedicated panel. Binds key gestures `CTRL+Z` and `CTRL+Y` to the Undo and Redo action.
#2758
> feat: undo/redo & action history panel

- sources/engine/Stride.Games/GameWindowRenderer.cs
- sources/engine/Stride.Games/GraphicsDeviceManager.cs
- sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
- sources/engine/Stride.Graphics/GraphicsPresenter.cs
- sources/engine/Stride.Graphics/PresentationParameters.cs
- sources/engine/Stride/Graphics/ColorSpace.cs
This PR introduces support for rendering to High Dynamic Range (HDR) displays by enabling configuration of the swap chain's output color space and pixel format.
1.  **`ColorSpaceType` Enum:** Added a new `Stride.Graphics.ColorSpaceType` enum (in `ColorSpace.cs`) which mirrors the `DXGI_COLOR_SPACE_TYPE` values. 
2.  **`GraphicsPresenter.SetOutputColorSpace` Method:** Added a new public method `GraphicsPresenter.SetOutputColorSpace(ColorSpaceType colorSpace, PixelFormat format)`. This is the primary way for users to configure the desired output. Calling this method will:
*   Update the presenter's description.
*   Recreate the underlying swap chain (using `IDXGISwapChain3::SetColorSpace1` on D3D11/12) with the specified color space.
*   Resize back buffer and depth stencil buffers …
> [Graphics] Enable rendering to HDR displays on DirectX/Windows

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Raycast/RayHitsStackHandler.cs
That assert is always hit when the buffer provided to the player is smaller than the amount of hits bepu found.
I wrote this nonsense, `Debug.Assert(t > storedMax, ...` should have been `Debug.Assert(t < storedMax` from the start since `maximumT` ensures subsequent hits have the `t < maximumT` constraint. I was aware of that at the time given the message, I just wrote the comparison the wrong way around.
Removed the assert as I finally had the time to test this proper.
None reported
> fix: Bepu, validate Debug.Assert and remove as the logic was mistakenly inverted

- sources/engine/Stride.UI/UIElement.cs
Replacing PR #2604 for a more generalize approach as asked.
Canvas can provides children with Infinity values for `availableSizeWithMargins` when measuring. Most `UIElement`s handle Infinity in `MeasureOverride`. For UIElments that do not handle Infinity, an Infinity check was added to UIElement.Measure as a default behavior to check for Parent.RenderSize recursively in `InfinityToParentRenderSize`. 
This was done recursively in since the `Arrange` happens after `Measure`, and  `Arrange` is when RenderSize is normally set except for the root element RenderSize is set earlier. 
Note on UIElments Stretch:
I have tested UIElements like Canvas inside of another Canvas and currently the second Canvas size is set to 0. This appears to be caused by `childrenDesiredSize` being set to `NaN` then …
> fix: Slider put in Canvas NaN Exception

- build/compile.bat
Fixes the error reported in #2733 in a (hopefully) minimally invasive way. 
I also tried another approach to fix this [here](https://github.com/hoelzl/stride/tree/fix-build-de). But that is probably too much code for such a simple task, although it seems slightly more robust. 
I know very little about writing CMD scripts, however, so both approaches might be flawed.
#2733
> fix: compile.bat error when computing duration (#2733)

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/_ConstraintComponent.cs
Constraints bound to bodies were appended twice, once when setting `Body.A` and another when the constraint is added to the scene. This does not cause issues, just wasted cycles and the list having twice as many items as expected
> fix: Bepu, fix constraint tracking

- sources/engine/Stride.Engine/Engine/Processors/TransformProcessor.cs
This PR fixes a typo.
- Fixed a typo in the method name from `UpdateTransfromationsRecursive()` to `UpdateTransformationsRecursive()` in `TransformProcessor.cs`.
- Namespaces removed
> fix: TransformProcessor.cs - Correct method name typo

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/AngularServoConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/IServo.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyAngularServoConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/TwistLimitConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/TwistServoConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/WeldConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/_OneBodyConstraintComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/_TwoBodyConstraintComponent.cs
Constraints with Quaternion values are not initialized with valid values, this PR ensures that they are initialized to Identity.
Also adds a couple of summaries.
N.B.: I mistakenly made it as a new branch under stride, I'll delete it as soon as I'm done
None reported
> fix: Bepu, ctor with valid orientation for constraints

- sources/editor/Stride.Assets.Editor.Avalonia/EditorViewSelector.cs
- sources/editor/Stride.Assets.Editor.Avalonia/Stride.Assets.Editor.Avalonia.csproj
- sources/editor/Stride.Assets.Editor.Avalonia/Views/EntityPropertyTemplateProviders.axaml
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Behaviors/PropertyViewAutoExpandNodesBehavior.cs
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Stride.Core.Assets.Editor.Avalonia.csproj
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/DefaultPropertyTemplateProviders.axaml
- sources/editor/Stride.Editor.Avalonia/Stride.Editor.Avalonia.csproj
- sources/editor/Stride.GameStudio.Avalonia/Controls/DebugLogUserControl.axaml
- sources/editor/Stride.GameStudio.Avalonia/Stride.GameStudio.Avalonia.csproj
- sources/editor/Stride.GameStudio.Avalonia/Themes/DefaultStyles.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/AssetExplorerView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/DebugWindow.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/EditorCollectionView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/MainView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/MainWindow.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/PropertyGridView.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Behaviors/BindCurrentToolTipStringBehavior.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/NumericTextBox.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/NumericTextBoxValueChangedEventArgs.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/PropertyView.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/PropertyViewItem.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/PropertyViewItemEventArgs.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/VectorEditorBase.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Stride.Core.Presentation.Avalonia.csproj
- sources/presentation/Stride.Core.Presentation.Avalonia/Windows/CheckedMessageBox.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Windows/MessageBox.axaml
Some improvements of the property grid to bring it closer to feature parity with the old editor.
* highlighting
* rule-based auto-expanding
As well as some Avalonia-specific improvements such as using compiled bindings by default, which should bring better performance (https://docs.avaloniaui.net/docs/basics/data/data-binding/compiled-bindings)
#2739
> feat: property grid improvements

- .github/workflows/build-assembly-processor.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-vs-package.yml
- .github/workflows/build-windows.yml
- .github/workflows/main.yml
- .github/workflows/test-windows.yml
Add CI workflows that will run when PRs are opened, updated and merged.
The workflows can also be triggered manually if necessary.
[![image](https://github.com/user-attachments/assets/86dc9c83-4ecb-4cb3-8c83-8bea17891423)](https://github.com/Color-Rise/stride-xplat-editor/actions/runs/15072497191)
Before merging, it would be good to restrict who can run workflows and use the most conservative settings at the beginning. As an example, here what I have on my fork:
> feat: Add CI workflows

- sources/engine/Stride.Games/Desktop/GameWindowWinforms.cs
- sources/engine/Stride.Games/GameWindow.cs
- sources/engine/Stride.Games/SDL/GameWindowSDL.cs
- sources/engine/Stride.Graphics/SDL/Window.cs
Add <b>BackgroundColor</b> and <b>Opacity</b> API
Support games like https://store.steampowered.com/app/2666510/Rustys_Retirement/
> feat: Add more window api

- build/Stride.sln
- sources/assets/Stride.Core.Packages/NugetStore.cs
- sources/assets/Stride.Core.Packages/ProgressReport.cs
- sources/core/Stride.Core/Native/NativeLibraryHelper.cs
- sources/editor/Stride.GameStudio.Avalonia.Desktop/Module.cs
- sources/editor/Stride.GameStudio.Avalonia.Desktop/Stride.GameStudio.Avalonia.Desktop.csproj
- sources/launcher/Stride.Launcher/App.axaml.cs
- sources/launcher/Stride.Launcher/Constants.cs
- sources/launcher/Stride.Launcher/Crash/CrashReportViewModel.cs
- sources/launcher/Stride.Launcher/Crash/CrashReportWindow.axaml
- sources/launcher/Stride.Launcher/PackageFilterExtensions.cs
- sources/launcher/Stride.Launcher/Program.cs
- sources/launcher/Stride.Launcher/Services/GameStudioSettings.cs
- sources/launcher/Stride.Launcher/Services/SelfUpdater.cs
- sources/launcher/Stride.Launcher/Stride.Launcher.csproj
- sources/launcher/Stride.Launcher/ViewModels/DocumentationPageViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/MainViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/NewsPageViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/PackageVersionViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/StrideStoreVersionViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/StrideVersionViewModel.cs
- sources/launcher/Stride.Launcher/ViewModels/VsixVersionViewModel.cs
- sources/launcher/Stride.Launcher/Views/MainView.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Stride.Core.Presentation.Avalonia.csproj
- sources/presentation/Stride.Core.Presentation.Avalonia/Windows/CheckedMessageBox.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Windows/MessageBox.axaml
- sources/shared/Stride.NuGetResolver/NuGetAssemblyResolver.cs
Resolve and restore NuGet dependencies when launching the GameStudio from its package (for instance from the Launcher).
[08_LaunchingGameStudio.webm](https://github.com/user-attachments/assets/6b22fecb-98f3-4f45-9aba-437152475b59)
Contributes to #2767.
> feat: NuGet resolution & start from new Launcher

- sources/engine/Stride.Graphics/UIBatch.cs
UI elements have individual depth bias applied to them to ensure they are drawn in the correct order. This works fine when you expect the UI to always face the camera, like is the case for billboards and fullscreen UI, but worldspace UI do not always face the camera, this PR reverses the bias if the UI is facing away from the camera.
Here, the orange line is a UI element from a world space UI facing away from the camera. The black cube is in front of the UI - the element should be completely occluded by the cube, but the depth bias pulled the UI towards the camera enough as to make it clip in front of it
With this PR's change, the depth bias is reversed, when the element is facing away from the camera, pushing it away from the camera resolving this issue;
None reported.
> fix: UI depth bias does not account for facing direction

- sources/engine/Stride.Physics/ContactPoint.cs
- sources/engine/Stride.Physics/Simulation.cs
The `ContactPoint` object should store additional lateral impulse data. This is useful in certain scenarios:
- If you want to adjust physical interaction feedback (e.g. when hit by a bullet or a punch)
- If you want audio to be dependent on the normal forces (e.g. play louder sounds on a harder impact)
- If you want to debug the runtime bounce between objects (e.g. an object is bouncing too heavily)
By updating it, we enabled `BulletSharps'` data to be propagated and stored in this object. 
https://github.com/stride3d/stride/issues/2490
> feat: adds on impulses to contact point

- .github/workflows/build-android.yml
- .github/workflows/build-assembly-processor.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-launcher.yml
- .github/workflows/build-linux-runtime.yml
- .github/workflows/build-vs-package.yml
- .github/workflows/build-windows-full.yml
- .github/workflows/build-windows-runtime.yml
- .github/workflows/main.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-windows.yml
Automatically cancels running workflow if a more recent push or merge happened.
This should save some actions minutes by preventing to build for commits that are no longer relevant.
See https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
> feat: GitHub CI concurrency

- sources/core/Stride.Core.Design/Settings/SettingsKey.cs
- sources/core/Stride.Core.Design/Settings/SettingsProfile.cs
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Converters/NodePathToObject.cs
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Themes/PropertyViewTheme.axaml
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/DefaultPropertyTemplateProviders.axaml
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/PropertyTemplateProviderSelector.cs
- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/SettingsStringFromAcceptableValuesTemplateProvider.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Keys/SettingsData.cs
- sources/editor/Stride.Core.Assets.Editor/Quantum/NodePresenters/Updaters/SettingsPropertyNodeUpdater.cs
- sources/editor/Stride.Core.Assets.Editor/Settings/EditorSettings.cs
- sources/editor/Stride.Core.Assets.Editor/Settings/PackageSettingsWrapper.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModels/SettingsCategoryViewModel.cs
- sources/editor/Stride.Core.Assets.Editor/ViewModels/SettingsViewModel.cs
- sources/editor/Stride.GameStudio.Avalonia/App.axaml.cs
- sources/editor/Stride.GameStudio.Avalonia/Services/EditorDialogService.cs
- sources/editor/Stride.GameStudio.Avalonia/ViewModels/MainViewModel.cs
- sources/editor/Stride.GameStudio.Avalonia/Views/DebugWindow.axaml.cs
- sources/editor/Stride.GameStudio.Avalonia/Views/MainView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/PropertyGridView.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/SettingsWindow.axaml
- sources/editor/Stride.GameStudio.Avalonia/Views/SettingsWindow.axaml.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Behaviors/ButtonCloseWindowBehavior.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Behaviors/CloseWindowBehavior.cs
Adds a Window for editing the settings.
> feat: Settings Window

- sources/presentation/Stride.Core.Presentation.Avalonia/MarkupExtensions/DoubleExtension.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/MarkupExtensions/IntExtension.cs
PR fixes following bug: 
1. Run new Avalonia Editor on Windows (`dotnet run`)
2. Load any game solution file.
3. Select any asset or go to settings.
4. Crash :
```
Exception: FormatException: The input string '0.5' was not in a correct format.
```
I simply used passed additional CultureInfo argument to take into account the different formats (dots or commas) that occur between languages.
My Current LocaleInfo : pl-PL
> fix: DoubleExtension & IntExtension

- sources/editor/Stride.Core.Assets.Editor.Avalonia/Views/DefaultPropertyTemplateProviders.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/ToolBar.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/ToolBarOverflowPanel.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/ToolBarPanel.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Controls/ToolBarTray.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Internal/DoubleUtil.cs
- sources/presentation/Stride.Core.Presentation.Avalonia/Themes/TextLogViewerStyle.axaml
- sources/presentation/Stride.Core.Presentation.Avalonia/Themes/ToolBarStyle.axaml
Add overflow panel to toolbars (either when they don't fit the area pr when items are explicitly set to appear in an overflow).
The behavior is adapted from WPF (https://github.com/dotnet/wpf/).
Note: I purposely didn't implement drag/drop of toolbars within the tray. I assumed users would expect the new positions to be saved as local settings and I didn't want to deal with that yet.
#2830
> feat: Toolbar overflow

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/SystemsOrderHelper.cs
- sources/engine/Stride.Engine/Engine/InputSystem.cs
Set the update order for the `InputSystem` to a non-zero value, it will now always run before other systems with unset order.
Previously, users may inadvertently introduce a one-frame input latency to their scripts by creating the `ScriptSystem` before the `InputSystem`.
Also provides a way for users to insert systems that may run after the `InputSystem` but before the `ScriptSystem` without touching those two systems or creating a custom game implementation.
Given the above, moved the execution point of `Bepu` earlier in the frame, before `ScriptSystem` runs to make sure interpolated bodies update their positions before users may read them in update, but after `InputSystem` otherwise users would be reading last frame's input when they implement `Components.ISimulationUpdate`.
The above …
> fix: Bepu and InputSystem update order

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
> Typo: Rename _nativeIntertia to _nativeInertia

- samples/Audio/SimpleAudio/SimpleAudio.Game/SimpleAudio.Game.csproj
- samples/Games/JumpyJet/JumpyJet.Game/JumpyJet.Game.csproj
- samples/Games/SpaceEscape/SpaceEscape.Game/SpaceEscape.Game.csproj
- samples/Graphics/AnimatedModel/AnimatedModel.Game/AnimatedModel.Game.csproj
- samples/Graphics/CustomEffect/CustomEffect.Game/CustomEffect.Game.csproj
- samples/Graphics/MaterialShader/MaterialShader.Game/MaterialShader.Game.csproj
- samples/Graphics/SpriteFonts/SpriteFonts.Game/SpriteFonts.Game.csproj
- samples/Graphics/SpriteStudioDemo/SpriteStudioDemo.Game/SpriteStudioDemo.Game.csproj
- samples/Input/GravitySensor/GravitySensor.Game/GravitySensor.Game.csproj
- samples/Input/TouchInputs/TouchInputs.Game/TouchInputs.Game.csproj
- samples/Particles/ParticlesSample/ParticlesSample.Game/ParticlesSample.Game.csproj
- samples/Physics/BepuSample/BepuSample.Game/BepuSample.Game.csproj
- samples/Physics/PhysicsSample/PhysicsSample.Game/PhysicsSample.Game.csproj
- samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/FirstPersonShooter.Game.csproj
- samples/Templates/Packs/MaterialPackage/MaterialPackage.csproj
- samples/Templates/Packs/PrototypingBlocks/PrototypingBlocks.csproj
- samples/Templates/Packs/SamplesAssetPackage/SamplesAssetPackage.csproj
- samples/Templates/Packs/VFXPackage/VFXPackage.csproj
- samples/Templates/Packs/mannequinModel/mannequinModel.csproj
- samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/ThirdPersonPlatformer.Game.csproj
- samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/TopDownRPG.Game.csproj
- samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/VRSandbox.Game.csproj
- samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/CSharpBeginner.Game.csproj
- samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/CSharpIntermediate.Game.csproj
- samples/UI/GameMenu/GameMenu.Game/GameMenu.Game.csproj
- samples/UI/UIElementLink/UIElementLink.Game/UIElementLink.Game.csproj
- samples/UI/UIParticles/UIParticles.Game/UIParticles.Game.csproj
- sources/editor/Stride.Samples.Templates/ThisPackageVersion.DevBuild.cs
- sources/editor/Stride.Samples.Templates/ThisPackageVersion.PackageBuild.cs
This PR update Stride Dev version to 4.2.1.1
see #2822
> feat: Update Stride dev version for the game samples

- .github/release.yml
This PR adds a new label, `behavioral-change`, under **Breaking changes** in `release.yml`. With this update, any PR tagged with this label will automatically appear under the **Breaking changes** section in the release notes.
n/a
> Add 'behavioral-change' label to breaking changes

- sources/engine/Stride.UI.Tests/Layering/GridTests.cs
- sources/engine/Stride.UI.Tests/Layering/StackPanelTests.cs
- sources/engine/Stride.UI.Tests/Layering/UniformGridTests.cs
- sources/engine/Stride.UI/Panels/Grid.cs
- sources/engine/Stride.UI/Panels/GridBase.cs
- sources/engine/Stride.UI/Panels/StackPanel.cs
- sources/engine/Stride.UI/Panels/UniformGrid.cs
Introduced gap functionality to Grid, UniformGrid and StackPanel similar to the `gap` in CSS.
Add `ColumnGap`, `RowGap`, and `LayerGap` properties in GridBase for Grid and UniformGrid to manage spacing between elements. Extend the StackPanel to include a gap property.
- Grid: <img width="1655" height="617" alt="image" src="https://github.com/user-attachments/assets/c2df9a35-a5c9-4fa0-8e20-65243ec9b54b" />
- UniformGrid: <img width="1691" height="665" alt="image" src="https://github.com/user-attachments/assets/213d85ed-0148-4fdd-9343-7ad5dfb19d9e" />
- Stackpanel: <img width="1675" height="650" alt="image" src="https://github.com/user-attachments/assets/11d4e742-eecd-4c22-b2cc-e3ca872f3028" />
Closes #2852
> [UI] Add gap support to layout panels

- sources/engine/Stride.Physics/Engine/PhysicsComponent.cs
If a physicscomponent attached to an entity has no collidershapes, there is an error log from the physicscomponent. It should log the name of the entity in the message, but there are two brackets to much in the error string which results in "[PhysicsComponent]: Error: Entity {Entity.Name} has a PhysicsComponent without any collider shape." which dosn't include the real name of the entity.
I didn't create an issue because it's a simple error and fixed it right away when i saw it.
To reproduce: add a e.g. RigidBodyComponent to an Entity but don't add a collidershape and run the game. You will then see the wrong error log.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] All new and existing tests passed.
- [x ] **I have built and run the editor to try this change out.**
> fix: removed double brackets in error log string

- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
- sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/IServo.cs
n/a
docs: Update documentation in BodyComponent and IServo
- In the `BodyComponent.cs` file, updated the documentation comment to specify the full namespace for the `INarrowPhaseCallbacks` interface, changing it from `<see cref="INarrowPhaseCallbacks"/>` to `<see cref="global::BepuPhysics.CollisionDetection.INarrowPhaseCallbacks"/>`.
- In the `IServo.cs` file, modified the documentation comment to change the reference from `<see cref="MaximumForce"/>` to `<see cref="ServoMaximumForce"/>`.
Documentation update to improve clarity and accuracy of code references.
This pull request enhances the documentation in two files to provide clearer references to specific interfaces and properties. 
- `BodyComponent.cs`: Updated the reference to `INarrowPhaseCallbacks` to include its namespace for …
> docs: Update xml comments in BodyComponent and IServo

- sources/engine/Stride.Graphics/BatchBase.cs
`DrawBatchPerTextureAndPass` is called multiple times per frame and per instance,
https://github.com/stride3d/stride/blob/4903592434d89a37ad5ec08b06f95db3ffa3a4d5/sources/engine/Stride.Graphics/BatchBase.cs#L461-L467
`GetTemporaryBuffer()` here will retrieve the buffer it just used in a previous call when that buffer may be in use by the GPU causing a stall when calling `MapSubresource()` below:
https://github.com/stride3d/stride/blob/4903592434d89a37ad5ec08b06f95db3ffa3a4d5/sources/engine/Stride.Graphics/BatchBase.cs#L504
This PR cleans up the logic and ensures that temporary buffers are only released on the next `Begin` of the batcher to make sure that they are not still being used.
Performance difference goes from ~0.083ms to ~0.0013ms per call to MapSubresource. This method is called …
> perf: Improve UI batch performance

- .github/CONTRIBUTING.md
- README.md
If a repository includes a CONTRIBUTING.md file, GitHub also surfaces it in two other places to make it easier for contributors to discover:
- A " Contributing" tab in the repository overview (next to the " README" and " Code of conduct")
- A "Contributing" link in the repository sidebar
The original Contributing content was moved to this new file. README.md still contains a paragraph.
n/a
> feat: Add CONTRIBUTING.md - A "Contributing" tab will surface in the repository overview
