README.md
=> Fix a broken URL.

sources/assets/Xenko.Core.Assets.CompilerClient/Xenko.Core.Assets.CompilerClient.csproj, sources/assets/Xenko.Core.Assets.Quantum/Xenko.Core.Assets.Quantum.csproj, sources/assets/Xenko.Core.Assets/Xenko.Core.Assets.csproj, sources/core/Xenko.Core.AssemblyProcessor/Xenko.Core.AssemblyProcessor.csproj, sources/core/Xenko.Core.Tasks/Xenko.Core.Tasks.csproj, sources/editor/Xenko.Assets.Presentation/Xenko.Assets.Presentation.csproj, sources/editor/Xenko.Editor/Xenko.Editor.csproj, sources/editor/Xenko.GameStudio/Xenko.GameStudio.csproj, sources/engine/Xenko.Assets/Xenko.Assets.csproj, sources/tools/Xenko.ProjectGenerator/Xenko.ProjectGenerator.csproj, sources/tools/Xenko.VisualStudio.Package/Xenko.VisualStudio.Package.csproj
update Microsoft.Build.* packages, fixing "Could not find a compatible version of MSBuild." errors
=> update Microsoft.Build.* packages

sources/editor/Xenko.GameStudio/View/AboutPage.xaml.cs
Following #75, load the markdown document inside a task when clicking on the hyperlink.
=> [GameStudio] Don't block the UI thread when clicking on the hyperlinks.

sources/editor/Xenko.Assets.Presentation/Xenko.Assets.Presentation.csproj
Fixed launching Spritesheet editor by properly embedding some resources in the assembly.
Fixes issue #38
=> Fixed launching Sprite sheet editor

BACKERS.md
vvvv is pretty abstract for people who don't know it, so i changed it to vvvv.org
=> [GitHub] changed abstract 'vvvv' to vvvv.org with link

sources/editor/Xenko.Assets.Presentation/View/ImageDictionary.xaml
Sorry for the mess, hopefully the last PR regarding that issue.
See @tebjan's [post](https://github.com/xenko3d/xenko/pull/161#issuecomment-417669772) for context.
=> [Editor] Match folder icon to tebjan's tweak of the original design

sources/engine/Xenko.Graphics/Buffer.cs, sources/engine/Xenko.Graphics/DescriptorSet.cs, sources/engine/Xenko.Graphics/DescriptorSetEntry.cs, sources/engine/Xenko.Graphics/Direct3D/CommandList.Direct3D.cs, sources/engine/Xenko.Graphics/Direct3D12/Buffer.Direct3D12.cs, sources/engine/Xenko.Graphics/OpenGL/CommandList.OpenGL.cs, sources/engine/Xenko.Graphics/ResourceBinder.cs
update of my previous pull request #123 which fixes #122 
@xen2 i fixed the signature for OpenGL and added a comment for DX12. most platforms don't seem to have proper uav support. solutions build properly here. tell me if something is missing.
=> [Graphics] Add buffer initial counter offset

sources/editor/Xenko.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml, sources/editor/Xenko.Assets.Presentation/Templates/ModelAssetTemplateWindow.xaml.cs, sources/presentation/Xenko.Core.Presentation/Themes/ExpressionDark/Theme.xaml
I resolved the issue #146, it was necessary to change the template of the radio button because the check icon was not being shown when the initial value was true, and about the UpdateStatus method, i removed because it is not necessary when used the GroupName in the elements.
=> [Editor] Updated checkboxes for radiobuttons in ModelAssetTemplateWindow

Xenko.xkpkg, sources/shared/SharedAssemblyInfo.cs
to have better local nuget distinction on dev machines.
=> version bump to 3.0.0.6

sources/engine/Xenko.Input/InputManager.State.cs, sources/engine/Xenko.Input/Windows/InputSourceWindowsDirectInput.cs, sources/engine/Xenko.Input/Windows/InputSourceWinforms.cs, sources/engine/Xenko.Input/Windows/KeyboardWindowsRawInput.cs
Fixing issue #159 
While this first push addresses the main issue mentioned there it makes the scene view hard to use because of the missing events mentioned lower in that same issue.
I'm investigating it, if you have any clue feel free to share !
n.b.:Those `Console.WriteLine` will be gone once I'm done of course.
=> [Input] Windows input fixes

sources/editor/Xenko.Assets.Presentation/View/ImageDictionary.xaml
This PR fix the issue #199.
**Evidences:**
=> [Editor] Wrong icon in Sprite Sheet

sources/engine/Xenko.Input/Windows/InputSourceWinforms.cs
Remove remaining log mentioned [here](https://github.com/xenko3d/xenko/issues/159#issuecomment-424399846).
Sorry about that !
=> [Input] console patch

sources/engine/Xenko.Graphics/FastTextRenderer.cs
... was hidden in constructor.
=> [Graphics] Exposed MatrixTransform as a property of FastTextRenderer

BACKERS.md
=> [Backers] Mike Jones represents MLF

sources/engine/Xenko.Graphics/Texture.Extensions2D.cs
seem to have missed to adjust a few overloads on PR #230
=> [Graphics] added 'options' parameter to texture 2d create methods

sources/engine/Xenko.Assets/Physics/ColliderShapeAssetCompiler.cs
#283 Compile ColliderShapeAsset if refered model files updated.(Like ModelAsset)
=> Properly update ColliderShapeAsset for #283

build/Xenko.sln, sources/editor/Xenko.Assets.Presentation/Xenko.Assets.Presentation.csproj, sources/editor/Xenko.Core.Assets.Editor/SupportedLanguage.cs, sources/editor/Xenko.Core.Assets.Editor/Xenko.Core.Assets.Editor.csproj, sources/editor/Xenko.GameStudio/Program.cs, sources/editor/Xenko.GameStudio/Xenko.GameStudio.csproj, sources/localization/Xenko.Assets.Presentation.pot, sources/localization/Xenko.Core.Assets.Editor.pot, sources/localization/Xenko.Core.Presentation.pot, sources/localization/Xenko.GameStudio.pot, sources/localization/extract_strings.bat, sources/localization/fr/Xenko.Assets.Presentation.fr.po, sources/localization/fr/Xenko.Core.Assets.Editor.fr.po, sources/localization/fr/Xenko.Core.Presentation.fr.po, sources/localization/fr/Xenko.GameStudio.fr.po, sources/localization/ja/Xenko.Assets.Presentation.ja.po, sources/localization/ja/Xenko.Core.Assets.Editor.ja.po, sources/localization/ja/Xenko.Core.Presentation.ja.po, sources/localization/ja/Xenko.GameStudio.ja.po, sources/presentation/Xenko.Core.Presentation/Xenko.Core.Presentation.csproj
I updated the extracted strings for all languages and added files for French.
The main goal of that pull-request is to see how Crowdin handles it: if it detects new files automatically, or with minimal manual interaction from their interface.
Note: most strings are not translated yet.
=> Add support for French in the editor

sources/core/Xenko.Core.Mathematics/Quaternion.cs
Fixed a spelling error in the Quaternion class.
=> Fixed spelling error

sources/engine/Xenko.Graphics/PipelineStateDescriptionWithHash.cs, sources/engine/Xenko.Physics/Collision.cs
Fairly small PR, changes speak for themselves.
see PR Details.
None reported.
=> [Misc] Exception prone basic functions

sources/editor/Xenko.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityCameraService.cs
Straightforward, see file changes.
Rotation used within camera logic is not kept up to date with pitch and yaw changes, this pr re-orders the code to avoid stutters caused by that.
none.
Mentioned by [star#7464 on discord](https://discordapp.com/channels/500285081265635328/500285081265635330/585476304288350239)
=> [Editor] Orbit editor camera fix

sources/engine/Xenko.Engine/Engine/Scene.cs
Fixes a bug occurring when removing an entity, which can end up firing code which also tries to remove that entity, generating an exception as the collection does not expect such a state.
Forced ``Entity.sceneValue`` and ``Scene.Parent`` to be taken care of before firing events related to them.
None reported.
Here's an example of the kind of issues where it would throw:
- Remove entityA from scene
- collection fires remove events [lifo](https://github.com/xenko3d/xenko/blob/5cee86cd3d8807c39446c07d0481348afd7c4131/sources/core/Xenko.Core/Collections/TrackingCollection.cs#L27), so first:
- SceneInstance event:[fires processors](https://github.com/xenko3d/xenko/blob/5cee86cd3d8807c39446c07d0481348afd7c4131/sources/engine/Xenko.Engine/Engine/SceneInstance.cs#L142)
- *some user side code …
=> [SceneManagement] Assign Entity.sceneValue before firing collection events

sources/editor/Xenko.Assets.Presentation/SceneEditor/HighlightRenderFeature.cs, sources/editor/Xenko.Assets.Presentation/SceneEditor/PickingRenderFeature.cs, sources/editor/Xenko.Assets.Presentation/SceneEditor/WireframeRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/Images/SubsurfaceScattering/SubsurfaceScatteringRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/Lights/ForwardLightingRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/MeshVelocityRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/SkinningRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/TransformRenderFeature.cs
just added a further null check, this happened a few times when working on shaders. the code after deals with null properly already.
=> Fixed null pointer exceptions in render features

README.md
=> Added xenko-community-projects to README.md

sources/engine/Xenko.Engine/Engine/Game.cs
=> Fix DataBaseFileProvider cast

samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/Core/Utils.cs, sources/engine/Xenko.Physics.Tests/CharacterTest.cs, sources/engine/Xenko.Physics.Tests/ColliderShapesTest.cs, sources/engine/Xenko.Physics.Tests/SkinnedTest.cs
Fix for #531
Missing namespaces included.
None.
Fix.
=> [Physics] Include namespaces of FastList from 531

samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Prefabs/Pile of boxes.xkprefab, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Instantiating prefabs.xkscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Linear Interpolation.xkscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Loading content.xkscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/MainScene.xkscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/AddingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/AmmoComponent.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/ChildEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/CloneEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/DeltaTimeDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingTheEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/InstantiatingPrefabsDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LerpDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LoadingContentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/MouseInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/RemoveEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/TutorialUI.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Windows/CSharpBeginner.Windows.xkpkg
Added 3 tutorials
- Lerp
- Loading content
- Instantiating prefabs
Docs will be updated in separate PR, but this PR has to be approved first.
Also update all private member to use format:  '_varName'
Extended C# basics template with 3 new tutorials.
Final tutorials for the C# beginners tutorials set
=> C sharp beginner extra tutorials

sources/engine/Xenko.Physics/Engine/PhysicsComponent.cs
See title.
None reported
See title
=> [Physics] Add buffer to set ignore collision pre-NativeObject creation

sources/engine/Xenko.Physics/Elements/CharacterComponent.cs
cherry picked from phr00ts fork.
fixes #574
=> CharacterComponent: fix orientation initialization

sources/engine/Xenko.Engine/Starter/AndroidXenkoActivity.cs, sources/engine/Xenko.Engine/Xenko.Engine.csproj
fix bug: issue
Xenko.Engine.csproj RootNamespace is set error, cause generate error Resource.designer.cs
this pr is fix this bug
#553
=> fix bug: Android Resource error #553 

sources/engine/Xenko.UI/Rendering/UI/UIRenderFeature.Picking.cs
This just fixes the compile error that is currently in master branch. Please make sure that the logic is correct, I just made assumption about what its supposed to be.
=> Fix compile issue in master.

sources/editor/Xenko.Core.Assets.Editor/Themes/ExpressionDark/TableflowView.ExpressionDark.normalcolor.xaml, sources/editor/Xenko.Core.Assets.Editor/Xenko.Core.Assets.Editor.csproj
This fixes a wpf compile error that was introduced when the DataGrid changes were merged.
=> Fix WPF resource dictionary errors.

build/Xenko.Android.sln, sources/engine/Xenko.Input/InputManager.cs, sources/engine/Xenko.Input/Windows/WinKeys.cs, sources/engine/Xenko.Input/Xenko.Input.csproj
Should hopefully stop some of the complaints in the TeamCity builds for Android and Windows builds.
Some Android Graphics Test projects were purged in commit b79f7160f2, so removed them from the Android solution.
@xen2 added `XENKO_INPUT_RAWINPUT`, you might want to double check the `#if` for `WinKeys` and the inclusion of `System.Windows.Forms` is corrected in this pull.
I'm assuming `XENKO_INPUT_RAWINPUT` is more general than `XENKO_PLATFORM_WINDOWS_DESKTOP && (XENKO_UI_WINFORMS || XENKO_UI_WPF)`, since `KeyboardWinforms` is referencing `WinKeys` and uses `XENKO_PLATFORM_WINDOWS_DESKTOP && (XENKO_UI_WINFORMS || XENKO_UI_WPF)`
=> Fix some build issues on TeamCity

sources/engine/Xenko.Input/Simulated/InputSourceSimulated.cs, sources/engine/Xenko.Input/Simulated/PointerSimulated.cs
just adds adds PointerSimulated.cs. That class is analogue to MouseSimulated.cs
This is still a WIP and also my first PR to stride, so please provide feedback on what to improve or change.
One thing i was unsure is the GUID: 
i created the GUI via VS and just inserted it here. Maybe something more has to be done with this GUID like registering it somewhere else.
It helps me to create pointer events from various sources. Imagine a special input-device like a touchframe, that doesn't come with a touch-driver but sends its events via network. With this class, you can create an easy adapter, that translates the incoming network events to pointer-events.
=> Pointersimulation

sources/core/Xenko.Core.Mathematics/Color3.cs, sources/core/Xenko.Core.Mathematics/Matrix.cs, sources/editor/Xenko.Assets.Presentation/AssetEditors/Gizmos/LightGizmo.cs, sources/editor/Xenko.Assets.Presentation/AssetEditors/Gizmos/TransformationGizmo.cs, sources/engine/Xenko.Engine/Engine/ModelComponent.cs, sources/engine/Xenko.Engine/Rendering/Compositing/ForwardRenderer.LightProbes.cs, sources/engine/Xenko.Graphics/Sprite3DBatch.cs, sources/engine/Xenko.Graphics/SpriteBatch.cs, sources/engine/Xenko.Graphics/UIBatch.cs, sources/engine/Xenko.Physics/ColliderShape.cs, sources/engine/Xenko.Physics/Engine/PhysicsDebugShapeMaterial.cs, sources/engine/Xenko.Rendering/Rendering/Images/AmbientOcclusion/AmbientOcclusion.cs, sources/engine/Xenko.Rendering/Rendering/Images/DepthOfField/DepthOfField.cs, sources/engine/Xenko.Rendering/Rendering/Images/LightShafts/LightShafts.cs, sources/engine/Xenko.Rendering/Rendering/Images/LightStreak/LightStreak.cs, sources/engine/Xenko.Rendering/Rendering/Images/SubsurfaceScattering/SubsurfaceScatteringBlur.cs, sources/engine/Xenko.Rendering/Rendering/Lights/LightAmbientRenderer.cs, sources/engine/Xenko.Rendering/Rendering/Lights/LightSpotTextureProjectionRenderer.cs, sources/engine/Xenko.Rendering/Rendering/Shadows/LightDirectionalShadowMapRenderer.cs, sources/engine/Xenko.Rendering/Rendering/Shadows/LightPointShadowMapRendererParaboloid.cs, sources/engine/Xenko.Rendering/Rendering/SortModeDistance.cs, sources/engine/Xenko.Rendering/Rendering/Sprites/SpriteRenderFeature.cs, sources/engine/Xenko.Rendering/Rendering/VisibilityGroup.cs, sources/engine/Xenko.UI/Engine/UIElementTransformLink.cs, sources/engine/Xenko.UI/Panels/Canvas.cs, sources/engine/Xenko.UI/Panels/StackPanel.cs, sources/engine/Xenko.UI/Rendering/UI/UIRenderFeature.cs, sources/engine/Xenko.UI/UIElement.cs
Minor performance improvement in the game engine.
~Reduce the number of constructor calls when copying the struct directly is applicable.~
Reduce redundant calculations where possible.
Pass structs by ref where applicable.
Foreach-loop on `VisualChildrenCollection` to avoid enumerator object allocations.
~Note that I've created new `Color3.Black` & `Color3.White` public fields. Not sure if you want this exposed, or keep it internal.~
A little more FPS can't hurt.
=> More minor performance improvement

sources/engine/Xenko.Engine/Engine/EntityTransformExtensions.cs
Convenience extension method to work with the entity tree.
People often have problems with building entity hierarchies by code.
=> [Engine] Added SetParent to EntityTransformExtensions

README.md
Fix wording, typos, more precise building guidelines and add a small troubleshoot section.
I removed ``3. Open <StrideDir>\samples\StrideSamples.sln and play with the samples.`` as I don't really think it's applicable to building guidelines specifically, feel free to reply back if you disagree.
If some of the stuff I have added could be improved feel free to reply below as well.
N/A
Lots of users still had trouble with building from source and reported on the forums or in the issues when those issues could have been avoided in the first place.
=> [Docs] Extend prereq and building guidelines

samples/Templates/Packs/PrototypingBlocks/PrototypingBlocks.csproj, samples/Templates/Packs/SamplesAssetPackage/SamplesAssetPackage.csproj, samples/Templates/Packs/mannequinModel/mannequinModel.csproj, samples/Tutorials/CSharpBeginner/CSharpBeginner.sln, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/CSharpBeginner.Game.csproj, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/AddingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/AmmoComponent.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/ChildEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/CloneEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/DeltaTimeDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingTheEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LerpDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LoadingContentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/MouseInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/RemoveEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/TutorialUI.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Windows/CSharpBeginnerApp.cs
Added a reference to the editor config. 
- Removed underscores for private variables.
- basic cleaning
=> Referenced editorconfig and cleaned up code C# beginner tutorials

sources/core/Stride.Core/ThreadThrottler.cs, sources/engine/Stride.Games/GameBase.cs
See title.
Very small doc changes, see files
#403 
Trying to make that API less obtuse.
=> [Game] Extend and fix property documentation around ThreadThrottler

sources/core/Stride.Core/ThreadThrottler.cs, sources/engine/Stride.Games/GameBase.cs
Calculations and comparisons are all based on the performance counter format now leading to more precise periods overall, even more so for cpus with lower tickrates. Added more ctor, methods to throttle in an fps format, clarified summaries.
#679
I doubt anyone cares enough about this for it to matter but it bothered me so yeah.
=> [Thread] More precise throttler

sources/engine/Stride.Input/Windows/GameControllerDirectInput.cs
DirectInput might report more objects than SharpDX sampling/polling supports, this PR ignores out of range data to avoid a game crash. 
To properly fix this would requires further investigation by someone with such a device at hand if it even really exists.
See issue #678 for more context.
#678
Work around a bug in a device, driver or wherever else this came from.
=> [Input] Work around DirectInput OutOfRange issue

sources/engine/Stride.Input/Windows/InputSourceWinforms.cs
Changes how the workaround for raw input operates to fix #686 
Again, still not exactly sure what's going on here but this work.
Fixes #686 
Previous related PR #181 which 'fixed' issue #159
Fixes/workaround a bug.
=> [Input] Workaround for gamestudio input

samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Keyboard input.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Mouse input.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Virtual buttons.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/ChildEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/DeltaTimeDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/KeyboardInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/MouseInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/TransformPositionDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/VirtualButtonsDemo.cs
Fixes some minor typos in the beginner sample project.
=> [Samples] Minor typo fixes

deps/assimp/include/assimp/types.h, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Animation/AnimationBlend.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Animation/AnimationStart.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/BasicCameraController.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/FpsCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/FreeCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/OrbitCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/SideScrollingCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Physics/DebugShapesRender.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Physics/PlayerController.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Utility/GameProfiler.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Utility/SceneStreaming.cs, sources/engine/Stride.Particles/Materials/UVBuilderScroll.cs, sources/engine/Stride.Shaders.Parser/ShaderMixinParser.cs, sources/engine/Stride.Shaders.Tests/GameAssets/Shaders/NonStageStreamTest.sdsl, sources/engine/Stride.UI/StripDefinition.cs, sources/engine/Stride.VirtualReality/GoogleVR/GoogleVR.cs, sources/presentation/Stride.Core.Presentation/Controls/VirtualizingTreePanel.cs, sources/tools/Stride.Importer.FBX/AnimationConverter.h
No engine affecting modifications in this pull.
Only minor fixes like removing trailing whitespaces in the script templates, capitalize the first letter in the comments in the script templates, remove some pointless doubled-up semi colons.
=> Minor adjustment to prettify code

samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/CloneEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/KeyboardInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/VirtualButtonsDemo.cs
Change `KeyboadInputDemo`'s `BlueTeapot` rotation code from `RotationEulerXYZ` to `Quaternion` and update code comments
#725 
Fix bug
=> Fix c# beginner's KeyboardInputDemo code & update code comment

sources/engine/Stride.Rendering/Rendering/Materials/MaterialSpecularMicroFacetModelFeature.cs
The Environment property wasn't checked. 
#735
=> [Rendering] Fixed equality of MaterialSpecularMicroFacetModelFeature

samples/Games/JumpyJet/Assets/Shared/Pipe Set.sdprefab, samples/Games/JumpyJet/JumpyJet.Game/BackgroundSection.cs, samples/Games/JumpyJet/JumpyJet.Game/CharacterScript.cs, samples/Games/JumpyJet/JumpyJet.Game/PipesScript.cs, samples/Games/JumpyJet/JumpyJet.Game/UIScript.cs
Refactor the code, fix some logic error (that I see during the walkthrough) and fix bugs from collider detection
I'll just focus on the bugs I fix, refactoring and fixing logic error are just trivial and does not break the game
- The original JumpyJet project has an overlapping collider on the PipeSet prefab and for some reason when the player goes through that overlapped area, the collision detection sometimes(?) does not broadcast `GameOverEventKey`.
And for the same reason, sometimes, too, the score will be increased to 1 right on game restarted when the player dies on the Pipe
**Overlapping collider**
**Player goes through that overlapping area**
**Player gains a score on game restarted when it dies on the Pipe**
- So what I do now is to move the `PassedTrigger` collider past the pipe …
=> Fix JumpyJet collision detection

samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/GraphicsCompositor.sdgfxcomp, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Adding a component.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Child entities.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Cloning entities.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/DeltaTime.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Getting a component.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Getting the entity.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Instantiating prefabs.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Keyboard input.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Linear Interpolation.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Loading content.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Mouse input.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Properties.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Removing entities.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/TransformPosition.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/Basics/Virtual buttons.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/Scenes/MainScene.sdscene, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/CSharpBeginner.Game.csproj, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/InstantiatingPrefabsDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/VirtualButtonsDemo.cs
Some final details of the C# beginner template that I came across when recording tutorials.
I will do another PR that updates the docs with youtube embedded videos
=> Last C# beginner tutorials update

sources/engine/Stride.Engine/Engine/EntityManager.cs, sources/engine/Stride.Rendering/Rendering/RenderContext.cs
Allows to call `SceneInstance.Draw` from user code.
See #805 - we're not making use of a scene system.
=> Make some APIs public to allow custom drawing of a scene instance

sources/engine/Stride.Engine/Rendering/ModelRenderProcessor.cs
Changing the `ModelComponent.IsShadowCaster` property while the engine is running had no effect.
=> [Engine] Reevaluate active render stages when changing the shadow caster property

sources/buildengine/Stride.Core.BuildEngine.Common/SiliconStudio.BuildEngine.Common.csproj.DotSettings, sources/core/Stride.Core.Design/SiliconStudio.Core.Design.csproj.DotSettings, sources/core/Stride.Core.Reflection/SiliconStudio.Core.Reflection.csproj.DotSettings, sources/core/Stride.Core.Yaml/SiliconStudio.Core.Yaml.csproj.DotSettings, sources/editor/Stride.Assets.Presentation/SiliconStudio.Stride.Assets.Presentation.csproj.DotSettings, sources/editor/Stride.Core.Assets.Editor/SiliconStudio.Assets.Editor.csproj.DotSettings, sources/editor/Stride.GameStudio/SiliconStudio.Stride.GameStudio.csproj.DotSettings, sources/engine/Stride.Physics/SiliconStudio.Stride.Physics.csproj.DotSettings, sources/presentation/Stride.Core.Presentation/SiliconStudio.Presentation.csproj.DotSettings, sources/tools/Stride.Core.Translation.Extractor/SiliconStudio.Translation.Extractor.csproj.DotSettings
removed some old files that contain the siliconstudio name
=> deleted old siliconstudio files

sources/engine/Stride.UI/Controls/ScrollingText.cs
See PR #845, this PR supersedes that one.
=> [UI] Fix ScrollingText infinite loop

sources/engine/Stride.Engine/Engine/Processors/ScriptSystem.cs
Fix binary operation for setting `AsyncScript`'s priority in the scheduler.
Fixes #859
=> Fix AsyncScript priority handling

sources/engine/Stride.Assets/Materials/MaterialAssetCompiler.cs
Fixes material being black when loading older project files.
The binary change was introduced with 2f96f724438e62c1d5716b3c4d70518499d1a4d8
=> Bumped version of material asset binary serializer

sources/tools/Stride.Importer.FBX/MeshConverter.cpp
Imports tangents when they are included within the FBX file
None reported
=> [Asset] Fbx import tangent

sources/engine/Stride.Rendering/Rendering/Materials/ComputeColors/ComputeShaderClassColor.cs, sources/engine/Stride.Rendering/Rendering/Materials/ComputeColors/ComputeShaderClassScalar.cs
Swapped the documentation for ComputeShaderClassColor/ComputeShaderClassScalar 
#872 
Fixes the documentation
- [ X] Docs change / refactoring / dependency upgrade
- [ X] My change requires a change to the documentation.
=> #872 Corrected ComputeShaderClassColor/ComputeShaderClassScalar documentation

sources/core/Stride.Core/Threading/ThreadPool.cs
See #913, this temporary while I investigate the issue further
#913
System-wide freeze
=> [Threading] Temporary workaround for #913

sources/tools/Stride.VisualStudio.Package.Tests/IntegrationTests.cs
=> Adds missing ifdef to VS integration test so all tests compile without an error

sources/engine/Stride.Input/InputManager.cs
The previous PR introduced a compiler error. Not sure why I didn't catch it when running the tests locally :/
=> [Input] Fixes compile error introduced in previous commit

sources/engine/Stride.Rendering/Rendering/Images/ImageEffect.cs
Allows to read the in- and outputs of an image effect
=> [Rendering] Allows to read the in- and outputs of an image effect.

sources/engine/Stride.Rendering/Rendering/Images/ColorTransforms/ColorTransformGroup.cs
The previous code relied on `UpdateEffect` returning true when the set of enabled transforms changed, however that was not the case when the generated shader stayed the same.
https://github.com/vvvv/VL.Stride/issues/371
=> [Rendering] Fixes crash when enabling a color transform during runtime

sources/engine/Stride.Games/GameWindow.cs, sources/engine/Stride.Games/SDL/GameFormSDL.cs, sources/engine/Stride.Games/SDL/GameWindowSDL.cs, sources/engine/Stride.Graphics/SDL/Window.cs
This PR collects some minor modifications to the (SDL based) game window.
=> [Games] A few minor window related additions (SDL)

sources/engine/Stride.Graphics/Direct3D/SharpDXInterop.cs
Fix for #976, didn't test DX12.
=> [Graphics] Fixed isSRgb parameter for DX12

sources/launcher/Stride.Launcher/ViewModels/PackageVersionViewModel.cs
Uninstalling a build should remove all of the `Stride.*` packages for that build version, not just `Stride.GameStudio`.
Added additional logic to `/sources/launcher/Stride.Launcher/ViewModels/PackageVersionViewModel.cs`. When the deleted package ID is one of the main package IDs, then remove all of its dependencies (where IDs are like `Stride.*` or `Xenko.*`) for that particular build version.
Fixes #992.
This will remove the unneeded files from `C:\Users\<USERNAME>\.nuget\packages\` and it will save significant amounts of disk space for people who frequently update Stride builds.
=> Remove GameStudio dependencies when a build is uninstalled

sources/engine/Stride.Assets/Templates/ProjectTemplateGeneratorHelper.cs
Updating the template generator to make life easier for people who don't have .NET Framework build tools installed, just .NET 5 SDK.
N/A
=> Set TargetFramework to net5.0-windows for new projects

sources/editor/Stride.Assets.Presentation/Stride.Assets.Presentation.csproj
Bumping up the version on System.Reactive (and System.Reactive.Linq) which targets net5.0 and there's no longer an issue with it not being resolved correctly.
#786
#894
=> Upgrade System.Reactive so that it's resolved correctly

sources/engine/Stride.UI/Engine/UIComponent.cs, sources/engine/Stride.UI/Rendering/UI/RenderUIElement.cs, sources/engine/Stride.UI/Rendering/UI/UIRenderFeature.cs, sources/engine/Stride.UI/Rendering/UI/UIRenderProcessor.cs
=> Revert "Add sampling option to UIComponent"

sources/core/Stride.Core.Design/Reflection/AssemblyContainer.cs
There's no way to load such assembly from byte array. Therefor fallback to load from file.
#1066
=> [Reflection] Loads mixed-mode assemblies containing fixups from file instead of from byte array

sources/assets/Stride.Core.Assets/Stride.Core.Assets.csproj, sources/core/Stride.Core.Tasks/Stride.Core.Tasks.csproj, sources/targets/Stride.Core.Cpp.props, sources/targets/Stride.Core.props
Not sure I did something completely wrong but with the following changes I could successfully compile again with latest VS (16.10.3). I was working on the `master-4.0` branch.
=> [Build] Couple of fixes to get it building with latest Visual Studio

sources/core/Stride.Core.Mathematics/Vector2.cs, sources/core/Stride.Core.Mathematics/Vector3.cs, sources/core/Stride.Core.Mathematics/Vector4.cs
See #1089 
Had to create a new PR as I don't have write access, fixing a couple of stuff we talked about over there.
=> [Math] Added a Goto method to Vectors (cont. from @VexedUXR in #1089)

sources/engine/Stride.Physics.Tests/CharacterTest.cs, sources/engine/Stride.Physics/Collision.cs, sources/engine/Stride.Physics/Elements/CharacterComponent.cs, sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs, sources/engine/Stride.Physics/Engine/PhysicsComponent.cs, sources/engine/Stride.Physics/Simulation.cs
See commit names, self explanatory.
None reported over in github
Fixes issues.
Is related to PR #1100
=> [Physics] Couple of minor collision related fixes following #1100

sources/engine/Stride.Engine/Engine/Processors/InstancingProcessor.cs
Fixes null exception in InstancingProcessor when no ModelComponent is present
Just a null check.
=> [Engine] Fixes null exception in InstancingProcessor

sources/core/Stride.Core/PlatformFolders.cs, sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Android/ProjectExecutable.Android.ttproj, sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Android/Resources/Resource.Designer.cs.t4
This PR backports Android platform fixes from 4.1-beta to the 4.0 branch. Please see PR's #1146 and #1018 (backport courtesy of @Basewq) for more information.
=> [Backport] Android platform fixes

sources/engine/Stride.Physics/Elements/CharacterComponent.cs
Gets the linear velocity from the kinematic character in the character component instead of having to compute it separately
#1127
=> Added linear velocity for character component

sources/core/Stride.Core.Reflection/TypeDescriptors/ArrayDescriptor.cs, sources/core/Stride.Core.Reflection/TypeDescriptors/ListDescriptor.cs, sources/editor/Stride.Core.Assets.Editor/View/DefaultPropertyTemplateProviders.xaml, sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/ArrayItemTemplateProvider.cs, sources/editor/Stride.Core.Assets.Editor/View/TemplateProviders/ArrayTemplateProvider.cs, sources/presentation/Stride.Core.Presentation.Quantum/Presenters/ItemNodePresenter.cs, sources/presentation/Stride.Core.Quantum/GraphNodeBase.cs, sources/presentation/Stride.Core.Quantum/Internal/Content.cs, sources/presentation/Stride.Core.Quantum/ObjectNode.cs
Fix array support for game editor
=> Fix array support for game editor

README.md
VS 2022 is now a requirement afaict so I updated the requirements listed in the readme and also added a couple of things we stumbled onto.
None
=> [Doc] Update build instructions

sources/launcher/Stride.Launcher/Resources/Urls.Designer.cs, sources/launcher/Stride.Launcher/Resources/Urls.resx
Links url updated
Fixes #1225
Links updated to new content
=> Roadmap and forum chat links updated

sources/engine/Stride.Input/SDL/KeyboardSDL.cs
Add missing key mapping for KeyboardSDL
#1182
=> Add missing sdl keys

sources/engine/Stride.Rendering/Rendering/Lights/RenderLight.cs
Reverts #1275, see latest comment over there
=> Revert "Expose RenderLight bounding boxes"

sources/assets/Stride.Core.Assets.Tests/TestBase.cs, sources/assets/Stride.Core.Assets.Tests/TestPackage.cs, sources/assets/Stride.Core.Assets/Compiler/PackageCompiler.cs, sources/core/Stride.Core.Serialization/Serialization/UrlReferenceHelper.cs, sources/core/Stride.Core.Yaml/Serialization/YamlAssemblyRegistry.cs, sources/engine/Stride.Games/Android/GamePlatformAndroid.cs, sources/engine/Stride.Games/Desktop/GamePlatformDesktop.cs, sources/engine/Stride.Games/GameBase.cs, sources/engine/Stride.Games/GameContextFactory.cs, sources/engine/Stride.Games/iOS/GamePlatformiOS.cs, sources/engine/Stride.Rendering/Rendering/Shadows/LightPointShadowMapRendererParaboloid.cs, sources/engine/Stride.Shaders.Tests/TestParallelShaderMixer.cs, sources/engine/Stride.VirtualReality/OculusOVR/OculusOverlay.cs, sources/shared/ConsoleProgram.cs, sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/FreeImageWrapper.cs
See changes, those were reported through the build warnings and seemed significant enough to deal with.
=> [Misc] Fix minor issues

README.md
Added open collective backers badge on readme
=> Added open collective backers badge on readme

sources/engine/Stride.Engine/Rendering/ModelRenderProcessor.cs
follow up to #1343
Just a cherry-pick.
=> [Materials] Fixes render stage evaluation if the transparency changes

sources/core/Stride.Core.Mathematics/Matrix.cs, sources/engine/Stride.Engine/Engine/Processors/TransformProcessor.cs, sources/engine/Stride.Graphics/SpriteBatch.cs, sources/engine/Stride.Graphics/UIBatch.cs, sources/engine/Stride.VirtualReality/DummyDevice.cs
Passing operations to numerics where appropriate to benefit from SIMD, only did it for the two most commonly used function right now, we could look into writing it explicitly for column major later.
Also small cleanup for `TransformProcessor`.
=> [Math] Optimize Matrix mult and invert

sources/engine/Stride.Physics/Elements/RigidbodyComponent.cs
Who wrote that garbage ? Oh wait ... that's me !
=> [Physics] Fix Rigidbody memory leak

sources/engine/Stride.Rendering/Rendering/Images/DepthOfField/DepthOfField.cs
=> [Rendering] Fixes crash when changing DoF quality at runtime

sources/engine/Stride.Engine/Rendering/ModelRenderProcessor.cs
=> [Rendering] Fixes null exception on first frame. #1343

samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/05_Async/AsyncCollisionTriggerDemo.cs, samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/05_Async/AsyncWebApi.cs, samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/09_FirstPersonCamera/FirstPersonCamera.cs, samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Game/10_ThirdPersonCamera/ThirdPersonCamera.cs
Small improvements to intermediate tutorial code found during recording.
=> C#intermediate tutorial

samples/Templates/Packs/SamplesAssetPackage/Assets/Materials/board1B.sdmat, samples/Tutorials/CSharpIntermediate/CSharpIntermediate/Assets/Scenes/08_Audio/Start-Audio.sdscene, samples/Tutorials/CSharpIntermediate/CSharpIntermediate/CSharpIntermediate.Windows/CSharpIntermediate.Windows.sdpkg
Small improvement to the audio start scene as well as a fix in a weird texture glow.
=> C# intermediate tutorial fixes: remade audio startscene. remove specular from wood

sources/engine/Stride.Input/SDL/PointerSDL.cs
See initial bug report here: https://discourse.vvvv.org/t/multiple-multitouch-screens-crashes-on-fast-touches/20683/5
=> Fixes key not found exception when working with multiple devices

.editorconfig
Make editing projects easier.
Guess what Visual Studio does to the poor people whose indentation is set to Tabs by default...
=> Make editing projects easier.

README.md
Improving build instructions
Steps update
GitHub Zip file doesn't support LFS at the  moment
=> update: Instructions improvements

samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/FpsCamera.cs
`Yaw` will always be equal to `desiredYaw` as they are both private and set to each other at line 105, therefore the entire logic from 92-103 doesn't actually do anything. Same with pitch. Might as well cut it out entirely to avoid confusing users with it.
None.
=> [Template] FPS remove unused logic

sources/core/Stride.Core.Tests/TestProfiler.cs, sources/core/Stride.Core/Native/CoreNative.c, sources/core/Stride.Core/Native/NativeInvoke.cs, sources/core/Stride.Core/ThreadThrottler.cs, sources/engine/Stride.Audio.Tests/TestAudioEngine.cs, sources/engine/Stride.Audio.Tests/TestDynamicSoundEffectInstance.cs, sources/engine/Stride.Audio.Tests/TestInvalidationAudioContext.cs, sources/engine/Stride.Audio.Tests/TestSoundEffect.cs, sources/engine/Stride.Audio.Tests/TestSoundEffectInstance.cs, sources/engine/Stride.Audio/DynamicSoundSource.cs, sources/engine/Stride.Games/GameBase.cs, sources/engine/Stride.Games/GraphicsDeviceManager.cs, sources/engine/Stride.Video/Android/MediaCodecExtractorBase.cs, sources/engine/Stride.Video/FFmpeg/FFmpegMedia.cs
This PR removes native ThreadSleep function and replaces with .NET Thread.Sleep
#1394
=> Replace native ThreadSleep with .NET Thread.Sleep

sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameRenderModeService.cs, sources/editor/Stride.Assets.Presentation/CurveEditor/ViewModels/RotationComponentCurveViewModel.cs, sources/editor/Stride.GameStudio/AssetEditorsManager.cs, sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/GraphViewModel.cs, sources/presentation/Stride.Core.Presentation/Controls/VirtualizingTreePanel.cs, sources/presentation/Stride.Core.Quantum/References/ObjectReference.cs, sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/MetadataModels.cs, sources/tools/Stride.TextureConverter/Frontend/TexAtlas.cs
Addressing the issues reported in #1543, will describe each changes below.
Fixes #1543
=> [Misc] Addressing PVS report

sources/engine/Stride.Engine/Engine/Entity.cs
Fixed an issue preventing the solution from compiling due to a recent change in Entity.cs.
=> Updated Entity.cs

sources/core/Stride.Core.Mathematics/Int2.cs
Changed an error in the comments for Int2
=> Fix documentation error on Int2

sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs
As recommended by Microsoft this PR uses the flip model in Direct3D11. A rather good overview with useful information & links can be found [here](https://walbourn.github.io/care-and-feeding-of-modern-swapchains/).
#1344 
Comparison of the example game
without flip model
with flip model
In another test where we only rendered a white quad in 1920x1200 (no post-effects) the GPU usage dropped from 20% to 0%.
=> Use flip model in Direct3D11

sources/core/Readme.md
I looked through the classes in the projects under `sources/core` and provided a high level description into each of them. This should help raise awareness on what's in there.
N/A
It's often not easy to guess what lies where without spending some time digging into the code, which can sometimes be confusing.
=> [Docs] Add a Readme with information on what's in the Core folder

sources/editor/Stride.Assets.Presentation/AssetEditors/ScriptSourceCodeResolver.cs
Changes to the `ScriptSourceCodeResolver` to account for some shortcomings of the Roslyn API in regards of .NET 6.0 projects. 
It seems that Roslyn, for some reason, cannot find types in references Nuget packages causing some problems in checking for inheritance of script types. This PR updates the code to use Reflection instead of Roslyn API which is more robust in this context and also fixes the problem of missing drag-drop for script components.
#1466
This enables again Drag and Drop of Script components to the scene.
=> Fix #1466: adding scripts by dragging

sources/engine/Stride.VirtualReality/Stride.VirtualReality.csproj
This broke with the merge of PR #1428 because these lines of code where added after #1428 was created.
=> [Build] Fixes location of native openxr_loader.dll in Stride.VirtualReality package

sources/assets/Stride.Core.Assets/Yaml/CollectionWithIdsSerializerBase.cs, sources/core/Stride.Core.Serialization/Serialization/IUrlReference.cs, sources/core/Stride.Core.Serialization/Serialization/UrlReferenceBase.cs, sources/core/Stride.Core/Collections/MultiValueSortedDictionary.cs, sources/editor/Stride.Editor/EditorGame/Game/EditorServiceGame.cs, sources/engine/Stride.Graphics/Buffer.Structured.cs, sources/engine/Stride.Graphics/DeviceCreationFlags.cs, sources/engine/Stride.Graphics/GeometricPrimitives/GeometricPrimitive.cs, sources/engine/Stride.Input/VirtualButton/VirtualButtonGroup.cs, sources/engine/Stride.Particles/Initializers/ParticleInitializer.cs, sources/engine/Stride.Particles/ParticlePool.cs, sources/engine/Stride.Rendering/Rendering/Images/PostProcessingEffects.cs, sources/engine/Stride.Rendering/Rendering/Images/SubsurfaceScattering/SubsurfaceScatteringBlur.cs, sources/engine/Stride.Rendering/Rendering/Materials/Hair/LightAttenuationFunction/MaterialHairLightAttenuationFunctionDirectional.cs, sources/engine/Stride.Rendering/Rendering/Materials/Hair/MaterialSpecularHairModelFeature.cs
=> Fix XML warnings

deps/HtmlRenderer/HtmlRenderer.WPF.dll, deps/HtmlRenderer/HtmlRenderer.WPF.pdb, deps/HtmlRenderer/HtmlRenderer.dll, deps/HtmlRenderer/HtmlRenderer.pdb
This PR removes unused dependency from stride project. 
#1394
=> [deps] - Remove unused HtmlRenderer

sources/engine/Stride.Rendering/Rendering/Images/SubsurfaceScattering/SubsurfaceScatteringBlur.cs
=> Fix XML documentation

sources/assets/Stride.Core.Assets/Compiler/AssetCompilerBase.cs, sources/assets/Stride.Core.Assets/PackageReferenceBase.cs, sources/engine/Stride.Particles/Materials/ParticleMaterial.cs, sources/engine/Stride.Particles/Materials/UVBuilder.cs, sources/engine/Stride.Rendering/Extensions/SimpleExtensions.cs, sources/engine/Stride.Rendering/Rendering/ComputeEffect/ComputeEffectShader.cs, sources/engine/Stride.Rendering/Rendering/ConstantBufferOffsetReference.cs, sources/engine/Stride.Rendering/Rendering/EffectDescriptorSetReference.cs, sources/engine/Stride.Rendering/Rendering/FrameResourceGroupLayout.cs, sources/engine/Stride.Rendering/Rendering/Images/ImageEffectShader.cs, sources/engine/Stride.Rendering/Rendering/Images/ImageScaler/ImageScaler.cs, sources/engine/Stride.Rendering/Rendering/Images/SphericalHarmonics/SphericalHarmonicsRendererEffect.cs, sources/engine/Stride.Rendering/Rendering/Lights/RenderLightCollection.cs, sources/engine/Stride.Rendering/Rendering/Materials/MaterialRenderFeature.cs, sources/engine/Stride.Rendering/Rendering/Materials/MaterialStreamType.cs, sources/engine/Stride.Rendering/Rendering/MeshRenderFeature.cs, sources/engine/Stride.Rendering/Rendering/RenderDrawContext.cs, sources/engine/Stride.Rendering/Rendering/RootEffectRenderFeature.cs, sources/engine/Stride.Rendering/Rendering/SkinningRenderFeature.cs, sources/engine/Stride.Rendering/Rendering/TransformRenderFeature.cs, sources/engine/Stride.Rendering/Rendering/ViewResourceGroupLayout.cs
XML Document fixes for the new website
Adjusted references or fixed wrong XML Documents
Helps #1681
=> [Docs] Fix xml docs

build/Stride.VisualStudio.sln, build/Stride.build, build/Stride.sln
=> Separate VisualStudio projects from main solution

README.md
=> Docs: Readme, update Community Projects link

sources/editor/Stride.Samples.Templates/ThisPackageVersion.DevBuild.cs, sources/editor/Stride.Samples.Templates/ThisPackageVersion.PackageBuild.cs
Bump samples, forcing a new package upgrade to include fixes like #1618 
#1618
=> [Samples] Bump samples version

README.md
Redundant badge removed and missing `lfs` added
Docs improvement
=> Readme.md update - Improving readme based on the community feedback

README.md, sources/core/Stride.Core/IServiceRegistry.cs, sources/core/Stride.Core/ServiceRegistry.cs
XML comments improvements
Added and updated comments
Stride Docs improvements
=> Xml comments improvements

sources/assets/Stride.Core.Assets/VSProjectHelper.cs
Replaces the message 
`The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.`
With:
Not the most elegant solution, both in terms of having to parse strings and of where we end up showing it. 
Can't do much about the former, build tool doesn't have the API to build anything less fragile. 
And as for the latter, we would have to rewrite the four callers to `RestoreNugetPackages` to display a popup window or such. Let's get this out first and we'll figure out the rest when needed.
There is already a similar check going on before projects are loaded (https://github.com/stride3d/stride/blob/master/sources/editor/Stride.GameStudio/Program.cs#L230), but that is strictly for making sure that the …
=> [Project] Show custom message for users with outdated dotnet version

sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
Looks like sorting was already in declaration order pre-github, but `MemberInfo` became obsolete and is never assigned.
```cs
public class MemberOrderTest : EntityComponent
{
public float z, y, x;
public float a, b, c;
}
```
None logged afaict.
=> [Editor] PropertyGrid, fix member sorting by declaration/token

samples/Graphics/SpriteFonts/SpriteFonts.Game/FontRenderer.cs
There was a typo in one of the samples.
renamed the referenced method to use the right call.
#1796
=> Fixed SpriteFont sample

sources/editor/Stride.Core.Assets.Editor/ViewModel/AssetCollectionViewModel.cs
fix #1803 , format some lines
the Files Parameter was null when adding through right click in Studio
I dont know how to test why it was originally added in https://github.com/stride3d/stride/commit/3eac07770518617c8c047821f32428aa863f8c8b
Could someone confirm that this is still working?
#1803
=> Repair NPE on add Asset

README.md
It's a great resource and deserves a spot in the readme. What do you think?
Also two minor typos.
It appears in the readme like this:
* [Awesome Stride - Huge List of Stride Resources](https://github.com/Doprez/Awesome-Stride)
=> Adds Awesome Stride to readme

sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/Views/AddItemWindow.xaml, sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/Views/ObjectBrowserUserControl.xaml.cs, sources/editor/Stride.Core.Assets.Editor/Components/TemplateDescriptions/Views/TemplateBrowserUserControl.xaml, sources/editor/Stride.Core.Assets.Editor/Themes/generic.xaml, sources/presentation/Stride.Core.Presentation.Graph/Themes/generic.xaml
Fix some xaml errors
https://github.com/stride3d/stride/issues/1817
https://github.com/stride3d/stride/issues/1818
https://github.com/stride3d/stride/issues/1819
https://github.com/stride3d/stride/issues/1820
IDE highlights errors. It should be fixed
=> Fix some xaml errors

samples/Tutorials/CSharpBeginner/CSharpBeginner/Assets/readme.sdraw, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/AddingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/ChildEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/CloneEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/DeltaTimeDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingAComponentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/GettingTheEntityDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/InstantiatingPrefabsDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/KeyboardInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LerpDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/LoadingContentDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/MouseInputDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/PropertiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/RemoveEntitiesDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/TransformPositionDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/VirtualButtonsDemo.cs, samples/Tutorials/CSharpBeginner/CSharpBeginner/Resources/readme.txt
This just adds some comments to the code to point the user to the online tutorials if they didnt know. There is also a readme file with a small amount of extra info.
https://github.com/stride3d/stride/issues/1751
This should help some new users who may not have known about the online tutorials.
=> Add more documentation for beginner tutorial

sources/engine/Stride.Physics/Elements/CollisionFilterGroups.cs, sources/engine/Stride.Physics/Simulation.cs
Adds flags to change how ray tests are performed, mainly allowing users to ignore back-faces.
None logged.
=> [Physics] Add ray test flags

sources/core/Stride.Core/DataMemberMode.cs
Fix a typo in the Comment of DataMemberMode Assign
Only 1 Typo
N/A
=> field typo

sources/engine/Stride.Physics/Elements/CollisionFilterGroups.cs
=> [XML Comment] Minor updates on EFlags in CollisionFilterGroups.cs

sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityCameraService.cs, sources/editor/Stride.Assets.Presentation/SceneEditor/SceneEditorSettings.cs
Just lets you change the keybinding for this in the editor settings. Defaults to the old hardcoded bindings so it should be unnoticed by most.
=> Add editor settings for the camera speed increase/decrease hotkeys

samples/UI/GameMenu/GameMenu.Game/UISceneBase.cs, samples/UI/UIElementLink/UIElementLink.Game/UISceneBase.cs, samples/UI/UIParticles/UIParticles.Game/UISceneBase.cs
=> [Sample] Replace deprecated GetServiceAs calls

.github/pull_request_template.md
See title and content.
See last few days.
=> [Github] Update pull request template to ensure users tried out their changes

sources/core/Stride.Core.Mathematics/Vector3.cs
Max had an incorrect xml document
max is big not small.
Sizes confuse me greatly.
=> Fixed small xml docs mistake

README.md
This has been discussed a fair bit, will be updating the wiki entry this links to shortly
=> [Docs] Move bounty paragraph to a more prominent spot

README.md
Adds some info that should prevent common pitfalls for newcomers and developers who are less experienced with Git.
Supersedes PR #1497 and incorporates the review suggestions from it.
Helps some newcomers.
=> [Readme] Some additional info for building Stride from source

samples/Tutorials/CSharpBeginner/CSharpBeginner/CSharpBeginner.Game/Code/PropertiesDemo.cs
A previous PR fixed the issue mentioned here
=> [Docs] Update PropertiesDemo.cs

sources/engine/Stride.Shaders.Parser/ShaderLinker.cs, sources/engine/Stride.Shaders.Tests/TestShaderReflection.cs
Negative values are represented as unary expressions. This commit adds support for unary expressions when reading the default value of a parameter. In case an initializer expression is not supported / can't be evaluated (for example `float x = 3 + 4;`) the `DefaultValue` property is set to `null`, leaving it up to the consumer to deal with it.
Fixes issue #1963
Replacement for #1967 
As outlined in #1967 the handling of negative values didn't work at all. Instead of changing the shader grammar this PR fixes the offending code itself.
=> [Shaders] Fixes `EffectValueDescription.DefaultValue` for negative values

sources/README.md
=> Add information about Irony.GrammarExplorer project

samples/Templates/VRSandbox/VRSandbox/VRSandbox.Game/VRGame.cs, samples/Templates/VRSandbox/VRSandbox/VRSandbox.Windows/VRSandboxApp.cs
Changes are fairly straightforward, see comments over there
None reported on github.
=> [VR] Remove framecap from VR sample

Directory.Packages.props, sources/buildengine/Stride.Core.BuildEngine/Stride.Core.BuildEngine.csproj, sources/core/Stride.Core.Tests/Stride.Core.Tests.Android.csproj, sources/core/Stride.Core.Tests/Stride.Core.Tests.iOS.csproj, sources/launcher/Stride.Launcher/Stride.Launcher.csproj, sources/metrics/Stride.Metrics/Stride.Metrics.csproj, sources/tools/Stride.PublicApiCheck/Stride.PublicApiCheck.csproj
Continuation of #2045, where a few projects were missed.
=> [Build] Use central package management  - missed a couple of projects

.gitignore
=> [Project] GitIgnore Rider cache/user config

sources/engine/Stride.Physics/Shapes/BoxColliderShape.cs
=> [Physics] Fix inconsistent box2D collision, see #1707 and #2019

sources/engine/Stride.Assets.Tests2/Stride.Assets.Tests2.csproj, sources/engine/Stride.Graphics/SDL/Application.cs, sources/engine/Stride.Graphics/SDL/Window.cs, sources/engine/Stride.UI.Tests/Layering/EditTextTests.cs, sources/engine/Stride.UI.Tests/Layering/TextBlockTests.cs, sources/engine/Stride.VirtualReality/OpenVR/OpenVR.cs, sources/tools/Stride.ProjectGenerator/Stride.ProjectGenerator.csproj
=> [Build] Fix misc warnings

sources/Directory.Packages.props, sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj
=> [Build] Fix VSPackage build

sources/editor/Stride.Core.Assets.Editor/Module.cs, sources/presentation/Stride.Core.Presentation.Quantum/ViewModels/NodeViewModel.cs
Fixes #2194
Regression was introduced by #2167 (more precisely commit b389a6f53cabfcd4eb95672d0acb0e861512fdb5).
=> [Presentation] Fix issue with binding quantum nodes when associated name is not found

sources/core/Stride.Core.Design/IO/UPath.cs, sources/engine/Stride.Assets/Media/SoundAssetCompiler.cs, sources/engine/Stride.Assets/Media/VideoAssetCompiler.cs, sources/engine/Stride.Assets/SpriteFont/Compiler/SignedDistanceFieldFontImporter.cs, sources/engine/Stride.Assets/ToolLocator.cs
This method is being used to locate ffmpeg program or msdfgen. If OS is not Windows, it simply checks whether the program is installed and returns path (example result : UFile(/usr/bin/ffmpeg))
=> Adjust ToolLocator for all platforms

sources/README.md
These projects do not exist, but also I did not found information about those in the past (xenko engine)
=> fix: Update README.md

sources/native/Stride.Native.targets
=> Fix for PR #2112

sources/engine/Stride.Engine/Engine/Game.cs, sources/engine/Stride.Games/GameBase.cs
Reverts stride3d/stride#2230 - needs additional work before prod
=> Revert "fix: Add possibility to add ScriptComponent before running game"

THIRD PARTY.md
Fixes the URL of one of the third party links.
https://github.com/stride3d/stride/issues/2229
=> fix opentk link

CODE_OF_CONDUCT.md, README.md
- README.md links corrected and minor grammar updates.
- CODE_OF_CONDUCT.md file added so we can see it on the top. I will remove it from the README.md itself so it is not duplicated in the next PR.
Minor GitHub Docs improvements.
Docs updates.
=> README.md updates

sources/core/Stride.Core.Serialization/Serialization/Contents/ContentManager.cs
The previous error did not explain the problem very clearly, this attempts to help with readability.
https://github.com/stride3d/stride/issues/2178
Trying to make things easier to read for newcomers is a benefit.
=> Reworded content load exception message

.github/pull_request_template.md
Simplified the PR template to reduce the amount of nonsense people have to deal with.
- `Description` has been removed, most issues could be explained entirely through `PR Details` while more complex ones would just split it into paragraphs anyway.
- `Motivation and Context` is fairly obvious from the title or description of the PR.
- Added a link to the documentation about PRs, for both newcomers and maintainers to hopefully guide them into titling and labeling PRs appropriately.
None.
See what I mean, this is just busywork :)
=> [Docs] Simplify PR template

sources/core/Stride.Core.Mathematics.Tests/TestPoint.cs
I was looking through places to add testing in the game engine and found that there were no tests for the Point class in Stride.Mathematics. In order to add completeness and increase code coverage of the system, I figured I would add a couple simple tests _just_ to make sure that the points are working as they are supposed to.
I added a couple simple tests for the Point class in Stride.Mathematics. They are very basic and can be added to or modified if desired.
There is no issue related to this pull request.
This change is not required. I simply added a couple tests to increase code coverage of the project.
- [x ] All new and existing tests passed.
- [x ] **I have built and run the editor to try this change out.**
=> created a basic class to test points

.github/release.yml
Areas added based on the new GitHub labels and some emojis changed.
- Added: area-Core, area-Math, area-Serialization
- Emojis changed: area-Graphics, area-UI, area-Rendering
N/a
=> feat: New areas added

sources/core/Stride.Core.Yaml/Serialization/SerializerSettings.cs, sources/engine/Stride.Games/GameWindow.cs, sources/engine/Stride.Rendering/Rendering/GraphicsRendererCollectionBase.cs, sources/engine/Stride.Rendering/Rendering/Images/ColorTransforms/ColorTransformBase.cs, sources/tools/Stride.TextureConverter/Backend/Wrappers/FINetWrapper/Classes/MemoryArray.cs
I have occasionally had vague null exceptions while running projects. This should make debugging a little easier to find what values are throwing the error.
=> added simple descriptions to null exceptions

deps/VHACD/linux-x64/VHACD.so, sources/engine/Stride.Assets/Stride.Assets.csproj
This PR adds the generated binary of VHACD shared library for Linux using my [BulletSharp fork](https://github.com/Jklawreszuk/BulletSharpPInvoke)
=> feat: Add linux VHACD shared library

sources/shared/Stride.NuGetResolver.Targets/Stride.NuGetResolver.Targets.projitems
=> Fixes assembly load failure when building Stride based project on clean machine

sources/engine/Stride.VirtualReality/OpenXR/OpenXRExt_FB_passthrough.cs
its a very simple PR , fix a little Compile Warnings in Rider IDE
=> Fix Compile Warnings

sources/engine/Stride.Graphics/GeometricPrimitives/GeometricPrimitive.Torus.cs
=> Update : GeometricPrimitive.Torus.cs

build/BuildXmlDocumentation.bat, build/BuildXmlDocumentationVS2015.bat, build/KillMSBuild.bat, build/NugetExtractFix.ps1, build/compile.bat
PR removes unused files located in build folder. I also fixed BuildXmlDocumentation.bat file
=> fix: Build folder cleanup

samples/Templates/VRSandbox/VRSandbox/VRSandbox.Windows/VRSandboxApp.cs
Patch for typo introduced in #2187
=> fix: Typo in VRSandboxApp

sources/editor/Stride.Samples.Templates/ThisPackageVersion.DevBuild.cs, sources/editor/Stride.Samples.Templates/ThisPackageVersion.PackageBuild.cs
After modifying the templates for the samples (#2109), the package version must be bumped.
#2354
=> fix: Bump samples version

sources/data/images/Logo/stride-logo-readme.png, sources/data/images/ReleaseNotes/1.2/DefaultScene.png, sources/data/images/ReleaseNotes/1.2/LiveScripting.png, sources/data/images/ReleaseNotes/1.2/Material-highlight0.png, sources/data/images/ReleaseNotes/1.2/Material-highlight1.gif, sources/data/images/ReleaseNotes/1.2/Material-highlight1.png, sources/data/images/ReleaseNotes/1.2/Material-highlight2.gif, sources/data/images/ReleaseNotes/1.2/Material-highlight2.png, sources/data/images/ReleaseNotes/1.2/ScriptReloading1.png, sources/data/images/ReleaseNotes/1.2/ScriptReloading2.png, sources/data/images/ReleaseNotes/1.2/UserDoc.png, sources/data/images/ReleaseNotes/1.2/Windows10.png, sources/data/images/ReleaseNotes/1.3/CameraMenu.png, sources/data/images/ReleaseNotes/1.3/MagicWand.gif, sources/data/images/ReleaseNotes/1.3/NavigationGizmo.gif, sources/data/images/ReleaseNotes/1.3/RootAssets.png, sources/data/images/ReleaseNotes/1.3/SceneFolders.png, sources/data/images/ReleaseNotes/1.3/SceneSettings.png, sources/data/images/ReleaseNotes/1.3/SpriteEditorLeft.png, sources/data/images/SplashScreen/splashscreen.jpg, sources/data/images/SplashScreen/splashscreen.psd, sources/data/renorm.bin
Another round of looking for unused files in the source code :) My PR removes unused data from `data` folder
=> fix: Remove unused data

sources/assets/Stride.Core.Assets/Bundle.cs, sources/assets/Stride.Core.Assets/OverrideUpgraderHint.cs, sources/core/Stride.Core.Mathematics/CollisionHelper.cs, sources/core/Stride.Core.MicroThreading/MicroThread.cs, sources/engine/Stride.Engine/Animations/AnimationCurve.cs, sources/engine/Stride.Engine/Audio/AudioEmitterSoundController.cs, sources/engine/Stride.Engine/Engine/AudioEmitterComponent.cs, sources/engine/Stride.Engine/Engine/Design/EffectCompilationMode.cs, sources/engine/Stride.Engine/Engine/Entity.cs, sources/engine/Stride.Engine/Engine/EntityManager.cs, sources/engine/Stride.Engine/Engine/InstancingUserBuffer.cs, sources/engine/Stride.Engine/Engine/Network/ClientRouterMessage.cs, sources/engine/Stride.Engine/Profiling/GameProfilingSystem.cs, sources/engine/Stride.Engine/Updater/ArrayUpdateResolver.cs, sources/engine/Stride.Graphics/CommandList.cs, sources/engine/Stride.Graphics/GraphicsDeviceExtensions.cs, sources/engine/Stride.Rendering/Rendering/RenderContext.cs
Fixing XML comments issues.
https://github.com/stride3d/stride/issues/1681
=> fix: Xml comments fix 5

sources/engine/Stride.Engine/Engine/Entity.cs
The comment for the `Entity` class has been updated to provide a more detailed description. It now specifies that the class represents a game entity that typically aggregates multiple `EntityComponent` instances. Additionally, it includes references to the Stride documentation for more information about adding and managing entities.
(https://github.com/stride3d/stride/discussions/1745)
=> docs: Enhance Entity class comment with detailed description.

sources/core/Stride.Core.Design/VisualStudio/SolutionReader.cs
As title suggests my PR allow to load sln files by adjusting slashes. Main motivation relates to future xplat GameStudio project
=> fix: Adjust Solution.cs for all platforms

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs, sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs, sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs
=> fix: very minor prop. grid presentation changes for bepu

sources/engine/Stride.Audio/AudioEngine.iOS.cs
=> fix: Remove unused using directive in Stride.Audio

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollisionMask.cs
=> fix: Minor xml issue with Bepu extensions

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BepuSimulation.cs
=> feat: Bepu, Allow user to set thread count

sources/Directory.Packages.props
Reverts stride3d/stride#2548
See this discussion for more context https://github.com/stride3d/stride/issues/2566
=> Revert "chore: Update ServiceWire package to version 5.6.0"

sources/Directory.Packages.props
Missed syncing the last Silk library...
Fixes #2349
Fixes #2348
=> fix: missing version update of Silk.NET to version 2.22.0

sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Animation/AnimationBlend.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Animation/AnimationStart.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/BasicCameraController.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/FpsCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/FreeCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/OrbitCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Camera/SideScrollingCamera.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/DefaultAsyncScript.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/DefaultStartupScript.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/DefaultSyncScript.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Events/EventBroadcaster.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Events/EventListener.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Physics/DebugShapesRender.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Physics/PlayerController.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Prefabs/PrefabInstance.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Utility/GameProfiler.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Utility/SceneStreaming.cs, sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.Android/$PackageGameNameShort$Activity.cs.t4, sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectExecutable.iOS/$PackageGameNameShort$AppDelegate.cs.t4, sources/editor/Stride.Assets.Presentation/Templates/Core/ProjectLibrary/Class1.cs.t4
PR modernizes current script templates mainly by using file-scoped namespaces
=> refactor: Modernize script templates

sources/tools/Stride.VisualStudio.Package/Stride.VisualStudio.Package.csproj, sources/tools/Stride.VisualStudio.PackageInstall/Program.cs, sources/tools/Stride.VisualStudio.PackageInstall/Stride.VisualStudio.PackageInstall.csproj
Quick fix for latest PR #2683 that fixes file locations
=> fix: Update file location for #2683

sources/Directory.Packages.props
Fixes a major issue related to convex hulls
https://github.com/bepu/bepuphysics2/issues/325
=> chore: Update bepu to 2.5.0-beta.25

sources/engine/Stride.UI/Rendering/UI/UIRenderProcessor.cs
`RenderViewStage` selected for a given `RenderObject` is set on `VisibilityGroup.RenderObjects.Add`. If the `RenderObject` does not have the right `RenderGroup` set at that point, it will be stuck assigned to the `RenderStage` for `RenderGroup.Group0`.
This PR ensures the `RenderGroup` is set as soon as the `RenderObject` for the UI is created, and force update the `RenderViewStage` whenever the UI's `RenderGroup` changes.
This is the repro: [MyGame7.zip](https://github.com/user-attachments/files/19591456/MyGame7.zip)
Press `Q/W/E` to toggle the three UI components in the scene. Before this PR, only the one at the center works even though the only difference compared to the other two is that it starts off enabled.
Fix #2033
=> fix: Non-default RenderGroup and changing RenderGroup at runtime for UI

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs, sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/CollidableComponent.cs, sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Colliders/CompoundCollider.cs
=> feat: Cleanup editor UI for CollidableComponents

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/BodyComponent.cs
Setters for position and orientation were too often misused by users, added an obsolete attribute on them to notify users of the alternatives and added in `SetTargetPose` helper to handle behavior those users expected.
Mostly reported on discord, some discussion around it in #2649
=> feat: SetTargetPose and deprecate setters for Position and Orientation

README.md
This PR fixes the logo in Readme.md so that it now changes color based on the user's theme.
#2726
=> #2726 Use different logos in README.md for different themes

sources/launcher/Stride.Launcher/Stride.Launcher.csproj, sources/launcher/Stride.Launcher/Views/MainView.axaml
A project reference was broken following f654d88ff513bd1fb70320bafef579d3067011a9. And a few data bindings in XAML had an incorrect syntax.
=> ⬇️🟢𝐒 New launcher bug fixes

sources/editor/Stride.Assets.Presentation/AssetEditors/EntityHierarchyEditor/Game/EditorGameEntityCameraService.cs
Remove this obnoxious mouse cursor lock+hiding away when right clicking.
https://github.com/stride3d/stride/assets/5742236/0f231d16-654c-4489-9323-2866a4319f64
=> [Input] Prevent locking the mouse cursor when selecting

README.md
This PR adds a a blank space so it matches VS Prerequisites names. And so we can copy and paste the prerequisites into VS Installer.
=> feat: Update README.md - Add a blank space

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Definitions/Colliders/CompoundCollider.cs
- Added XML documentation comments to the `CompoundCollider` class.
- Included a summary and remarks explaining the class's purpose and functionality.
- Added documentation for the `Colliders` property, detailing its role in the compound collider structure.
=> feat: CompoundCollider.cs - Add XML documentation comments

sources/launcher/Stride.Launcher/Stride.Launcher.csproj, sources/launcher/Stride.Launcher/ViewModels/LauncherViewModel.cs, sources/launcher/Stride.Launcher/Views/LauncherWindow.xaml.cs
Recent refactorings broke the build of the launcher (see #2658 and #2683).
=> fix: [Launcher] Fix build after #2658 and #2683

sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyAngularServoConstraintComponent.cs, sources/engine/Stride.BepuPhysics/Stride.BepuPhysics/Constraints/OneBodyLinearServoConstraintComponent.cs
=> fix: Bepu, normalize default servo settings across servo constraints

samples/Templates/FirstPersonShooter/FirstPersonShooter/FirstPersonShooter.Game/Player/AnimationController.cs, samples/Templates/ThirdPersonPlatformer/ThirdPersonPlatformer/ThirdPersonPlatformer.Game/Player/AnimationController.cs, samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/Core/Utils.cs, samples/Templates/TopDownRPG/TopDownRPG/TopDownRPG.Game/Player/AnimationController.cs, sources/editor/Stride.Assets.Presentation/Templates/Assets/Scripts/Animation/AnimationBlend.cs
=> fix: Remove usage of FastList from samples following PR #2798
